### ISSUE TITLE
微调训练-sovitas训练warn("Detected call of `lr_scheduler.step()` before `optimizer.step()之后报错

### ISSUE THREAD

**Issue by 2268190072** [RVC-Boss/GPT-SoVITS#1017]
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 125, in _main
  File "multiprocessing\spawn.py", line 236, in prepare
  File "multiprocessing\spawn.py", line 287, in _fixup_main_from_path
  File "runpy.py", line 288, in run_path
  File "runpy.py", line 97, in _run_module_code
  File "runpy.py", line 87, in _run_code
  File "F:\GPT-SoVITS-beta0217\GPT_SoVITS\s2_train.py", line 1, in <module>
    import utils, os
  File "F:\GPT-SoVITS-beta0217\GPT_SoVITS\utils.py", line 13, in <module>
    import torch
  File "F:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\__init__.py", line 1465, in <module>
    from . import _meta_registrations
  File "F:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\_meta_registrations.py", line 2705, in <module>
    activate_meta()
  File "F:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\_meta_registrations.py", line 2702, in activate_meta
    _meta_lib_dont_use_me_use_register_meta.impl(op_overload, fn)
  File "F:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\library.py", line 126, in impl
    self.m.impl(name, dispatch_key if dispatch_key != "" else "CompositeImplicitAutograd", fn)
RuntimeError: bad allocation

**Comment by RVC-Boss** [comment]
显存不太够
