### ISSUE TITLE
go-webui.bat在启动后报错，刚刚下载的时候明明正常打开的

### ISSUE THREAD

**Issue by MatthewHA233** [RVC-Boss/GPT-SoVITS#1027]
D:\my files\GPT-SoVITS-beta0217fix>runtime\python.exe webui.py
Traceback (most recent call last):
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\my files\GPT-SoVITS-beta0217fix\webui.py", line 48, in <module>
    import gradio as gr
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "D:\my files\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

D:\my files\GPT-SoVITS-beta0217fix>pause
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/74890172/cfbdc347-3e99-44e9-b36d-991e55d99f7e)
估计是因为开过全局代理的原因，但是我关闭代理，重启了电脑，重新解压缩了，都没用

**Comment by 385766470** [comment]
G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>runtime\python.exe webui.py
Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\webui.py", line 48, in <module>
    import gradio as gr
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>pause
请按任意键继续. . .
今天突然这样了，有哪位大佬能够帮忙解释一下呢？

**Comment by xuzhijiang** [comment]
刚刚遇到了一样的问题

**Comment by 385766470** [comment]
> 刚刚遇到了一样的问题

如有解决方案，请告知一下，谢谢！

**Comment by Liuxin4950** [comment]
G:\AiTool\GPT-SoVITS>runtime\python.exe webui.py
Traceback (most recent call last):
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AiTool\GPT-SoVITS\webui.py", line 48, in <module>
    import gradio as gr
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

G:\AiTool\GPT-SoVITS>pause
请按任意键继续. . .


我也遇见了，不会是某个依赖挂了吧

**Comment by blackbulaji** [comment]
一样的报错

**Comment by Liuxin4950** [comment]
其他人二次开发的还可以用，离谱

**Comment by alfredzhou1902** [comment]
今天遇到一样的问题，应该是gadio包的string.py文件在申请更新内容时网络出现问题（应该是网站挂了）
只需要找到runtime\Lib\site-packages\gradio\strings.py,把下图绿色框内容注释掉就行了
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/21978365/50020912-b6d3-42f2-a9f0-eac673a7b2a6)
````python
# try:
#     updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
#     en.update(updated_messaging)
# except (
#     requests.ConnectionError,
#     requests.exceptions.ReadTimeout,
#     json.decoder.JSONDecodeError,
# ):  # Use default messaging
#     pass
```

**Comment by Liuxin4950** [comment]
这样吗？谢谢你，我试试

**Comment by Liuxin4950** [comment]
可以了，nb，我知道是啥玩意没了，就是找不到位置，大佬赛高

**Comment by stella0909** [comment]
感谢大佬！刚刚遇到一模一样的问题！

**Comment by MatthewHA233** [comment]
好像已经能用了恢复正常了

**Comment by 385766470** [comment]
感谢大佬！果然有效，立竿见影!

**Comment by 385766470** [comment]
> 可能的解决方案(solution)：
> 
> 今天遇到一样的问题，应该是gadio包的string.py文件在申请更新内容时网络出现问题（应该是网站挂了） 只需要找到runtime\Lib\site-packages\gradio\strings.py,把下图绿色框内容注释掉就行了 ![image](https://private-user-images.githubusercontent.com/21978365/326171596-50020912-b6d3-42f2-a9f0-eac673a7b2a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODUyOTIsIm5iZiI6MTcxNDI4NDk5MiwicGF0aCI6Ii8yMTk3ODM2NS8zMjYxNzE1OTYtNTAwMjA5MTItYjZkMy00MmYyLWE5ZjAtZWFjNjczYTdiMmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Zjc0ZTM3MjQyMzQ4YWRhZGY1ZDM3MGU4MjU0M2M4NjYxYjc4OTY1YjYzZDQ1N2ZkNGJhNTAzNTYzM2MyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5BycqDX_mONu6TYIafPgwv55CtaBAOEAeaulqLNcec)
> 
> ```python
> # try:
> #     updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
> #     en.update(updated_messaging)
> # except (
> #     requests.ConnectionError,
> #     requests.exceptions.ReadTimeout,
> #     json.decoder.JSONDecodeError,
> # ):  # Use default messaging
> #     pass
> ``

> 可能的解决方案(solution)：
> 
> 今天遇到一样的问题，应该是gadio包的string.py文件在申请更新内容时网络出现问题（应该是网站挂了） 只需要找到runtime\Lib\site-packages\gradio\strings.py,把下图绿色框内容注释掉就行了 ![image](https://private-user-images.githubusercontent.com/21978365/326171596-50020912-b6d3-42f2-a9f0-eac673a7b2a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODUyOTIsIm5iZiI6MTcxNDI4NDk5MiwicGF0aCI6Ii8yMTk3ODM2NS8zMjYxNzE1OTYtNTAwMjA5MTItYjZkMy00MmYyLWE5ZjAtZWFjNjczYTdiMmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Zjc0ZTM3MjQyMzQ4YWRhZGY1ZDM3MGU4MjU0M2M4NjYxYjc4OTY1YjYzZDQ1N2ZkNGJhNTAzNTYzM2MyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5BycqDX_mONu6TYIafPgwv55CtaBAOEAeaulqLNcec)
> 
> ```python
> # try:
> #     updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
> #     en.update(updated_messaging)
> # except (
> #     requests.ConnectionError,
> #     requests.exceptions.ReadTimeout,
> #     json.decoder.JSONDecodeError,
> # ):  # Use default messaging
> #     pass
> ```

果然有效，谢谢大佬！

**Comment by RVC-Boss** [comment]
感谢楼上的指导，这就把整合包所有gradio联网语句注释掉，防止后续又出问题

**Comment by jiehai4** [comment]
我连“runtime\python.exe webui.py”都运行不了，显示“runtime\python.exe”不是内部或外部命令，但问题是我做的其他的python开发都可以正常用python，python --version也没问题，就这个不行，也不知道为啥

**Comment by mraili1** [comment]
E:\GPT\freegpt-webui>python run.py
Traceback (most recent call last):
  File "E:\GPT\freegpt-webui\run.py", line 3, in <module>
    from server.bp import bp
  File "E:\GPT\freegpt-webui\server\bp.py", line 1, in <module>
    from flask import Blueprint
ModuleNotFoundError: No module named 'flask'

E:\GPT\freegpt
显示这样是怎么回事呢

**Comment by XXXXRT666** [comment]
问错地方了，这不是GSV
