### ISSUE TITLE
昨天都可以正常运行，今天就不行了

### ISSUE THREAD

**Issue by Liuxin4950** [RVC-Boss/GPT-SoVITS#1028]
它一直报这个错，我解压了个新的也报这个错误，换了电脑也一样
G:\AiTool\GPT-SoVITS>runtime\python.exe webui.py
Traceback (most recent call last):
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AiTool\GPT-SoVITS\webui.py", line 48, in <module>
    import gradio as gr
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

G:\AiTool\GPT-SoVITS>pause
请按任意键继续. . .

**Comment by alfredzhou1902** [comment]
> 它一直报这个错，我解压了个新的也报这个错误，换了电脑也一样 G:\AiTool\GPT-SoVITS>runtime\python.exe webui.py Traceback (most recent call last): File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 971, in json return complexjson.loads(self.text, **kwargs) File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson__init__.py", line 514, in loads return _default_decoder.decode(s) File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode obj, end = self.raw_decode(s) File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "G:\AiTool\GPT-SoVITS\webui.py", line 48, in import gradio as gr File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio__init__.py", line 3, in import gradio.components as components File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\components.py", line 35, in from gradio.blocks import Block File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 33, in from gradio import ( File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\gradio\strings.py", line 37, in updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json() File "G:\AiTool\GPT-SoVITS\runtime\lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> G:\AiTool\GPT-SoVITS>pause 请按任意键继续. . .

参考：[我的回答](https://github.com/RVC-Boss/GPT-SoVITS/issues/1027#issuecomment-2080444820)

**Comment by Liuxin4950** [comment]
解决了https://github.com/RVC-Boss/GPT-SoVITS/issues/1027#issuecomment-2080444820
