### ISSUE TITLE
开启SoVits训练报错：OSError: [Errno 95] Operation not supported

### ISSUE THREAD

**Issue by YuChuanhui3** [RVC-Boss/GPT-SoVITS#1031]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 27 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
"/home/ych/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/s2_train.py --config "/mnt/d/AI/GPT-SoVITS/TEMP/tmp_s2.json"
INFO:ZYQ:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 10, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 8, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/ZYQ'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/ZYQ', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'ZYQ', 'pretrain': None, 'resume_step': None}
phoneme_data_len: 42
wav_data_len: 84
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:00<00:00, 1882.33it/s]
skipped_phone:  0 , skipped_dur:  2
total left:  82
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
ssl_proj.weight not requires_grad
ssl_proj.bias not requires_grad
INFO:ZYQ:loaded pretrained GPT_SoVITS/pretrained_models/s2G488k.pth
<All keys matched successfully>
INFO:ZYQ:loaded pretrained GPT_SoVITS/pretrained_models/s2D488k.pth
<All keys matched successfully>
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
0it [00:00, ?it/s]/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:665: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:873.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/ych/anaconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported

**Comment by Helium-327** [comment]
你好，请问问题解决了吗

**Comment by kingbo1587** [comment]
可能是pytorch版本有关系，默认装的是2.5.0，我这边机器cuda是12.1，我把pytorch降级到2.3.0了。降级后，重新安装了torchaudio
