### ISSUE TITLE
No module named 'jieba'，但是pip list 里面是有的

### ISSUE THREAD

**Issue by mawendi0990** [RVC-Boss/GPT-SoVITS#104]
Running on local URL:  http://0.0.0.0:9874
"C:\Users\lenovo\anaconda3\envs\GPTSoVits\python.exe" tools/damo_asr/cmd-asr.py "E:\GPT-SoVITS\output\slicer_opt"
2024-01-21 01:04:42,127 - modelscope - INFO - PyTorch version 2.1.2+cu121 Found.
2024-01-21 01:04:42,127 - modelscope - INFO - Loading ast index from C:\Users\lenovo\.cache\modelscope\ast_indexer
2024-01-21 01:04:42,345 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 5bd9ad0c38905b12e94457675d16b1ae and a total number of 946 components indexed
2024-01-21 01:04:46,097 - modelscope - WARNING - Model revision not specified, use revision: v1.2.1
2024-01-21 01:04:46,488 - modelscope - INFO - initiate model from C:\Users\lenovo\.cache\modelscope\hub\damo\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-21 01:04:46,488 - modelscope - INFO - initiate model from location C:\Users\lenovo\.cache\modelscope\hub\damo\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-21 01:04:46,488 - modelscope - INFO - initialize model from C:\Users\lenovo\.cache\modelscope\hub\damo\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-21 01:04:46,504 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-21 01:04:46,504 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-21 01:04:46,504 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\lenovo\\.cache\\modelscope\\hub\\damo\\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2024-01-21 01:04:46,504 - modelscope - WARNING - No preprocessor key ('generic-asr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-01-21 01:04:48,033 - modelscope - WARNING - Model revision not specified, use revision: v1.2.0
2024-01-21 01:04:48,292 - modelscope - INFO - loading vad model from C:\Users\lenovo\.cache\modelscope\hub\damo\speech_fsmn_vad_zh-cn-16k-common-pytorch ...
2024-01-21 01:04:49,145 - modelscope - WARNING - Model revision not specified, use revision: v1.1.7
2024-01-21 01:04:49,542 - modelscope - INFO - loading punctuation model from C:\Users\lenovo\.cache\modelscope\hub\damo\punc_ct-transformer_zh-cn-common-vocab272727-pytorch ...
Traceback (most recent call last):
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\modelscope\pipelines\audio\asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\funasr\bin\asr_inference_launch.py", line 34, in <module>
    from funasr.bin.punc_infer import Text2Punc
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\funasr\bin\punc_infer.py", line 14, in <module>
    from funasr.datasets.preprocessor import CodeMixTokenizerCommonPreprocessor
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\funasr\datasets\preprocessor.py", line 14, in <module>
    import jieba
ModuleNotFoundError: No module named 'jieba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GPT-SoVITS\tools\damo_asr\cmd-asr.py", line 9, in <module>
    inference_pipeline = pipeline(
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Users\lenovo\anaconda3\envs\GPTSoVits\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: AutomaticSpeechRecognitionPipeline: No module named 'jieba'

**Comment by http-404-usernotfound** [comment]
Try this:
```bash
pip install jieba
```

**Comment by RVC-Boss** [comment]
离谱。我没有思路，看看有没有其他人知道怎么解决的

**Comment by bihailantian655** [comment]
你不会有多个Python环境吧

**Comment by RoversX** [comment]
是不是虚拟环境没激活

**Comment by VINK77aaaa** [comment]
我也是这个问题，显示没有jieba这个依赖，但是已经确定安装上了，后来我尝试在文件夹上运行Windows PowerShell，然后py webui.py，在Windows PowerShell上运行，不要点go-webui.bat，就没有这个问题了

**Comment by danvan** [comment]
在当前虚拟环境下线卸载jieba ： pip uninstall jieba    然后重新安装一下 ：  pip install jieba   
如果不行  卸载后试试： pip3 install jieba
