### ISSUE TITLE
ASR执行出错：make sure the correct version of ModelScope library is used

### ISSUE THREAD

**Issue by yourfans** [RVC-Boss/GPT-SoVITS#105]
报错如下：
2024-01-21 02:18:31,695 - modelscope - WARNING - ('PIPELINES', 'auto-speech-recognition', 'funasr-pipeline') not found in ast index file
Traceback (most recent call last):
  File "/root/autodl-tmp/GPT-SoVITS/tools/damo_asr/cmd-asr.py", line 17, in <module>
    inference_pipeline = pipeline(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

根据别的issue中的方法，试过两种，但都不行：
1. 降级版本
pip uninstall funasr
pip uninstall modelscope
modelscope~=1.10.0
funasr~=0.8.7

2. clone三个模型文件到damo目录，修改tools/damo_asr/cmd_asr.py中模型文件目录
inference_pipeline = pipeline(
task=Tasks.auto_speech_recognition,
model='tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
vad_model='tools/damo_asr/models/speech_fsmn_vad_zh-cn-16k-common-pytorch',
punc_model='tools/damo_asr/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
)
改成

inference_pipeline = pipeline(
task=Tasks.auto_speech_recognition,
model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
)

**Comment by bruce2233** [comment]
#120 请问你是怎么解决的, 我这边也发现一个类似的错误

**Comment by ZhiYiy** [comment]
解决了吗

**Comment by LauraGPT** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/194#issuecomment-1910205929
