### ISSUE TITLE
生成日文语音出现Failed to initalize Mecab错误

### ISSUE THREAD

**Issue by kirbykirby** [RVC-Boss/GPT-SoVITS#1059]
ERROR: Mecab_load() in mecab.cpp: Cannot open D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\pyopenjtalk\open_jtalk_dic_utf_8-1.11.
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\inference_webui.py", line 121, in inference
    for item in tts_pipeline.run(inputs):
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 675, in run
    data = self.text_preprocessor.preprocess(text, text_lang, text_split_method)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 61, in preprocess
    phones, bert_features, norm_text = self.segment_and_extract_feature_for_text(text, lang)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 111, in segment_and_extract_feature_for_text
    phones, bert_features, norm_text = self.extract_bert_feature(textlist, langlist)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 164, in extract_bert_feature
    phones, word2ph, norm_text = self.clean_text_inf(textlist[i], lang)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 192, in clean_text_inf
    phones, word2ph, norm_text = clean_text(text, language)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 26, in clean_text
    phones = language_module.g2p(norm_text)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\text\japanese.py", line 183, in g2p
    phones = preprocess_jap(norm_text, with_prosody)
  File "D:\声音克隆\GPT-SoVITS\GPT_SoVITS\text\japanese.py", line 85, in preprocess_jap
    p = pyopenjtalk.g2p(sentence)
  File "D:\声音克隆\GPT-SoVITS\runtime\lib\site-packages\pyopenjtalk\__init__.py", line 100, in g2p
    _global_jtalk = OpenJTalk(dn_mecab=OPEN_JTALK_DICT_DIR)
  File "pyopenjtalk\\openjtalk.pyx", line 142, in pyopenjtalk.openjtalk.OpenJTalk.__cinit__
RuntimeError: Failed to initalize Mecab

**Comment by XXXXRT666** [comment]
中文路径

**Comment by kirbykirby** [comment]
> 中文路径

改成英文路径后出现这个报错：
Traceback(most recent call last):File “D:\Sound cloning\GPT-SoVITS\GPT-SoVITS\inference_webui.py", 1ine 39, in <module>from TTS infer pack.TTS import TTS, TTS ConfigmoduleNotFoundError: No module named 'TTS infer pack’

**Comment by XXXXRT666** [comment]
工作路径问题？需要在GPT_SoVITS上层目录启动

**Comment by ranfengqaq** [comment]
我也是这个报错，楼主解决了吗
‘

**Comment by TansVioletta** [comment]
同问，不知道哪里出了问题
