### ISSUE TITLE
启动推理服务时出错：libstdc++.so.6: version `GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by yourfans** [RVC-Boss/GPT-SoVITS#106]
报错如下：
`(GPTSoVits) root@autodl-container-28d94f9faf-1cfbd1cd:~/autodl-tmp/GPT-SoVITS# python GPT_SoVITS/inference_webui.py 
Traceback (most recent call last):
  File "/root/autodl-tmp/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 28, in <module>
    from text.cleaner import clean_text
  File "/root/autodl-tmp/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/root/autodl-tmp/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 5, in <module>
    import pyopenjtalk
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/pyopenjtalk/__init__.py", line 21, in <module>
    from .openjtalk import OpenJTalk
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/pyopenjtalk/openjtalk.cpython-39-x86_64-linux-gnu.so)`

看了一下：strings /root/miniconda3/envs/GPTSoVits/lib/libstdc++.so.6.0.32 | grep GLIBCXX
是有GLIBCXX_3.4.32的。

**Comment by yourfans** [comment]
将libstdc++.so.6的软连接重新指向6.0.32版本的就可以了。
