### ISSUE TITLE
Another "ZeroDivisionError: division by zero" .

### ISSUE THREAD

**Issue by hereTac** [RVC-Boss/GPT-SoVITS#1142]
The error message
```
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-GPT_SoVITS/GPT_SoVITS/s1_train.py", line 180, in <module>
    main(args)
  File "/root/ComfyUI/custom_nodes/ComfyUI-GPT_SoVITS/GPT_SoVITS/s1_train.py", line 156, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/root/ComfyUI/exchange/ComfyUI-GPT_SoVITS/GPT_SoVITS/AR/data/data_module.py", line 30, in setup
    self._train_dataset = Text2SemanticDataset(
  File "/root/ComfyUI/exchange/ComfyUI-GPT_SoVITS/GPT_SoVITS/AR/data/dataset.py", line 108, in __init__
    self.init_batch()
  File "/root/ComfyUI/exchange/ComfyUI-GPT_SoVITS/GPT_SoVITS/AR/data/dataset.py", line 219, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero
```
I debug the `GPT_SoVITS/AR/data/dataset.py` file, get  `leng = len(self.semantic_phoneme)` is 0.
The loop continue here, I do not know what are the values mean, any help will be grateful.

`print(ps_ratio,self.max_ps_ratio , self.min_ps_ratio, num_deleted_ps)`
`247.91666666666669 25 3 0`

```
 if (
                ps_ratio > self.max_ps_ratio or ps_ratio < self.min_ps_ratio
            ):  ##########4#3~25#�~O�~R�~Z�~Q个phone
                num_deleted_ps += 1
                # print(item_name)
                continue
```

**Comment by RVC-Boss** [comment]
ps_ratio = len(phoneme_ids) / (len(semantic_ids) / self.hz)

high ps_ratio means you speak very fast.
If you confirm that your training set's speaking speed is normal, you can increase self.max_ps_ratio and self.min_ps_ratio by 10~20 times.
