### ISSUE TITLE
api_v2.py中workers大于1的时候，子进程会一直重启

### ISSUE THREAD

**Issue by ctrlcplusv** [RVC-Boss/GPT-SoVITS#1183]
api_v2.py中workers等于1的时候，一切正常，workers大于1的时候，子进程会一直重启，显存是24G的，肯定够用，有人碰到这种情况吗？

**Comment by v3ucn** [comment]
```
if __name__ == '__main__':

    # 阻止子进程重启
    import multiprocessing
    multiprocessing.freeze_support()
    # ------------------------------------

    # 封装前运行
    uvicorn.run(app="api_v2:app", host="0.0.0.0", port=12233, workers=5)

```

**Comment by lckj2009** [comment]
请问，api_v2.py在哪里？没找到这个文件

**Comment by v3ucn** [comment]
> 请问，api_v2.py在哪里？没找到这个文件

在 fast_inference_分支

**Comment by ctrlcplusv** [comment]
> ```
> if __name__ == '__main__':
> 
>     # 阻止子进程重启
>     import multiprocessing
>     multiprocessing.freeze_support()
>     # ------------------------------------
> 
>     # 封装前运行
>     uvicorn.run(app="api_v2:app", host="0.0.0.0", port=12233, workers=5)
> ```

还是有问题，报错这个
![Snipaste_2024-06-13_18-31-00](https://github.com/RVC-Boss/GPT-SoVITS/assets/70870915/68bfb1dd-0ab3-4a90-82cd-00dbcafa8373)

**Comment by lckj2009** [comment]
> > 请问，api_v2.py在哪里？没找到这个文件
> 
> 在 fast_inference_分支

你好，fast_inference_分支在哪里呀，GPT-SoVITS目录里面没找到

**Comment by Separatee** [comment]
> > > 请问，api_v2.py在哪里？没找到这个文件
> > 
> > 
> > 在 fast_inference_分支
> 
> 你好，fast_inference_分支在哪里呀，GPT-SoVITS目录里面没找到

@lckj2009 第一次用github吗?在[仓库界面](http://github.com/RVC-Boss/GPT-SoVITS)，从main切换到fast_inference_
![Here](https://github.com/RVC-Boss/GPT-SoVITS/assets/162851813/747d63ef-2638-4696-aba9-898e5dacf12e)

如果你想从当前的main版本切换到fast_inference_分支，只需要使用git，额外加上-b参数，即 -b fast_inference_。命令如下
````
git clone --depth=1 https://github.com/RVC-Boss/GPT-SoVITS.git -b fast_inference_
````
或者直接在切换后的分支界面点下载zip压缩包也可以。
把新下载的分支全部覆盖你的原文件
之后只需要额外的安装wordsegments包就能从main切换到fast_inference_了
````
/path/to/your/python -m pip install wordsegments
````

**Comment by wx971025** [comment]
一样的问题，workers大于1的时候，子进程会被莫名kill，unicorn的logger没有报错信息，然后不停重启，请问这个问题有解决方案吗？

**Comment by wx971025** [comment]
> > ```
> > if __name__ == '__main__':
> > 
> >     # 阻止子进程重启
> >     import multiprocessing
> >     multiprocessing.freeze_support()
> >     # ------------------------------------
> > 
> >     # 封装前运行
> >     uvicorn.run(app="api_v2:app", host="0.0.0.0", port=12233, workers=5)
> > ```
> 
> 还是有问题，报错这个 ![Snipaste_2024-06-13_18-31-00](https://private-user-images.githubusercontent.com/70870915/339326092-68bfb1dd-0ab3-4a90-82cd-00dbcafa8373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODk3OTksIm5iZiI6MTcyMTI4OTQ5OSwicGF0aCI6Ii83MDg3MDkxNS8zMzkzMjYwOTItNjhiZmIxZGQtMGFiMy00YTkwLTgyY2QtMDBkYmNhZmE4MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA3NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NjA4ODM2MWVkOWFmNDc5MDYyNWRjM2EwYTVhYmVlMGUwN2Y4NmJhMDA2ZGZhZjNiMmY3MmMyYTA5NmE3ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZLhslhzIo34OBVLVuJS5-lFlTMga7UnnWLFGWp_Hh4)

我遇到了相同的问题，当uvicorn==0.21.0时可以正常启动

**Comment by lckj2009** [comment]
> uvicorn

多谢，但是我尝试在 conda环境下运行 python api_v2.py。结果报错了，如下：

(GPT-SoVITS) E:\GPT-SoVITS>python api_v2.py
Loading Text2Semantic weights from GPT_weights/lvbu-e30.ckpt
Loading VITS weights from GPT_SoVITS/pretrained_models/s2G488k.pth
C:\Users\ww\anaconda3\envs\GPT-SoVITS\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading BERT weights from GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
C:\Users\ww\anaconda3\envs\GPT-SoVITS\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading CNHuBERT weights from GPT_SoVITS/pretrained_models/chinese-hubert-base
Traceback (most recent call last):
  File "E:\GPT-SoVITS\api_v2.py", line 143, in <module>
    tts_pipeline = TTS(tts_config)
  File "E:\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 205, in __init__
    self._init_models()
  File "E:\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 232, in _init_models
    self.init_cnhuhbert_weights(self.configs.cnhuhbert_base_path)
  File "E:\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 239, in init_cnhuhbert_weights
    self.cnhuhbert_model = CNHubert(base_path)
TypeError: CNHubert.__init__() takes 1 positional argument but 2 were given

**Comment by XXXXRT666** [comment]
检查代码,看看import的是哪里的CNHubert,你import的可能是Main分支

**Comment by XXXXRT666** [comment]
> 我clone的应该是Main分支。 api_v2.py和V3主要特点是什么，我还不明白。是不是现在流行用 fast_inference_ 分支的api_v2.py、v3?
去看看cnhubert.__path__

**Comment by lckj2009** [comment]
> > 我clone的应该是Main分支。 api_v2.py和V3主要特点是什么，我还不明白。是不是现在流行用 fast_inference_ 分支的api_v2.py、v3?
> 
> 去看看`cnhubert.__path__`

TTS.py 的一部分引用

from AR.models.t2s_lightning_module import Text2SemanticLightningModule
from feature_extractor.cnhubert import CNHubert
from module.models import SynthesizerTrn
import librosa
from time import time as ttime
from tools.i18n.i18n import I18nAuto
from my_utils import load_audio
from module.mel_processing import spectrogram_torch
from TTS_infer_pack.text_segmentation_method import splits
from TTS_infer_pack.TextPreprocessor import TextPreprocessor
i18n = I18nAuto()

**Comment by lckj2009** [comment]
(GPT-SoVITS) E:\bak>git clone https://github.com/RVC-Boss/GPT-SoVITS.git
Cloning into 'GPT-SoVITS'...
error: RPC failed; curl 28 Recv failure: Connection was reset
fatal: expected flush after ref listing

fast_inference_ 分支clone一直失败

**Comment by wx971025** [comment]
> (GPT-SoVITS) E:\bak>git clone https://github.com/RVC-Boss/GPT-SoVITS.git Cloning into 'GPT-SoVITS'... error: RPC failed; curl 28 Recv failure: Connection was reset fatal: expected flush after ref listing
> 
> fast_inference_ 分支clone一直失败

首先 clone特定分支要加-b参数，其次 你可以直接download一个项目的zip 解压使用

**Comment by XXXXRT666** [comment]
> TTS.py 的一部分引用

import之后让他print一下看看`__path__`

**Comment by lckj2009** [comment]
测试代码：
from feature_extractor.cnhubert import CNHubert

print(CNHubert.__path__)

运行结果：

已连接到 pydev 调试器(内部版本号 222.4554.11)Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\GPT-SoVITS-fast_inference_\ceshi.py", line 3, in <module>
    print(CNHubert.__path__)
AttributeError: type object 'CNHubert' has no attribute '__path__'. Did you mean: '__hash__'?
python-BaseException

**Comment by lckj2009** [comment]
测试代码：
from feature_extractor.cnhubert import CNHubert

print(CNHubert.__path__)

运行结果：

已连接到 pydev 调试器(内部版本号 222.4554.11)Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev\pydevd.py", line 1496, in exec
pydev_imports.execfile(file, globals, locals) # execute the script
File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "E:\GPT-SoVITS-fast_inference\ceshi.py", line 3, in
print(CNHubert.path)
AttributeError: type object 'CNHubert' has no attribute 'path'. Did you mean: 'hash'?
python-BaseException

**Comment by lckj2009** [comment]
已连接到 pydev 调试器(内部版本号 222.4554.11)Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\GPT-SoVITS-fast_inference_\ceshi.py", line 3, in <module>
    print(CNHubert.__file__)
AttributeError: type object 'CNHubert' has no attribute ' _ _file _ _'. Did you mean: ' _ _ le _ _'?

**Comment by XXXXRT666** [comment]
cnhubert和CNHubert是两个东西

**Comment by Separatee** [comment]
看了你启动失败的问题
尝试使用这个Windows版本(不要滥用下载链接):
[0306fix](https://xn--z0s.top/Fly_Ali/SO-VITS-GPT-AI/GPT-SoVITS-beta0306fix3.7z)

还有你克隆的方式不对，既然你当初git clone没有加参数,那么git默认把所有分支和commit都克隆了，请阅读git基本教程了解git的使用原理。请使用
````
git branch _fast_inference
````

````
git pull -f
````
切换到_fast_inference分支。
如果还是不行 尝试:
````
git remote remove origin && git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits
````
使用我的github镜像网站进行`git pull -f`

**Comment by lckj2009** [comment]
> > 去看看`cnhubert.__file__`
> 
> cnhubert和CNHubert是两个东西，而且需要知道的是报错前一刻他import的是哪个模块，而不是一个测试，直接在报错前`from feature_extractor import cnhubert`看看 `cnhubert.__file__`

![cuowu](https://github.com/user-attachments/assets/05059e2c-9ffe-4f2a-b907-4a011aaa91a2)

feature_extractor.cnhubert 里面只有 CNHubert，没有 cnhubert

**Comment by lckj2009** [comment]
> 看了你启动失败的问题 尝试使用这个Windows版本(不要滥用下载链接): [0306fix](https://xn--z0s.top/Fly_Ali/SO-VITS-GPT-AI/GPT-SoVITS-beta0306fix3.7z)
> 
> 还有你克隆的方式不对，既然你当初git clone没有加参数,那么git默认把所有分支和commit都克隆了，请阅读git基本教程了解git的使用原理。请使用
> 
> ```
> git branch _fast_inference
> ```
> 
> ```
> git pull -f
> ```
> 
> 切换到_fast_inference分支。 如果还是不行 尝试:
> 
> ```
> git remote remove origin && git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits
> ```
> 
> 使用我的github镜像网站进行`git pull -f`

连接下载不了，网速0。我尝试 git branch _fast_inference 看看

**Comment by Separatee** [comment]
> > 看了你启动失败的问题 尝试使用这个Windows版本(不要滥用下载链接): [0306fix](https://xn--z0s.top/Fly_Ali/SO-VITS-GPT-AI/GPT-SoVITS-beta0306fix3.7z)
> > 还有你克隆的方式不对，既然你当初git clone没有加参数,那么git默认把所有分支和commit都克隆了，请阅读git基本教程了解git的使用原理。请使用
> > ```
> > git branch _fast_inference
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > git pull -f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 切换到_fast_inference分支。 如果还是不行 尝试:
> > ```
> > git remote remove origin && git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用我的github镜像网站进行`git pull -f`
> 
> 连接下载不了，网速0。我尝试 git branch _fast_inference 看看

使用
`git remote -v`查看一下当前的远程服务器地址是否有误，实际上你只需要把前缀域名改一下,从github.com转为github.xn--z0s.top
还有你还可以试一下我最开始说的0306fix版本的下载链接(蓝色字体)

**Comment by Separatee** [comment]
> > 看了你启动失败的问题 尝试使用这个Windows版本(不要滥用下载链接): [0306fix](https://xn--z0s.top/Fly_Ali/SO-VITS-GPT-AI/GPT-SoVITS-beta0306fix3.7z)
> > 还有你克隆的方式不对，既然你当初git clone没有加参数,那么git默认把所有分支和commit都克隆了，请阅读git基本教程了解git的使用原理。请使用
> > ```
> > git branch _fast_inference
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > git pull -f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 切换到_fast_inference分支。 如果还是不行 尝试:
> > ```
> > git remote remove origin && git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用我的github镜像网站进行`git pull -f`
> 
> 连接下载不了，网速0。我尝试 git branch _fast_inference 看看

抱歉 我的说法有误,你应该在地址末尾加上.git
是
````
git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits.git
````
而不是
````
git remote add origin https://github.xn--z0s.top/rvc-boss/gpt-sovits
````

**Comment by lckj2009** [comment]
> 0306fix版本的下载链接

0306fix版本的下载链接，网速0。

**Comment by lckj2009** [comment]
![33](https://github.com/user-attachments/assets/186d85e7-417c-441e-b695-978dc9013295)

**Comment by Separatee** [comment]
> > 0306fix版本的下载链接
> 
> 0306fix版本的下载链接，网速0。

检查一下你是不是开魔法了 这是阿里云北京的CDN节点

**Comment by Separatee** [comment]
> ![33](https://github.com/user-attachments/assets/186d85e7-417c-441e-b695-978dc9013295)
> 

在你原来的文件夹里用这个命令

**Comment by lckj2009** [comment]
> > > 0306fix版本的下载链接
> > 
> > 
> > 0306fix版本的下载链接，网速0。
> 
> 检查一下你是不是开魔法了 这是阿里云北京的CDN节点

没有，迅雷下不了。360浏览器也是

**Comment by XXXXRT666** [comment]
> > > 去看看`cnhubert.__file__`
> > 
> > 
> > cnhubert和CNHubert是两个东西，而且需要知道的是报错前一刻他import的是哪个模块，而不是一个测试，直接在报错前`from feature_extractor import cnhubert`看看 `cnhubert.__file__`
> 
> feature_extractor.cnhubert 里面只有 CNHubert，没有 cnhubert

我说的就是cuhubert这个文件,就在你的TTS.py对应报错位置前加上,或者是你自己检查sys.path,两个分支共用环境可能导致import错误
```
from feature_extractor import cnhubert
print(cnhubert.__file__)
```

**Comment by Separatee** [comment]
> > > > 0306fix版本的下载链接
> > > 
> > > 
> > > 0306fix版本的下载链接，网速0。
> > 
> > 检查一下你是不是开魔法了 这是阿里云北京的CDN节点
> 
> 没有，迅雷下不了。360浏览器也是

…恕我直言,谁家下载用迅雷,换个Edge浏览器试试。

**Comment by lckj2009** [comment]
> > > > 去看看`cnhubert.__file__`
> > > 
> > > 
> > > cnhubert和CNHubert是两个东西，而且需要知道的是报错前一刻他import的是哪个模块，而不是一个测试，直接在报错前`from feature_extractor import cnhubert`看看 `cnhubert.__file__`
> > 
> > 
> > feature_extractor.cnhubert 里面只有 CNHubert，没有 cnhubert
> 
> 我说的就是cuhubert这个文件,就在你的TTS.py对应报错位置前加上,或者是你自己检查sys.path,两个分支共用环境可能导致import错误
> 
> ```
> from feature_extractor import cnhubert
> print(cnhubert.__file__)
> ```
> 
> shell执行 `python -c "import sys;print(sys.path)"`

E:\GPT-SoVITS\GPT_SoVITS\feature_extractor\cnhubert.py  准确的找到了文件地址。

**Comment by XXXXRT666** [comment]
> E:\GPT-SoVITS\GPT_SoVITS\feature_extractor\cnhubert.py 准确的找到了文件地址。

看上下文的话,你调用的TTS.py在GPT-SoVITS-fast_infernence_里面

**Comment by lckj2009** [comment]
> > > > > 0306fix版本的下载链接
> > > > 
> > > > 
> > > > 0306fix版本的下载链接，网速0。
> > > 
> > > 
> > > 检查一下你是不是开魔法了 这是阿里云北京的CDN节点
> > 
> > 
> > 没有，迅雷下不了。360浏览器也是
> 
> …恕我直言,谁家下载用迅雷,换个Edge浏览器试试。

![1](https://github.com/user-attachments/assets/c531eaaa-c89a-43b1-a971-74e6c42effb9)

**Comment by XXXXRT666** [comment]
> 看上下文的话,你调用的TTS.py在GPT-SoVITS-fast_infernence_里面

你是不是本地还有一个Main分支,和fast inference分支属于同时存在而不是git切换的状态

**Comment by lckj2009** [comment]
> > 看上下文的话,你调用的TTS.py在GPT-SoVITS-fast_infernence_里面
> 
> 你是不是本地还有一个Main分支,和fast inference分支属于同时存在而不是git切换的状态

是这样的，刚才，我在 E:\GPT-SoVITS-fast_inference_  文件夹里新建了一个ceshi.py。代码只有：
from feature_extractor import cnhubert
print(cnhubert.__file__)
这2行，运行时打印了：E:\GPT-SoVITS\GPT_SoVITS\feature_extractor\cnhubert.py
E:\GPT-SoVITS和E:\GPT-SoVITS-fast_inference_ 是2个文件夹。我估计是git版本把他们联系在一起的原因。

**Comment by XXXXRT666** [comment]
跟git没关系,建议分开建环境,或者去site-packages底下把users.pth清空

**Comment by lckj2009** [comment]
我还没测试在这种情况下，api_v2.py 能否运行。那么我可以测试一下？

命令就是 python api_v2.py ？无需其他参数？

**Comment by XXXXRT666** [comment]
users.pth只是为了更改sys.path的内容

**Comment by Separatee** [comment]
> 我还没测试在这种情况下，api_v2.py 能否运行。那么我可以测试一下？
> 
> 命令就是 python api_v2.py ？无需其他参数？

你可以回炉重造 在你的E盘根目录新建一个文件夹 仓库主页的Readme有0306fix的压缩包 下载下来然后把你的_fast_inference内部所有文件拖到解压后的文件夹内(覆盖并确认)
它可能会提示缺少wordsegments包那就在以当前目录打开CMD,输入`.\runtime\python -m pip install wordsegments`

**Comment by Separatee** [comment]
@lckj2009 我的域名是纯ipv6,无法访问,下载速度为0的情况应该是你的路由不支持IPV6。但问题不大。

**Comment by lckj2009** [comment]
> @lckj2009 我的域名是纯ipv6,无法访问,下载速度为0的情况应该是你的路由不支持IPV6。但问题不大。

我用同事的电脑下载成功了
