### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by younkoto** [RVC-Boss/GPT-SoVITS#1209]
求助，合成语音时出现了错误，结果是一个0秒的音频。o(╥﹏╥)o

当前使用的版本是

> GPT-SoVITS-beta0217fix3

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in call
return await self.app(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\fastapi\applications.py", line 270, in call
await super().call(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\applications.py", line 124, in call
await self.middleware_stack(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\middleware\errors.py", line 184, in call
raise exc
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\middleware\errors.py", line 162, in call
await self.app(scope, receive, _send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\middleware\cors.py", line 84, in call
await self.app(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 79, in call
raise exc
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 68, in call
await self.app(scope, receive, sender)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in call
raise e
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in call
await self.app(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\routing.py", line 706, in call
await route.handle(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\routing.py", line 276, in handle
await self.app(scope, receive, send)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\routing.py", line 66, in app
response = await func(request)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\fastapi\routing.py", line 235, in app
raw_response = await run_endpoint_function(
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
return await run_in_threadpool(dependant.call, **values)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
return await anyio.to_thread.run_sync(func, *args)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
result = context.run(func, *args)
File "X:#AItools\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\gradio\routes.py", line 272, in file
raise ValueError(
ValueError: File cannot be fetched: X:/. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

![屏幕截图 2024-06-19 170104](https://github.com/RVC-Boss/GPT-SoVITS/assets/136080672/f543ed1a-883f-4fee-bbb3-1bf41fdce23d)

**Comment by younkoto** [comment]
自己解决了，文件绝对路径的命名不能有下划线意外的符号。

**Comment by huchanglihcl** [comment]
和你有一样的问题，但文件中没特殊符号还是报这个错，我是api调用的时候，页面控制台上能正常输出
