### ISSUE TITLE
Close gradio connections when using ctrl+c to kill the webui.py  

### ISSUE THREAD

**Issue by bruce2233** [RVC-Boss/GPT-SoVITS#123]
```javascript
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/app/GPT-SoVITS/webui.py", line 744, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1347, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/networking.py", line 123, in start_server
    raise OSError(
OSError: Port 9874 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```
We have to wait for a long time.

**Comment by a-cold-bird** [comment]
try to reboot your server,or use lsof tool
`lsof -i:9874`
`kill [pid] -9`

**Comment by selfboot** [comment]
> ```js
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/app/GPT-SoVITS/webui.py", line 744, in <module>
>     app.queue(concurrency_count=511, max_size=1022).launch(
>   File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1347, in launch
>     server_name, server_port, local_url, app, server = networking.start_server(
>   File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/networking.py", line 123, in start_server
>     raise OSError(
> OSError: Port 9874 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
> ```
> 
> We have to wait for a long time.

same problem

**Comment by bruce2233** [comment]
> try to reboot your server,or use lsof tool `lsof -i:9874` `kill [pid] -9`

I tried this but lsof doesn't ouput any information and the port is still in use.

**Comment by Liu-yixi** [comment]
> > try to reboot your server,or use lsof tool `lsof -i:9874` `kill [pid] -9`
> 
> I tried this but lsof doesn't ouput any information and the port is still in use.

You can use `ps aux | grep python`, the kill the webui.py '[pid]
