### ISSUE TITLE
模型训练保存错误：PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。

### ISSUE THREAD

**Issue by xia-huang-411303** [RVC-Boss/GPT-SoVITS#1249]
### 环境
硬件：RTX4090
系统：Windows10
版本：GPT-SoVITS-beta0217fix2

### 错误描述
1Bb-GPT training 过程中保存模型权重遇到 PermissionError
```
Epoch 14: 100%|█| 22/22 [00:14<00:00,  1.47it/s, v_num=3, total_loss_step=1.14e+3, lr_step=0.002, top_3_acc_step=0.6`Trainer.fit` stopped: `max_epochs=15` reached.
Epoch 14: 100%|█| 22/22 [00:18<00:00,  1.18it/s, v_num=3, total_loss_step=1.14e+3, lr_step=0.002, top_3_acc_step=0.6
Traceback (most recent call last):
```

### 报错
```bash
Traceback (most recent call last):
  File "shutil.py", line 825, in move
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: '1719483526.6775331.pth' -> 'GPT_weights/zhaiweitang-e15.ckpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GIT\GPT-SoVITS-beta0217fix2\GPT_SoVITS\s1_train.py", line 180, in <module>
    main(args)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\GPT_SoVITS\s1_train.py", line 156, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 989, in _run
    results = self._run_stage()
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 203, in run
    self.on_advance_end()
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 374, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "E:\GIT\GPT-SoVITS-beta0217fix2\GPT_SoVITS\s1_train.py", line 82, in on_train_epoch_end
    my_save(
  File "E:\GIT\GPT-SoVITS-beta0217fix2\GPT_SoVITS\s1_train.py", line 34, in my_save
    shutil.move(tmp_path,"%s/%s"%(dir,name))
  File "shutil.py", line 846, in move
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: '1719483526.6775331.pth'
```

**Comment by xia-huang-411303** [comment]
\GPT_weights 下只有一个 xxx-e5.ckpt文件

**Comment by RVC-Boss** [comment]
看看你的webui参数设置的啥？

**Comment by xia-huang-411303** [comment]
> 看看你的webui参数设置的啥？
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/30041175/d2c17d0d-69f3-44dd-9013-ac895e5ab4cc)
就默认设置

PS，我通过反复启动，训练过程绕过这个BUG，最终完成16轮的训练

**Comment by RVC-Boss** [comment]
我知道问题了，你是两卡两进程训练，结果保存也两进程保存了，可能需要判一下当前rank，只有0的时候才保存

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/a208698e775155efc95b187b746d153d0f2847ca
https://github.com/RVC-Boss/GPT-SoVITS/commit/1ff74f001a0c75c538c86d615246d794c8a12968
已修复，更新最新的代码看看呢？

**Comment by xia-huang-411303** [comment]
> 我知道问题了，你是两卡两进程训练，结果保存也两进程保存了，可能需要判一下当前rank，只有0的时候才保存

是的！我都忘记说这点了，大佬牛逼！
