### ISSUE TITLE
人声伴奏分离批量处理， 使用UVR5模型。

### ISSUE THREAD

**Issue by plasx520** [RVC-Boss/GPT-SoVITS#1261]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/59572466/3eefc71e-b4aa-4c8f-abbf-560faeda8a1f)

`Screenrecording_20240630_12165703kdqlbt.mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\tools\uvr5\webui.py", line 81, in uvr
    pre_fun._path_audio_(
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\tools\uvr5\vr.py", line 121, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\tools\uvr5\lib\lib_v5\spec_utils.py", line 400, in cmb_spectrogram_to_wave
    wave = librosa.resample(
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\librosa\core\audio.py", line 606, in resample
    util.valid_audio(y, mono=False)
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\plasx\Desktop\GPT-SoVITS-beta0217fix3\runtime\lib\site-packages\librosa\util\utils.py", line 294, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
`

**Comment by SapphireLab** [comment]
这个报错一般是对语音处理时, 判断到数据中存在无穷或者 NaN，即不是所有值都有限。
可能的解决方案：
- 一般要检查一下你的语音文件有没有损坏。
  - 如果文件很大也可以先切分再做 UVR 这步，也可以定位出哪个语音片段有问题。
  - 也可能是 UVR5 代码的问题（毕竟他们仓库下面一大堆这个问题且无明确解决方案），这个需要后续看看能不能复现到。
- 可以使用 UVR5 单独的客户端，可能就正常了。（具体可以参考[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/xyyqrfwiu3e2bgyk#vffyq)）

**Comment by RVC-Boss** [comment]
这个可能需要你上传一下报错音频我才能排查

**Comment by wangziyao318** [comment]
这个[pull request](https://github.com/Anjok07/ultimatevocalremovergui/pull/1359)可能解决了这个问题，至少我用起来不报错了。


![Screenshot 2024-08-01 at 19 05 56](https://github.com/user-attachments/assets/82a99e98-cc79-481f-bbb8-a6a3e8295783)
