### ISSUE TITLE
叠词频繁出现错误但不是所有叠词均发生错误

### ISSUE THREAD

**Issue by 2132159285** [RVC-Boss/GPT-SoVITS#1271]
实际输入的目标文本(每句): 出发了，蒂蒂。
[[]]
[]
[]
Traceback (most recent call last):
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\GPT_SoVITS\inference_webui.py", line 438, in get_tts_wav
    bert2 = get_bert_final(phones2, word2ph2, norm_text2, text_language, device).to(dtype)
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\GPT_SoVITS\inference_webui.py", line 346, in get_bert_final
    bert = nonen_get_bert_inf(text, language)
  File "C:\Users\21321\Desktop\GPT-SoVITS-beta0217fix\GPT_SoVITS\inference_webui.py", line 321, in nonen_get_bert_inf
    bert = torch.cat(bert_list, dim=1)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

错误基本如上例子

如下不会发生错误
完蛋了啊啊啊啊啊啊！！
出发了蒂蒂。

**Comment by XXXXRT666** [comment]
使用仓库最新代码还会有如上错误吗

**Comment by 2132159285** [comment]
I download the latest version and it works well when I try the same sentence on it.
This problem is noticed in the old version.
thinks.
