### ISSUE TITLE
一键三连点击后 错误: 没有找到进程 "29408"。

### ISSUE THREAD

**Issue by kilopper** [RVC-Boss/GPT-SoVITS#1276]
D:\SD\GPT-SoVITS-beta0306fix3>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"D:\SD\GPT-SoVITS-beta0306fix3\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\SD\GPT-SoVITS-beta0306fix3\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
D:\SD\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\SD\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\SD\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\SD\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\SD\GPT-SoVITS-beta0306fix3\GPT_SoVITS\prepare_datasets\1-get-text.py", line 102, in <module>
  File "D:\SD\GPT-SoVITS-beta0306fix3\GPT_SoVITS\prepare_datasets\1-get-text.py", line 102, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'D:\\SD\\GPT-SoVITS-beta0306fix3\\output\\asr_opt'
    with open(inp_text, "r", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'D:\\SD\\GPT-SoVITS-beta0306fix3\\output\\asr_opt'
Traceback (most recent call last):
  File "D:\SD\GPT-SoVITS-beta0306fix3\webui.py", line 584, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/trump/2-name2text-0.txt'
错误: 没有找到进程 "29408"。
错误: 没有找到进程 "38160"。

**Comment by ChiaLinz** [comment]
檢查看看
`D:\SD\GPT-SoVITS-beta0306fix3\output\asr_opt`
資料夾內是否存在對應文本。
如果存在，請確認是否有權限問題阻止存取。

**Comment by XXXXRT666** [comment]
list路径

**Comment by kilopper** [comment]
路径是对的,里面也有list,我放在D盘一直提示没权限,这怎么搞?

**Comment by kilopper** [comment]
> 檢查看看 `D:\SD\GPT-SoVITS-beta0306fix3\output\asr_opt` 資料夾內是否存在對應文本。 如果存在，請確認是否有權限問題阻止存取。


路径是对的,里面也有list,我放在D盘一直提示没权限,这怎么搞?

**Comment by Separatee** [comment]
将以下代码重命名为.reg后缀的文件(请确保你理解后缀的含义)
之后双击注册,右键就会有为文件夹获取管理员权限了
````
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\*\shell\runas]
@="获取超级管理员权限"
"NoWorkingDirectory"=""
[HKEY_CLASSES_ROOT\*\shell\runas\command]
@="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
"IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
[HKEY_CLASSES_ROOT\exefile\shell\runas2]
@="获取超级管理员权限"
"NoWorkingDirectory"=""
[HKEY_CLASSES_ROOT\exefile\shell\runas2\command]
@="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
"IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"

[HKEY_CLASSES_ROOT\Directory\shell\runas]
@="获取超级管理员权限"
"NoWorkingDirectory"=""
[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
@="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
"IsolatedCommand"="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
````
最后别忘了右键D盘，属性 看看是否是只读状态

**Comment by caoshuxian** [comment]
> 将以下代码重命名为.reg后缀的文件（请确保你理解后缀的含义） 之后双击注册，右键就会有为文件夹获取管理员权限了
> 
> ```
> Windows Registry Editor Version 5.00
> [HKEY_CLASSES_ROOT\*\shell\runas]
> @="获取超级管理员权限"
> "NoWorkingDirectory"=""
> [HKEY_CLASSES_ROOT\*\shell\runas\command]
> @="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> [HKEY_CLASSES_ROOT\exefile\shell\runas2]
> @="获取超级管理员权限"
> "NoWorkingDirectory"=""
> [HKEY_CLASSES_ROOT\exefile\shell\runas2\command]
> @="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> 
> [HKEY_CLASSES_ROOT\Directory\shell\runas]
> @="获取超级管理员权限"
> "NoWorkingDirectory"=""
> [HKEY_CLASSES_ROOT\Directory\shell\runas\command]
> @="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> ```
> 
> 最后别忘了右键D盘，属性 看看是否是只读状态

我双击获取权限了，也是只读状态，地址也正确，但就是报错怎么办？

**Comment by XXXXRT666** [comment]
你的路径从来就没对过,一个文件夹肯定只读
