### ISSUE TITLE
IndexError: string index out of range  (最後一個步驟無法生成)

### ISSUE THREAD

**Issue by kai1040112** [RVC-Boss/GPT-SoVITS#1277]
Set seed to 3367266406
并行推理模式已开启
分桶处理模式已开启
实际输入的参考文本: 英文的恨有四个字母，但爱也是有四个字母。
############ 切分文本 ############
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\GPT-SoVITS-beta0306fix3\GPT_SoVITS\inference_webui.py", line 121, in inference
    for item in tts_pipeline.run(inputs):
  File "D:\GPT-SoVITS-beta0306fix3\runtime\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\GPT-SoVITS-beta0306fix3\GPT_SoVITS\TTS_infer_pack\TTS.py", line 681, in run
    data = self.text_preprocessor.preprocess(text, text_lang, text_split_method)
  File "D:\GPT-SoVITS-beta0306fix3\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 57, in preprocess
    texts = self.pre_seg_text(text, lang, text_split_method)
  File "D:\GPT-SoVITS-beta0306fix3\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 74, in pre_seg_text
    if (text[0] not in splits and len(get_first(text)) < 4):
IndexError: string index out of range

**Comment by ChasonJiang** [comment]
能给出详细的测试用例吗？包括：待合成的文本、合成的语言、切分方式

**Comment by rm7rzedg** [comment]
相同问题
步骤就是下载整合包,运行,
1-GPT-SoVITS-TTS -> 1C-推理 -> 选中"是否开启TTS推理WebUI"
在弹出的新窗口中从"需要合成的文本" 输入任意内容,然后选中不切,然后点击合成即出现

**Comment by hitashi0234** [comment]
我也有一樣的問題



Traceback (most recent call last):
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\blocks.py", line 1267, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\utils.py", line 574, in async_iteration
    return await iterator.__anext__()
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\utils.py", line 567, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\utils.py", line 550, in run_sync_iterator_async
    return next(iterator)
  File "D:\document\GPT-SoVITS-v3\runtime\lib\site-packages\gradio\utils.py", line 733, in gen_wrapper
    response = next(iterator)
  File "D:\document\GPT-SoVITS-v3\GPT_SoVITS\inference_webui.py", line 533, in get_tts_wav
    if (prompt_text[-1] not in splits): prompt_text += "。" if prompt_language != "en" else "."
IndexError: string index out of range

不管輸入啥文本都報錯，切分方式為不切，合成語言為日語
