### ISSUE TITLE
aliyun-python-sdk-core installation error: ModuleNotFoundError: No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by HaTiWinter** [RVC-Boss/GPT-SoVITS#1284]
# Problem

When I use `pip install -r requirements.txt` to install `FunASR`, the console reports `ModuleNotFoundError: No module named 'aliyunsdkcore'`:
```bash
Using cached https://mirrors.aliyun.com/pypi/packages/3a/e6/f579e8a5e26ef1066f6fb11074cedc9f668cb5f722c85cf7adc0f7e2e23e/aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HaTiWinter\AppData\Local\Temp\pip-install-50xcps92\aliyun-python-sdk-core_1b25988db72545b39644c8eae4310a08\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Environment

* Windows 10 21H2 64bit
* Python 3.10.13 embeddable

# Discussion

After testing, I found that using the Python embeddable version results in incorrect installation of `aliyun-python-sdk-core 2.15.1`, and tests show Python embeddable works only with `aliyun-python-sdk-core 2.13.10` or lower.

# Solution

```bash
pip install aliyun-python-sdk-core==2.13.10
pip install -U FunASR
```

**Comment by Separatee** [comment]
Also, why dont you try this All-In-One packages? it was mentioned in the README.md

https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-beta-fast-inference-branch.7z?download=true
