### ISSUE TITLE
开启TTS推理WebUI时出错：ModuleNotFoundError: No module named 'wordsegment'

### ISSUE THREAD

**Issue by marco-qu** [RVC-Boss/GPT-SoVITS#1310]
Traceback (most recent call last):
  File "D:\work\ai\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\inference_webui.py", line 65, in <module>
    from text.cleaner import clean_text
  File "D:\work\ai\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "D:\work\ai\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'

实际上，在这个环境下，已经安装了这个模块，重新安装，提示已经存在：
(GPTSoVits) PS D:\work\ai\GPT-SoVITS-beta\GPT-SoVITS> pip install wordsegment
Requirement already satisfied: wordsegment in c:\ai\anaconda3\envs\gptsovits\lib\site-packages (1.3.1)

如果用整合包，则能正常打开，但用github上的代码，则出错。

**Comment by SapphireLab** [comment]
结合之前的问题，如 [924](https://github.com/RVC-Boss/GPT-SoVITS/issues/924#issuecomment-2040955150)，看到你使用的是 PS Powershell，可以换成命令行 CMD 再尝试一下。
它们之间会有一点区别。

**Comment by RVC-Boss** [comment]
一般都是pip命令没指定对具体执行到的那个python

**Comment by marco-qu** [comment]
确实如上面所说，同#924问题。谢谢
