### ISSUE TITLE
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 

### ISSUE THREAD

**Issue by selfboot** [RVC-Boss/GPT-SoVITS#132]
cuda 从 11.0 升级到了 11.7 ，然后就报这个错误了。看了下 NCCL 的问题，没发现有有效解决方法。

```
python webui.py
Running on local URL:  http://0.0.0.0:9874
"/data/home/miniconda3/envs/GPTSoVits11/bin/python" GPT_SoVITS/s2_train.py --config "TEMP/tmp_s2.json"
phoneme_data_len: 143
wav_data_len: 143
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 143/143 [00:00<00:00, 95023.05it/s]
skipped_phone:  0 , skipped_dur:  0
total left:  143
/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
ssl_proj.weight not requires_grad
ssl_proj.bias not requires_grad
Traceback (most recent call last):
  File "/data/home/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 566, in <module>
    main()
  File "/data/home/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 53, in main
    mp.spawn(
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/data/home/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 177, in run
    net_g = DDP(net_g, device_ids=[rank], find_unused_parameters=True)
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/data/home/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1699449181081/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.6
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
nvmlDeviceGetP2PStatus(0,0,NVML_P2P_CAPS_INDEX_READ) failed: Invalid Argument
```

目前 cuda 版本
```
nvidia-smi 
Mon Jan 22 11:30:05 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:09.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB /  7680MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

驱动版本：

```
nvcc -V 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

torch 版本：

```
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> print(torch.__version__)
2.1.1
```

**Comment by RVC-Boss** [comment]
2.1.1+cuda11没测过呢

**Comment by RVC-Boss** [comment]
也许需要升级cuda到12或者降级pytorch到2.0.x？

**Comment by selfboot** [comment]
> 也许需要升级cuda到12或者降级pytorch到2.0.x？

感谢～ 我降级下 pytorch ，gpu 目前不支持升级 cuda12

**Comment by selfboot** [comment]
降级后可以了：

```shell
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
```

Ref: https://pytorch.org/get-started/previous-versions/

**Comment by RVC-Boss** [comment]
ok
