### ISSUE TITLE
启动时报错 max_split_size_mb=0

### ISSUE THREAD

**Issue by mrli834668690** [RVC-Boss/GPT-SoVITS#1348]
整合包
 ```
D:\soft\GPT-SoVITS-beta0706> python webui.py
Traceback (most recent call last):
  File "D:\soft\GPT-SoVITS-beta0706\webui.py", line 51, in <module>
    from config import python_exec,infer_device,is_half,exp_root,webui_port_main,webui_port_infer_tts,webui_port_uvr5,webui_port_subfix,is_share
  File "D:\soft\GPT-SoVITS-beta0706\config.py", line 33, in <module>
    gpu_name = torch.cuda.get_device_name(0)
  File "D:\soft\anaconda3\envs\GPTSoVits\lib\site-packages\torch\cuda\__init__.py", line 435, in get_device_name
    return get_device_properties(device).name
  File "D:\soft\anaconda3\envs\GPTSoVits\lib\site-packages\torch\cuda\__init__.py", line 465, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "D:\soft\anaconda3\envs\GPTSoVits\lib\site-packages\torch\cuda\__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=0
```

**Comment by SapphireLab** [comment]
告知一下使用的设备信息？

**Comment by mrli834668690** [comment]
> 告知一下使用的设备信息？

显卡是1640,4g显存，win10，显存可能不太够，但是我用conda的形式是可以正常启动的只不过一间三连遇到了另一个问题，但是整合包启动就报这个错不知道为啥

**Comment by mrli834668690** [comment]
conda启动的问题解决了，删除C:\Users\AppData\Roaming\nltk_data文件夹然后重新启动后会重新生成

**Comment by RVC-Boss** [comment]
1650的话推理和训练都用不成

**Comment by mrli834668690** [comment]
> 1650的话推理和训练都用不成

推理可以
