### ISSUE TITLE
unbantu上运行api.py

### ISSUE THREAD

**Issue by hjj-lmx** [RVC-Boss/GPT-SoVITS#1367]
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Traceback (most recent call last):
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict.zip/cmudict/

  Searched in:
    - '/root/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/share/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/UD/GPT-SoVITS/api.py", line 166, in <module>
    from text.cleaner import clean_text
  File "/usr/local/UD/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/usr/local/UD/GPT-SoVITS/GPT_SoVITS/text/english.py", line 358, in <module>
    _g2p = en_G2p()
  File "/usr/local/UD/GPT-SoVITS/GPT_SoVITS/text/english.py", line 252, in __init__
    super().__init__()
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/g2p_en/g2p.py", line 71, in __init__
    self.cmu = cmudict.dict()
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/vipuser/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict

  Searched in:
    - '/root/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/share/nltk_data'
    - '/home/vipuser/anaconda3/envs/GPTSoVits/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

**Comment by XXXXRT666** [comment]
缺少nltk,按照报错提示下载

**Comment by Yitianw** [comment]
可以在windows电脑上下载
`import nltk
nltk.download('cmudict’)`
![Image](https://github.com/user-attachments/assets/edbee6fd-5bab-458e-bdd4-37c23f9645f0)
然后把下载的文件copy到unbantu这里任意一个路径下
![image](https://github.com/user-attachments/assets/2405c25d-4d60-4bc6-bc41-a57cd18f9c87)
