### ISSUE TITLE
mac 一键三连报错 m2max 芯片

### ISSUE THREAD

**Issue by PengJiang520** [RVC-Boss/GPT-SoVITS#1378]
IMPORTANT: You are using gradio version 3.38.0, however version 4.29.0 is available, please upgrade.
--------
"/opt/miniconda3/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/opt/miniconda3/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/mrjp/Documents/凯凯你好/GPT-SoVITS-Kaikai-Renovate/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
  File "/Users/mrjp/Documents/凯凯你好/GPT-SoVITS-Kaikai-Renovate/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/Users/mrjp/Documents/凯凯你好/GPT-SoVITS-Kaikai-Renovate/GPT-SoVITS/GPT_SoVITS/text/english.py", line 5, in <module>
    from g2p_en import G2p
  File "/opt/miniconda3/lib/python3.9/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/opt/miniconda3/lib/python3.9/site-packages/g2p_en/g2p.py", line 22, in <module>

**Comment by XXXXRT666** [comment]
不确定是否是仓库代码,建议你去找那个人
