### ISSUE TITLE
在打标时出现了运行错误

### ISSUE THREAD

**Issue by xlinbo** [RVC-Boss/GPT-SoVITS#1381]
Running on local URL:  http://0.0.0.0:9874
"D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\runtime\python.exe" tools/subfix_webui.py --load_list "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\output\asr_opt" --webui_port 9871 --is_share False
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
PermissionError: [Errno 13] Permission denied: 'D:\\GPT-SoVITS-beta\\GPT-SoVITS-beta0706\\output\\asr_opt'
大概是权限问题吗

**Comment by SapphireLab** [comment]
[问题与报错合集 3.2](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt#N136W)

**Comment by RVC-Boss** [comment]
填写.list文件路径而非文件夹

**Comment by Sucgz** [comment]
填写文件路径而不是文件夹路径，感谢大佬
