### ISSUE TITLE
训练SoVITS时报错

### ISSUE THREAD

**Issue by 1507045** [RVC-Boss/GPT-SoVITS#1382]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\GPT-SoVITS-beta0706\GPT_SoVITS\s2_train.py", line 85, in run
    train_dataset = TextAudioSpeakerLoader(hps.data)  ########
  File "E:\GPT-SoVITS-beta0706\GPT_SoVITS\module\data_utils.py", line 35, in __init__
    assert os.path.exists(self.path2)
AssertionError

**Comment by wingerboy** [comment]
+1

**Comment by Lin-Silver** [comment]
You can try checking your file path. If the file exists, you can try using the absolute path.
