### ISSUE TITLE
大佬们，训练gpt模型报错，是整合包

### ISSUE THREAD

**Issue by nb10yyds** [RVC-Boss/GPT-SoVITS#1389]
"C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "C:\Users\Li\Documents\GPT-SoVITS-beta0706\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [LAPTOP-02DP5PH0]:35980 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [LAPTOP-02DP5PH0]:35980 (system error: 10049 - 在其上下文中，该请求的地址无效。).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 21
phoneme_data_len: 21
                              item_name                                     semantic_audio
0   新录音 1.m4a_0000016960_0000667200.wav  214 248 699 797 8 451 126 119 932 148 590 74 9...
1   新录音 1.m4a_0000793600_0001492800.wav  208 991 991 1005 98 784 462 307 462 183 565 20...
2   新录音 1.m4a_0001857920_0002571840.wav  722 766 608 826 251 453 710 950 800 378 881 64...
3   新录音 2.m4a_0000236800_0000612480.wav  1005 16 76 406 477 916 661 915 842 480 233 101...
4   新录音 2.m4a_0000778880_0002211840.wav  872 810 634 902 738 16 631 692 119 635 760 163...
5   新录音 2.m4a_0002640640_0002927680.wav  530 856 563 826 395 665 275 962 413 45 6 970 8...
6   新录音 2.m4a_0003517760_0003839360.wav  277 635 929 198 470 868 614 392 415 302 961 40...
7   新录音 2.m4a_0004089600_0004520320.wav  1005 256 496 203 311 272 327 942 942 640 175 2...
8   新录音 4.m4a_0000432960_0000588160.wav  1012 371 128 856 45 567 725 954 212 532 914 48...
9   新录音 4.m4a_0001109440_0001381120.wav  432 904 483 137 963 888 6 770 763 767 881 331 ...
10  新录音 4.m4a_0001490560_0001749760.wav  171 112 988 972 697 232 37 860 381 614 713 608...
11  新录音 1.m4a_0000667200_0000793600.wav  54 411 758 451 14 208 162 224 1018 126 969 788...
12  新录音 1.m4a_0001492800_0001857920.wav  913 360 341 909 909 258 360 950 624 624 659 80...
13  新录音 2.m4a_0000004480_0000236800.wav  913 13 623 496 722 562 382 382 8 134 565 965 3...
14  新录音 2.m4a_0000626240_0000778880.wav  913 721 23 673 570 59 831 644 845 603 39 806 4...
15  新录音 2.m4a_0002211840_0002640640.wav  277 635 846 994 566 685 121 289 730 920 601 55...
16  新录音 2.m4a_0002927680_0003517760.wav  714 73 820 820 286 652 947 942 549 984 655 402...
17  新录音 2.m4a_0003839360_0004089600.wav  722 798 626 667 414 1001 318 609 274 884 398 7...
18  新录音 4.m4a_0000000000_0000432960.wav  941 512 632 861 589 846 983 198 329 613 613 26...
19  新录音 4.m4a_0000588160_0001109440.wav  431 493 62 904 120 377 666 705 454 761 62 636 ...
20  新录音 4.m4a_0001381120_0001490560.wav  913 1018 704 714 848 707 673 360 269 735 893 6...
dataset.__len__(): 84
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                 | Params
-----------------------------------------------
0 | model | Text2SemanticDecoder | 77.5 M
-----------------------------------------------
77.5 M    Trainable params
0         Non-trainable params
77.5 M    Total params
309.975   Total estimated model params size (MB)
C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\fit_loop.py:293: The number of training batches (28) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:  18%|██████▉                                | 5/28 [00:02<00:12,  1.91it/s, v_num=1, total_loss_step=3.67e+3, lr_step=0.010, top_3_acc_step=0.183]Traceback (most recent call last):
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 989, in _run
    results = self._run_stage()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 202, in run
    self.advance()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 242, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\optimization\manual.py", line 92, in run
    self.advance(kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\loops\optimization\manual.py", line 112, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 381, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 633, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 626, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 39, in training_step
    loss, acc = forward(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\models\t2s_model.py", line 403, in forward_old
    xy_dec, _ = self.h(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\modules\transformer.py", line 170, in forward
    output = mod(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\modules\transformer.py", line 311, in forward
    x + self._sa_block(x, src_mask, src_key_padding_mask, cache=cache),
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\modules\transformer.py", line 332, in _sa_block
    x = self.self_attn(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\modules\activation.py", line 404, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\AR\modules\patched_mha_with_cache.py", line 452, in multi_head_attention_forward_patched
    attn_output = scaled_dot_product_attention(
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\s1_train.py", line 182, in <module>
    main(args)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\GPT_SoVITS\s1_train.py", line 158, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 68, in _call_and_handle_interrupt
    trainer._teardown()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1012, in _teardown
    self.strategy.teardown()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 406, in teardown
    super().teardown()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\parallel.py", line 127, in teardown
    super().teardown()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 528, in teardown
    self.lightning_module.cpu()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 79, in cpu
    return super().cpu()
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 954, in cpu
    return self._apply(lambda t: t.cpu())
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Li\Documents\GPT-SoVITS-beta0706\runtime\lib\site-packages\torch\nn\modules\module.py", line 954, in <lambda>
    return self._apply(lambda t: t.cpu())
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by bfloat16** [comment]
炸显存，尝试调小batch size，切短音频或者更换显卡

**Comment by RVC-Boss** [comment]
楼上正解
