### ISSUE TITLE
使用modelscope==1.10.0遇到错误

### ISSUE THREAD

**Issue by dvdcjw** [RVC-Boss/GPT-SoVITS#1393]
在如req.txt安装modelscope==1.10.0出现以下错误（日志中音频路径已后期改为默认路径方便看懂）

"E:\*****\GPT-SoVITS\.venv\Scripts\python.exe" tools/asr/funasr_asr.py -i "D:\GPT-SoVITS\raw\xxx" -o "output\asr_opt" -s large -l zh -p float32
2024-08-05 06:59:39,017 - modelscope - INFO - PyTorch version 2.2.2+cu118 Found.
2024-08-05 06:59:39,020 - modelscope - INFO - Loading ast index from C:\Users\DVDCJW\.cache\modelscope\ast_indexer
2024-08-05 06:59:39,114 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2024-08-05 06:59:39,124 - modelscope - INFO - AST-Scanning the path "E:\*****\GPT-SoVITS\.venv\Lib\site-packages\modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
Download: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch failed!: During ast indexing the file E:\*****\GPT-SoVITS\.venv\Lib\site-packages\modelscope\models\audio\aec\layers\activations.py, a related error excepted in the file E:\*****\GPT-SoVITS\.venv\lib\site-packages\modelscope\utils\ast_utils.py at line: 151: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file E:\*****\GPT-SoVITS\.venv\Lib\site-packages\modelscope\models\audio\aec\layers\activations.py to see whether the file is correctly edited.       
Traceback (most recent call last):
  File "E:\*****\GPT-SoVITS\tools\asr\funasr_asr.py", line 76, in <module>
    model = AutoModel(
  File "E:\*****\GPT-SoVITS\.venv\lib\site-packages\funasr\auto\auto_model.py", line 117, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "E:\*****\GPT-SoVITS\.venv\lib\site-packages\funasr\auto\auto_model.py", line 213, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
Keyboard interruption in main thread... closing server.

更新到modelscope1.14.0就没有出现过问题
python3.9.13，Windows11

**Comment by dvdcjw** [comment]
我的*被markdown识别了，不过不影响阅读
