### ISSUE TITLE
请问一下这个问题要怎么解决 ，我用的是 M1 的芯片

### ISSUE THREAD

**Issue by luohui1102** [RVC-Boss/GPT-SoVITS#1413]
"/Users/llh/Desktop/AI/GPT-SoVITS/runtime/bin/python3" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"/Users/llh/Desktop/AI/GPT-SoVITS/runtime/bin/python3" GPT_SoVITS/prepare_datasets/3-get-semantic.py
/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/Users/llh/Desktop/AI/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 67, in <module>
    vq_model.load_state_dict(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([322, 192]) from checkpoint, the shape in current model is torch.Size([732, 192]).
	size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 1025]) from checkpoint, the shape in current model is torch.Size([128, 704]).
Traceback (most recent call last):
  File "/Users/llh/Desktop/AI/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 67, in <module>
    vq_model.load_state_dict(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([322, 192]) from checkpoint, the shape in current model is torch.Size([732, 192]).
	size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 1025]) from checkpoint, the shape in current model is torch.Size([128, 704]).
Traceback (most recent call last):
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/llh/Desktop/AI/GPT-SoVITS/webui.py", line 586, in open1c
    with open(semantic_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/6-name2semantic-0.tsv'

**Comment by XXXXRT666** [comment]
点击command拉取一下

**Comment by luohui1102** [comment]
Thank you very much, it has been resolved.

**Comment by luohui1102** [comment]
我把update.command，go-api.command都点了，没有解决我的问题
ffmpeg 已安装.

![WeChat2711da9bbeddbff58202b3886d27ad6d](https://github.com/user-attachments/assets/3a587db9-fff8-4260-92e0-6b8ecee61617)


/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  未指定SoVITS模型路径, fallback后当前值: GPT_SoVITS/pretrained_models/s2G488k.pth
/Users/llh/Desktop/AI/GPT-SoVITS/api.py:715: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(f"未指定GPT模型路径, fallback后当前值: {gpt_path}")
WARNING:  未指定GPT模型路径, fallback后当前值: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
INFO:     未指定默认参考音频
INFO:     半精: False
INFO:     编码格式: wav
sovits版本: v1
/Users/llh/Desktop/AI/GPT-SoVITS/runtime/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
INFO:     Number of parameter: 77.49M
DEBUG:asyncio:Using selector: KqueueSelector
INFO:     Started server process [5440]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9880 (Press CTRL+C to quit)

**Comment by XXXXRT666** [comment]
那就等下一个一键包，应该在今晚

**Comment by luohui1102** [comment]
好的 ，请问一下在哪里下载啊

**Comment by XXXXRT666** [comment]
老地方

**Comment by recombiOOO** [comment]
![image](https://github.com/user-attachments/assets/e9f4693c-58b2-4455-ac86-360f5fff4242)
一样。。用的一键包

**Comment by XXXXRT666** [comment]
没指定路径那就指定,有端点可以指定模型

**Comment by Suzutsuki-CH** [comment]
同问这个缺tsv文件的错误该怎么解决，用的是m2的设备

**Comment by XXXXRT666** [comment]
完整traceback呢

**Comment by Suzutsuki-CH** [comment]
> 完整traceback呢

找到问题了，最开始训练的时候默认用的v2，然后1Ac那里的pretrained model path 没有添加；我后来点了一下v1，发现它自动把path填上了，再换回v2就好了。
