### ISSUE TITLE
Failed to import the site module

### ISSUE THREAD

**Issue by wakaztahir** [RVC-Boss/GPT-SoVITS#142]
I downloaded the zip and ran the go-webui.bat

Here's what came up in the terminal

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "site.py", line 589, in <module>
  File "site.py", line 576, in main
  File "site.py", line 359, in addsitepackages
  File "site.py", line 208, in addsitedir
  File "site.py", line 164, in addpackage
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 3: invalid start byte
```

I use AMD btw

**Comment by RVC-Boss** [comment]
Update the latest codes, replace it, and have a try again?
I don't know it it fixed now.
