### ISSUE TITLE
[Windows package] api.py - FFmpeg libraries are not found + Invalid HTTP request received

### ISSUE THREAD

**Issue by hopto-dot** [RVC-Boss/GPT-SoVITS#1424]
I have downloaded the Windows `GPT-SoVITS-v2-240807.7z` package from [lj1995/GPT-SoVITS-windows-package](https://huggingface.co/lj1995/GPT-SoVITS-windows-package/tree/main).

Everything in go-webui.bat works fine for me, however I want to use api.py.

So I run the following command (truncated for brevity):
```cmd
"runtime\python.exe" api.py -dr "...\010811-0.wav" -dt "..." -dl "ja" -s "...\sovits_model_name.pth"  -g "...\gpt_model_name.ckpt"
```

Then I get the following output mentioning `ffmpeg` but still running the server:
```cmd
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
INFO:     默认参考音频路径: ...\010811-0.wav
INFO:     默认参考音频文本: ...
INFO:     默认参考音频语种: ja
INFO:     半精: True
INFO:     编码格式: wav
sovits版本: v2
INFO:     Number of parameter: 77.61M
DEBUG:root:Using proactor: IocpProactor
INFO:     Started server process [24936]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9880 (Press CTRL+C to quit)
WARNING:  Invalid HTTP request received.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [24936]
```

When I send a curl request like the following:
```cmd
curl "http://127.0.0.1:9880?text=こんにちは！&text_language=ja"
```

the server responds back with:
```
Invalid HTTP request received.
```

I know that I have ffmpeg installed and in my system PATH. I can type `ffmpeg`:
```cmd
C:\Users\username>ffmpeg
ffmpeg version 2024-01-01-git-e1c1dc8347-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
 ...
```

Is this a bug, or is there a simple fix for this?

**Comment by KamioRinn** [comment]
Try unzip again？

**Comment by HsiangLeekwok** [comment]
看看ffmpeg是否安装正常？
```shell
runtime\python.exe -m pip list | findstr("ffmpeg")
```
如果没有的话，安装一下
```shell
runtime\python.exe -m pip install ffmpeg-python
```

**Comment by hopto-dot** [comment]
@HsiangLeekwok It tells me that ffmpeg-python is already is installed.

```cmd
GPT-SoVITS-v2-240807>runtime\python.exe -m pip list | findstr("ffmpeg")

GPT-SoVITS-v2-240807>runtime\python.exe -m pip install ffmpeg-python
Requirement already satisfied: ffmpeg-python in c:\users\username\documents\git\gpt-sovits-v2-240807\runtime\lib\site-packages (0.2.0)
Requirement already satisfied: future in c:\users\username\documents\git\gpt-sovits-v2-240807\runtime\lib\site-packages\future-0.18.2-py3.9.egg (from ffmpeg-python) (0.18.2)
```

That said, I don't understand how it can be installed if `pip list | findstr("ffmpeg")` returns nothing.

**Comment by KamioRinn** [comment]
wrong default_refer_path(-dr)

**Comment by KamioRinn** [comment]
> @KamioRinn I specified the path of a wav file just like the [example](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/api.py#L4) command in api.py. I don't think that's what's causing the issue.

show log

**Comment by hopto-dot** [comment]
@KamioRinn This is the command I ran.
```cmd
runtime\python.exe api.py -dr "C:\Users\username\Documents\Git\sbv2\Style-Bert-VITS2\Data\Mahiru-2\raw\1_31_(Vocals)-0.wav" -dt "寮に寄っては、先に地獄を見て残りは天国ですから。" -dl "ja" -s "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\SoVITS_weights_v2\Mahiru-2_e9_s279.pth" -g "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\GPT_weights_v2\Mahiru-2-e16.ckpt"
```

And the output I got in the console.
```cmd
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "C:\Users\username\Documents\Git\GPT-SoVITS-v2-240807\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
INFO:     默认参考音频路径: C:\Users\username\Documents\Git\sbv2\Style-Bert-VITS2\Data\Mahiru-2\raw\1_31_(Vocals)-0.wav
INFO:     默认参考音频文本: 寮に寄っては、先に地獄を見て残りは天国ですから。
INFO:     默认参考音频语种: ja
INFO:     半精: True
INFO:     编码格式: wav
sovits版本: v2
INFO:     Number of parameter: 77.61M
DEBUG:root:Using proactor: IocpProactor
INFO:     Started server process [9156]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9880 (Press CTRL+C to quit)
```

---

Then I run this Curl command:
```cmd
curl "http://127.0.0.1:9880?refer_wav_path=C:\Users\username\Documents\Git\sbv2\Style-Bert-VITS2\Data\Mahiru-2\raw\1_31_(Vocals)-0.wav&prompt_text=寮に寄っては、先に地獄を見て残りは天国ですから。&prompt_language=ja&text=これはテストです&text_language=ja&top_k=20&top_p=0.6&temperature=0.6&speed=1"
```

I get this response output in api.py:
```cmd
WARNING:  Invalid HTTP request received.
```

There is no other output to the console.

**Comment by KamioRinn** [comment]
use  urlEncode
```
curl  "http://127.0.0.1:9880/?refer_wav_path=C:\Users\username\Documents\Git\sbv2\Style-Bert-VITS2\Data\Mahiru-2\raw\1_31_(Vocals)-0.wav&prompt_text=%E5%AF%AE%E3%81%AB%E5%AF%84%E3%81%A3%E3%81%A6%E3%81%AF%E3%80%81%E5%85%88%E3%81%AB%E5%9C%B0%E7%8D%84%E3%82%92%E8%A6%8B%E3%81%A6%E6%AE%8B%E3%82%8A%E3%81%AF%E5%A4%A9%E5%9B%BD%E3%81%A7%E3%81%99%E3%81%8B%E3%82%89%E3%80%82&prompt_language=ja&text=%E3%81%93%E3%82%8C%E3%81%AF%E3%83%86%E3%82%B9%E3%83%88%E3%81%A7%E3%81%99&text_language=ja&top_k=20&top_p=0.6&temperature=0.6&speed=1"
```

**Comment by hopto-dot** [comment]
@KamioRinn That fixed the issue, thank you!

@RVC-Boss could api.py maybe print out an appropriate error when the user doesn't pass arguments in url encoding otherwise you get idiots like me who doesn't understand why when it doesn't work lol
