### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by brokestar233** [RVC-Boss/GPT-SoVITS#1427]
建议这里往终端输出错误信息，下面的错误排查了好久，最后才发现是这里没有权限导致没有正常写入
```
"/usr/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/usr/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/mnt/d/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 20, in <module>
    from text.cleaner import clean_text
ModuleNotFoundError: No module named 'text'
Traceback (most recent call last):
  File "/mnt/d/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 20, in <module>
    from text.cleaner import clean_text
ModuleNotFoundError: No module named 'text'
Traceback (most recent call last):
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/brokestar/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/brokestar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/brokestar/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/brokestar/.local/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/mnt/d/GPT-SoVITS/webui.py", line 472, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/fish/2-name2text-0.txt'
```
![image](https://github.com/user-attachments/assets/a503c2fd-83a5-4692-81c5-e1d02386d81d)

**Comment by KamioRinn** [comment]
这个地方不能在wsl里拉win下的资源，到了后面的步骤还会报错

**Comment by brokestar233** [comment]
> 这个地方不能在wsl里拉win下的资源，到了后面的步骤还会报错

主要原因其实是我没有用虚拟环境,然后这里要写的三个目录全部要root权限才可以写
![image](https://github.com/user-attachments/assets/b5c18688-84f9-42ae-8614-c7d083e8cf9b)

至于后面的步骤报错，目前没有遇到
![image](https://github.com/user-attachments/assets/b1f11a17-b51f-488d-a34d-0c0415ecde8d)

**Comment by RVC-Boss** [comment]
下次我改成traceback吧
