### ISSUE TITLE
6-name2semantic-0.tsv 报错

### ISSUE THREAD

**Issue by wrl1224** [RVC-Boss/GPT-SoVITS#1439]
从main分支拉区最新代码后执行1Ac-语义token提取
遇到以下报错
"/home/heike/anaconda3/envs/GPTSoVits20240808/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"/home/heike/anaconda3/envs/GPTSoVits20240808/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
  File "/home/heike/hkdata/Code/wrl/w20240809/GPT-SoVITS-main/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 38
    Felse:raise FileNotFoundError(pretrained_s2G)
          ^
SyntaxError: invalid syntax
  File "/home/heike/hkdata/Code/wrl/w20240809/GPT-SoVITS-main/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 38
    Felse:raise FileNotFoundError(pretrained_s2G)
          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/heike/anaconda3/envs/GPTSoVits20240808/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/heike/hkdata/Code/wrl/w20240809/GPT-SoVITS-main/webui.py", line 583, in open1c
    with open(semantic_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/serverYaoYao/6-name2semantic-0.tsv'

**Comment by SapphireLab** [comment]
前面不是写了 `FileNotFoundError(pretrained_s2G)` 么，找不到模型权重，所以需要另外下载一下预训练权重。

**Comment by bigbigtooth** [comment]
> 前面不是写了 `FileNotFoundError(pretrained_s2G)` 么，找不到模型权重，所以需要另外下载一下预训练权重。

请教一下，怎么解决呢？去哪里下？

**Comment by SapphireLab** [comment]
> 请教一下，怎么解决呢？去哪里下？目前我的模型都是最新下载的

- 如果是说底模的话，可以到 HuggingFace 下：[HF-Mirror 镜像](https://hf-mirror.com/lj1995/GPT-SoVITS/tree/main)，
v2 就是 `gsv-v2final-pretrained` 文件夹，下好放在项目内的 `/GPT_SoVITS/pretrained_models` 下。
注意文件结构和 HuggingFace 上的相同，如图
![image](https://github.com/user-attachments/assets/4b4562f0-9351-44be-b3d3-98735f5ba775)

- 如果不会的话直接下载整合包就好。

更详细的可以查看 [整合包及模型下载链接](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/dkxgpiy9zb96hob4)

**Comment by RVC-Boss** [comment]
楼上正解，模型没下全
