### ISSUE TITLE
Slicer 分割可以传参最大分割长度嘛？

### ISSUE THREAD

**Issue by yuys0602** [RVC-Boss/GPT-SoVITS#1447]
更新了新版后，看了下分割函数没变，但是分出来的分割段落特别长，导致bert的输入超长了（但没有截断），报了如下错误：

```
xxx.wav XXXXXX(超长的一段文字，约有800个字）。 
Traceback (most recent call last):
  File "/speech_v4/GPT_SoVITS/prepare_datasets/1-get-text.py", line 94, in process
    bert_feature = get_bert_feature(norm_text, word2ph)
  File "/speech_v4/GPT_SoVITS/prepare_datasets/1-get-text.py", line 71, in get_bert_feature
    res = bert_model(**inputs, output_hidden_states=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1491, in forward
    outputs = self.bert(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1077, in forward
    embedding_output = self.embeddings(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 216, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (800) must match the size of tensor b (512) at non-singleton dimension 1
```

检查了下，看到slice的音频都很长，请问可以在Slicer里传参修正下，至少保证不会超过比如20s一句？（因为看到了有个短与4秒合并的逻辑）

**Comment by HsiangLeekwok** [comment]
检查一下wav原声中这一段长音频是否有背景音或者其他诸如吸气等环境因素导致无法识别正确的停顿。
如果可行的话，用Audacity之类的软件查看一下声音波形，或者直接用Audacity处理(清除)一下低频噪音，把停顿空白留出来，然后再slice就可以了。

**Comment by RVC-Boss** [comment]
这个逻辑一直没变，过长的（如果确实就是没有切口）如果切到中间作为训练集的话感觉对合成效果不太好吧，建议写过滤逻辑
如果有切口的话就是调整阈值

**Comment by yuys0602** [comment]
> 这个逻辑一直没变，过长的（如果确实就是没有切口）如果切到中间作为训练集的话感觉对合成效果不太好吧，建议写过滤逻辑 如果有切口的话就是调整阈值

像我遇到的这种且不开的情况，传入bert时就会导致超出512token长度报错的问题，还是蛮烦人的。

想请问下是否可以强行控制切后的长度，比如不长于20s（一句话超过20s也不太正常吧），这样至少保证代码的鲁棒性

**Comment by Crestina2001** [comment]
同问
