### ISSUE TITLE
most likely due to a circular import

### ISSUE THREAD

**Issue by cpken** [RVC-Boss/GPT-SoVITS#1476]
操作【0c-中文批量离线ASR工具】，出现以下错误，无法成功执行。用的是 cuda124，torchaudio==2.4.0

```
Traceback (most recent call last):
  File "GPT-SoVITS/tools/asr/funasr_asr.py", line 9, in <module>
    from funasr import AutoModel
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/funasr/__init__.py", line 39, in <module>
    from funasr.auto.auto_model import AutoModel
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 19, in <module>
    from funasr.utils.load_utils import load_bytes
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/funasr/utils/load_utils.py", line 8, in <module>
    import torchaudio
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 42, in <module>
    _check_cuda_version()
  File "conda_env/GPT-SoVITS/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 168, in _check_cuda_version
    version = torchaudio.lib._torchaudio.cuda_version()
AttributeError: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
```

**Comment by cpken** [comment]
通过删除 在 def _check_cuda_version() 里 删除 import torchaudio.lib._torchaudio，然后在文件顶部加入 import torchaudio 解决问题。

conda_env/GPT-SoVITS/lib/python3.10/site-packages/torchaudio/_extension/utils.p

```python
import torch
import torchaudio

def _check_cuda_version():
    # import torchaudio.lib._torchaudio
```
