### ISSUE TITLE
`Fast_infercence_` 分支报错。

### ISSUE THREAD

**Issue by WhaleFell** [RVC-Boss/GPT-SoVITS#1486]
load tts config from configs/纳雅.yaml
Loading Text2Semantic weights from GPT_weights/Laya_Final-e15.ckpt
Loading VITS weights from SoVITS_weights/Laya_Final_e8_s72.pth
Loading BERT weights from GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
Loading CNHuBERT weights from GPT_SoVITS/pretrained_models/chinese-hubert-base
base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base <class 'str'>
Traceback (most recent call last):
  File "E:\AI-Voice\GPT-SoVITS-8dd7cfab931c8c98ac8ab33a213e309c7c2f737c\api_v3.py", line 362, in tts_handle
    tts_instance = get_tts_instance(tts_config)
  File "E:\AI-Voice\GPT-SoVITS-8dd7cfab931c8c98ac8ab33a213e309c7c2f737c\api_v3.py", line 174, in get_tts_instance
    return TTS(tts_config)
  File "E:\AI-Voice\GPT-SoVITS-8dd7cfab931c8c98ac8ab33a213e309c7c2f737c\GPT_SoVITS\TTS_infer_pack\TTS.py", line 216, in __init__
    self._init_models()
  File "E:\AI-Voice\GPT-SoVITS-8dd7cfab931c8c98ac8ab33a213e309c7c2f737c\GPT_SoVITS\TTS_infer_pack\TTS.py", line 244, in _init_models
    self.init_cnhuhbert_weights(self.configs.cnhuhbert_base_path)
  File "E:\AI-Voice\GPT-SoVITS-8dd7cfab931c8c98ac8ab33a213e309c7c2f737c\GPT_SoVITS\TTS_infer_pack\TTS.py", line 252, in init_cnhuhbert_weights
    self.cnhuhbert_model = CNHubert(base_path)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by ChasonJiang** [comment]
看起来没什么问题，检查一下runtime

**Comment by XXXXRT666** [comment]
不要把main分支和fast inference在同一环境下使用

**Comment by RVC-Boss** [comment]
试试最新的main分支呢，已经把该分支合并进去了

**Comment by clearlove-civ6** [comment]
同遇到问题，谢谢楼上的dalao
