### ISSUE TITLE
推理日语文本的时候出现错误

### ISSUE THREAD

**Issue by GaryCarsonStone** [RVC-Boss/GPT-SoVITS#1518]
```
实际输入的目标文本(每句): れてやってくるものだからね。
Traceback (most recent call last):
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\blocks.py", line 1267, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 574, in async_iteration
    return await iterator.__anext__()
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 567, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 550, in run_sync_iterator_async
    return next(iterator)
  File "E:\Program\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 733, in gen_wrapper
    response = next(iterator)
  File "E:\Program\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui.py", line 474, in get_tts_wav
    phones2,bert2,norm_text2=get_phones_and_bert(text, text_language, version)
  File "E:\Program\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui.py", line 326, in get_phones_and_bert
    phones, word2ph, norm_text = clean_text_inf(formattext, language, version)
  File "E:\Program\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui.py", line 275, in clean_text_inf
    phones, word2ph, norm_text = clean_text(text, language, version)
  File "E:\Program\GPT-SoVITS-v2-240821\GPT_SoVITS\text\cleaner.py", line 36, in clean_text
    language_module = __import__("text."+language_module_map[language],fromlist=[language_module_map[language]])
  File "E:\Program\GPT-SoVITS-v2-240821\GPT_SoVITS\text\japanese.py", line 21, in <module>
    pyopenjtalk.mecab_dict_index(USERDIC_CSV_PATH, USERDIC_BIN_PATH)
AttributeError: module 'pyopenjtalk' has no attribute 'mecab_dict_index'
```
但推理其它语言的时候没有出现问题，请问应该怎么解决……

**Comment by RVC-Boss** [comment]
这个因为你更新了代码但是没有更新环境
需要将pyopenjtalk升级至0.3.4版本
