### ISSUE TITLE
Fast_infercence_分支的api v3无法调用sovits的v2模型

### ISSUE THREAD

**Issue by clearlove-civ6** [RVC-Boss/GPT-SoVITS#1543]
{
  "message": "tts failed",
  "Exception": "Error(s) in loading state_dict for SynthesizerTrn:\n\tsize mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]).\n\tsize mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025])."
}

**Comment by clearlove-civ6** [comment]
Traceback (most recent call last):
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\starlette\routing.py", line 74, in app
    response = await f(request)
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
  File "C:\anaconda\envs\GPT-SoVITS-fast_inference_\lib\site-packages\fastapi\routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\python\GPT-SoVITS-fast_inference\api.py", line 186, in tts_get_endpoint
    return await tts_handle(req)
  File "D:\python\GPT-SoVITS-fast_inference\api.py", line 127, in tts_handle
    ptraceback.print_exc()  # 用于打印当前异常的回溯信息到标准错误流
NameError: name 'ptraceback' is not defined

**Comment by RVC-Boss** [comment]
v1v2模型结构不一样无法混用，fast_inference_分支已经不维护了，因为它合并进了main里，请用main里的api.py，同时适配v1v2结构，并且支持fast_inference
