### ISSUE TITLE
【求助】api_v2.py方式内容有英文报错以及内容过短直接变成参考音频内容

### ISSUE THREAD

**Issue by liutianye** [RVC-Boss/GPT-SoVITS#1548]
本地服务器部署，main分支下根据readme部署，通过api_v2起的服务，然后使用postman来调用。

Q1：text是“之前没有过吃药过敏或者吃东西过敏的情况，没有接触过放射性物质或有害物质。”的话可以正常生成，但是如果加上HPV或HCG等简写，就报错了，如下图。
![image](https://github.com/user-attachments/assets/4fa7f927-2d70-41d2-a986-e15352a4e085)

Q2：当text的内容比较短的时候，生成的音频会直接变成参考音频内的文本内容，如LLM回复的是：“我叫王欣。”，此时生成并不报错，但是播放出来的是参考文本内容。
![image](https://github.com/user-attachments/assets/386482b0-ce11-492c-ae7a-a4e37da5b16f)

请问这种情况正常吗？还是我哪里配置的不对，text_split_method是cut0还是cut5都没影响。
以下是postman的参数。
URL:http://192.168.100.175:9880/tts/
{
    "text": "我叫王欣。",
    "text_lang": "zh",
    "ref_audio_path": "/home/tellyes/ai_tools/lty_01.WAV",
    "prompt_text": "在辛苦和劳累过后，当假日来临时，美的事儿就是先懒懒的睡上一觉，养足精神。",
    "prompt_lang": "zh",
    "text_split_method": "cut0",
    "batch_size": 8,
    "media_type": "wav",
    "streaming_mode": false
}

**Comment by XXXXRT666** [comment]
英文不是zh,选择中英混合

**Comment by liutianye** [comment]
> 英文不是zh,选择中英混合

大佬，混合要怎么写？里面写"zh|en"这种吗？我在api哪里看注释里是，“参考音频语种, "中文","英文","日文","韩文","粤语,"zh","en","ja","ko","yue"`”

**Comment by tortoise-ben** [comment]
我也有遇到过，好像不太稳定，有时候会出现参考音频，不知道咋处理。

**Comment by XXXXRT666** [comment]
v1_languages:list = ["auto", "en", "zh", "ja",  "all_zh", "all_ja"]
    v2_languages:list = ["auto", "auto_yue", "en", "zh", "ja", "yue", "ko", "all_zh", "all_ja", "all_yue", "all_ko"]
    languages:list = v2_languages
    # "all_zh",#全部按中文识别
    # "en",#全部按英文识别#######不变
    # "all_ja",#全部按日文识别
    # "all_yue",#全部按中文识别
    # "all_ko",#全部按韩文识别
    # "zh",#按中英混合识别####不变
    # "ja",#按日英混合识别####不变
    # "yue",#按粤英混合识别####不变
    # "ko",#按韩英混合识别####不变
    # "auto",#多语种启动切分识别语种
    # "auto_yue",#多语种启动切分识别语种

**Comment by XXXXRT666** [comment]
Q1的请求参数呢

**Comment by KamioRinn** [comment]
用api.py测试下

**Comment by tortoise-ben** [comment]
参数是zh。嗯嗯，我后面试试api.py。

**Comment by tortoise-ben** [comment]
同样的也遇到漏字，或者字母不发音。比如说:某某小区2单元A座。A这个字母漏掉。这个有办法调优嘛，后面调了几次，我现在是把文字替换成：某某小区2单元，~A座。这样会好很多。

**Comment by liutianye** [comment]
> Q1的请求参数呢

没用v2那个版本，换成了api.py就可以了...

**Comment by YourGrandFa** [comment]
感觉用原始音频推理，偶尔就是会抽风：要么少了一句话，要么加了一些原音频的片段，要么罢工直接播放原音频。按理来说，接口应当，至少需要给我一些推理效果的反馈...

**Comment by clearlove-civ6** [comment]
目前看来切片会影响吞句和合成语音直接变成参考音频内容

**Comment by liutianye** [comment]
> 没用v2那个版本，换成了api.py就可以了...



> 用api.py测试下

api.py 没问题，“我叫王欣。”这四个字一个句号，在api.py下正常推理，在api_v2.py里就直接变成参考音频的内容了。

**Comment by liutianye** [comment]
> 感觉用原始音频推理，偶尔就是会抽风：要么少了一句话，要么加了一些原音频的片段，要么罢工直接播放原音频。按理来说，接口应当，至少需要给我一些推理效果的反馈...

好像合成的内容长度有关系，比参考音频长的内容没问题，短的几乎都翻车，v2的api里比参考音频短的推理好像大部分都变成了参考音频内容了，但是console里是正常推理的日志出来。

**Comment by KamioRinn** [comment]
> api.py 没问题，“我叫王欣。”这四个字一个句号，在api.py下正常推理，在api_v2.py里就直接变成参考音频的内容了。

是的，api.py的文字处理逻辑对短发音推理容易翻车做了预防。

**Comment by neuxys** [comment]
请问怎么避免 短文本 生成了参考音频的情况呢？在webui中不容易发生，api里出现概率很高

**Comment by Lwx1203** [comment]
遇到了类似情况，中文可以正常输出，英文加其他语种（非英文）也可以正常输出，但是内容是纯英文或包括英文就不行，选了en或zh都不可以，有没有大佬知道为什么

**Comment by XXXXRT666** [comment]
> 遇到了类似情况，中文可以正常输出，英文加其他语种（非英文）也可以正常输出，但是内容是纯英文或包括英文就不行，选了en或zh都不可以，有没有大佬知道为什么

日志

**Comment by Lwx1203** [comment]
Traceback (most recent call last):
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 1073, in read_chunked
    self._update_chunk_length()
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 1008, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/home/tj517/anaconda3/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj517/GPT-SoVITS/GPT-SoVITS/test.py", line 11, in <module>
    response = requests.post(url, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tj517/anaconda3/lib/python3.11/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
参数是这个data = {
    #需要转为语音的文本及文本类型
    "text": "hello",
    "text_language": "en"
}

**Comment by Lwx1203** [comment]
Traceback (most recent call last):
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff56aab1370>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9880): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff56aab1370>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj517/GPT-SoVITS/GPT-SoVITS/test.py", line 11, in <module>
    response = requests.post(url, json=data)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9880): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff56aab1370>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Lwx1203** [comment]
Traceback (most recent call last):
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/response.py", line 1057, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/response.py", line 1206, in read_chunked
    self._update_chunk_length()
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/urllib3/response.py", line 1136, in _update_chunk_length
    raise ProtocolError("Response ended prematurely") from None
urllib3.exceptions.ProtocolError: Response ended prematurely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj517/GPT-SoVITS/GPT-SoVITS/test.py", line 11, in <module>
    response = requests.post(url, json=data)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/tj517/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: Response ended prematurely参数是"text": "hello",
    "text_language": "en"

**Comment by XXXXRT666** [comment]
服务器问题,Response未传输完成

**Comment by Lwx1203** [comment]
但是为啥中文就没问题呢？搞不懂

**Comment by Lwx1203** [comment]
解决了，是NLTK的 averaged_perceptron_tagger_eng的问题

**Comment by teneous** [comment]
> 解决了，是NLTK的 averaged_perceptron_tagger_eng的问题

是做了替换还是什么呢，怎么解决的？

**Comment by JSTks24** [comment]
> 用api.py测试下

普通的api.py和api_v2有什么区别呢？api.py适用于现在这个v2版本的GPTsovits吗？

**Comment by Skye2099** [comment]
> > api.py 没问题，“我叫王欣。”这四个字一个句号，在api.py下正常推理，在api_v2.py里就直接变成参考音频的内容了。
> 
> 是的，api.py的文字处理逻辑对短发音推理容易翻车做了预防。

请问对于短字会变参考音频的情况怎么处理呢？我是增加数据量重新训练还是通过api就可以解决？我理解api_v2应该是api的改进版吧，如果api能解决，这个功能应该可以集成到api_2?

**Comment by teneous** [comment]
> > > api.py 没问题，“我叫王欣。”这四个字一个句号，在api.py下正常推理，在api_v2.py里就直接变成参考音频的内容了。
> > 
> > 
> > 是的，api.py的文字处理逻辑对短发音推理容易翻车做了预防。
> 
> 请问对于短字会变参考音频的情况怎么处理呢？我是增加数据量重新训练还是通过api就可以解决？我理解api_v2应该是api的改进版吧，如果api能解决，这个功能应该可以集成到api_2?

我当前的做法就是更换参考拼音，并且seed设置为随机

**Comment by sunyq1995** [comment]
V2 我这里还出现了文本多次重复读的问题，以及漏字>..

**Comment by lucasmen9527** [comment]
我也遇到了 而且webui用混合中英文的 会报错 

<img width="1027" alt="Image" src="https://github.com/user-attachments/assets/9475bd27-fc95-4198-a258-73d6169e5f2d" />
但是我用纯中文的 就没问题

**Comment by lucasmen9527** [comment]
我找到解决的issue了 https://github.com/RVC-Boss/GPT-SoVITS/issues/1530 Resource averaged_perceptron_tagger_eng not found. 自己手动安装下 python -m nltk.downloader averaged_perceptron_tagger_eng
