### ISSUE TITLE
自己训练的语音模型，调用接口出现错误： cannot import name 'has_collective_ops' from 'onnxruntime.capi._pybind_state'

### ISSUE THREAD

**Issue by wxzz** [RVC-Boss/GPT-SoVITS#1554]
**我在本机，使用的是win10，有显卡资源，8G显存，没有问题。
但是由于太慢了，我换了一个虚拟服务器，操作系统是：windows server 2022，但是没有显卡资源。
我把win10的软件环境配置和程序复制到windows 2022，启动接口和调用接口，出现如下错误。（注：直接python api.py，是没有问题的。）

启动接口：python api.py -s SoVITS_weights_v2\myself_sound_20240812_e8_s104.pth -g GPT_weights_v2\myself_sound_20240812-e15.ckpt
调用接口： http://127.0.0.1:9880?refer_wav_path=zh.wav&prompt_text=太祖是怎么评价秦朝宰相李斯的&prompt_language=zh&text=先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也&text_language=zh**

INFO:     127.0.0.1:52176 - "GET /?refer_wav_path=zh.wav&prompt_text=%E5%A4%AA%E7%A5%96%E6%98%AF%E6%80%8E%E4%B9%88%E8%AF%84%E4%BB%B7%E7%A7%A6%E6%9C%9D%E5%AE%B0%E7%9B%B8%E6%9D%8E%E6%96%AF%E7%9A%84&prompt_language=zh&text=%E5%85%88%E5%B8%9D%E5%88%9B%E4%B8%9A%E6%9C%AA%E5%8D%8A%E8%80%8C%E4%B8%AD%E9%81%93%E5%B4%A9%E6%AE%82%EF%BC%8C%E4%BB%8A%E5%A4%A9%E4%B8%8B%E4%B8%89%E5%88%86%EF%BC%8C%E7%9B%8A%E5%B7%9E%E7%96%B2%E5%BC%8A%EF%BC%8C%E6%AD%A4%E8%AF%9A%E5%8D%B1%E6%80%A5%E5%AD%98%E4%BA%A1%E4%B9%8B%E7%A7%8B%E4%B9%9F&text_language=zh HTTP/1.1" 200 OK
当前使用g2pw进行拼音推理
当前使用g2pw进行拼音推理
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\anaconda3\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\anaconda3\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\anaconda3\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "D:\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "D:\anaconda3\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "D:\anaconda3\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\anaconda3\Lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\GPT-SoVITS-v2-240807\api.py", line 531, in get_tts_wav
    phones1, bert1, norm_text1 = get_phones_and_bert(prompt_text, prompt_language, version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-SoVITS-v2-240807\api.py", line 334, in get_phones_and_bert
    phones, word2ph, norm_text = clean_text_inf(textlist[i], lang, version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-SoVITS-v2-240807\api.py", line 260, in clean_text_inf
    phones, word2ph, norm_text = clean_text(text, language, version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-SoVITS-v2-240807/GPT_SoVITS\text\cleaner.py", line 36, in clean_text
    language_module = __import__("text."+language_module_map[language],fromlist=[language_module_map[language]])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT-SoVITS-v2-240807/GPT_SoVITS\text\chinese2.py", line 28, in <module>
    from text.g2pw import G2PWPinyin, correct_pronunciation
  File "D:\GPT-SoVITS-v2-240807/GPT_SoVITS\text\g2pw\__init__.py", line 1, in <module>
    from text.g2pw.g2pw import *
  File "D:\GPT-SoVITS-v2-240807/GPT_SoVITS\text\g2pw\g2pw.py", line 11, in <module>
    from .onnx_api import G2PWOnnxConverter
  File "D:\GPT-SoVITS-v2-240807/GPT_SoVITS\text\g2pw\onnx_api.py", line 15, in <module>
    import onnxruntime
  File "D:\anaconda3\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\anaconda3\Lib\site-packages\onnxruntime\__init__.py", line 45, in <module>
    from onnxruntime.capi._pybind_state import has_collective_ops  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'has_collective_ops' from 'onnxruntime.capi._pybind_state' (D:\anaconda3\Lib\site-packages\onnxruntime\capi\_pybind_state.py)  （**注：实际上这个文件是有的。**）

![image](https://github.com/user-attachments/assets/f5798a24-0389-40d3-a819-e0746a314908)

**Comment by wxzz** [comment]
pip uninstall onnxruntime-gpu
pip install onnxruntime-1.19.0-cp311-cp311-win_amd64.whl

这样解决了。
