### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by YuChuanhui3** [RVC-Boss/GPT-SoVITS#1560]
执行api_v3.py报错: conda环境，python 3.9.19 cuda 12.6，

Traceback (most recent call last):
  File "D:\gptsovits2\GPT-SoVITS\api_v3_multi_process.py", line 122, in <module>
    from GPT_SoVITS.TTS_infer_pack.TTS import TTS, TTS_Config
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\__init__.py", line 1, in <module>
    from . import TTS, text_segmentation_method
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 27, in <module>
    from TTS_infer_pack.text_segmentation_method import splits
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\__init__.py", line 1, in <module>
    from . import TTS, text_segmentation_method
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 28, in <module>
    from TTS_infer_pack.TextPreprocessor import TextPreprocessor
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TextPreprocessor.py", line 13, in <module>
    from text.cleaner import clean_text
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "D:\gptsovits2\GPT-SoVITS\GPT_SoVITS\text\english.py", line 5, in <module>
    from g2p_en import G2p
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\site-packages\g2p_en\__init__.py", line 1, in <module>
    from .g2p import G2p
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\site-packages\g2p_en\g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\site-packages\nltk\data.py", line 538, in find
    return ZipFilePathPointer(p, zipentry)
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\site-packages\nltk\data.py", line 391, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\site-packages\nltk\data.py", line 1020, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\zipfile.py", line 1268, in __init__
    self._RealGetContents()
  File "C:\Users\Administrator\.conda\envs\GPTSoVits\lib\zipfile.py", line 1335, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by XXXXRT666** [comment]
nltk问题，中文教程中下载nltk

**Comment by RVC-Boss** [comment]
nltk这个库，我也很头大

可能是他那个zip文件下载一半断网了
