### ISSUE TITLE
运行API.py

### ISSUE THREAD

**Issue by counsd** [RVC-Boss/GPT-SoVITS#1567]

**Comment by counsd** [comment]
一当我运行：.\runtime\python api2.py -dr "cankao.wav" -dt "为了隐私不展示" -dl "zh"时，出现以下报错：
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "F:\EVoice\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "F:\EVoice\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "F:\EVoice\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'F:\EVoice\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\EVoice\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "F:\EVoice\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
Traceback (most recent call last):
  File "F:\EVoice\api2.py", line 229, in <module>
    from GPT_SoVITS.my_utils import load_audio
ModuleNotFoundError: No module named 'GPT_SoVITS.my_utils'
