### ISSUE TITLE
Unable to import backend : mxnet

### ISSUE THREAD

**Issue by zhou20120904** [RVC-Boss/GPT-SoVITS#157]
完全无法使用。
当我尝试进行训练集格式化时，报错。
`Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 42, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/bert/modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
    from ...modeling_utils import PreTrainedModel
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 88, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 88, in <module>
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/__init__.py", line 3, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/accelerator.py", line 41, in <module>
    from .accelerator import Accelerator
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/tracking.py", line 43, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/tracking.py", line 43, in <module>
    from torch.utils import tensorboard
    from torch.utils import tensorboard
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
    from .writer import FileWriter, SummaryWriter  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 16, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 16, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/_embedding.py", line 9, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/tensorboard/_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
                              ^^^^^
                              ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 65, in __getattr__
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
    return getattr(load_once(self), attr_name)
                   ^^^^^^^^^^^^^^^
                   ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 97, in wrapper
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
    cache[arg] = f(arg)
                 ^^^^^^
                 ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 50, in load_once
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
    module = load_fn()
             ^^^^^^^^^
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/compat/__init__.py", line 45, in tf
  File "/opt/homebrew/lib/python3.11/site-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
    import tensorflow
  File "/opt/homebrew/lib/python3.11/site-packages/tensorflow/__init__.py", line 478, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/tensorflow/__init__.py", line 478, in <module>
    importlib.import_module("keras.optimizers")
    importlib.import_module("keras.optimizers")
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/keras/__init__.py", line 8, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/keras/__init__.py", line 8, in <module>
    from keras import _tf_keras
  File "/opt/homebrew/lib/python3.11/site-packages/keras/_tf_keras/__init__.py", line 1, in <module>
    from keras import _tf_keras
  File "/opt/homebrew/lib/python3.11/site-packages/keras/_tf_keras/__init__.py", line 1, in <module>
    from keras._tf_keras import keras
    from keras._tf_keras import keras
  File "/opt/homebrew/lib/python3.11/site-packages/keras/_tf_keras/keras/__init__.py", line 8, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/keras/_tf_keras/keras/__init__.py", line 8, in <module>
    from keras import activations
    from keras import activations
  File "/opt/homebrew/lib/python3.11/site-packages/keras/activations/__init__.py", line 8, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/keras/activations/__init__.py", line 8, in <module>
    from keras.src.activations import deserialize
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src.activations import deserialize
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src import activations
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
    from keras.src.activations.activations import elu
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/activations/activations.py", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/backend/__init__.py", line 45, in <module>
    from keras.src import backend
  File "/opt/homebrew/lib/python3.11/site-packages/keras/src/backend/__init__.py", line 45, in <module>
    raise ValueError(f"Unable to import backend : {backend()}")
    raise ValueError(f"Unable to import backend : {backend()}")
ValueError: Unable to import backend : mxnet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
ValueError: Unable to import backend : mxnet
  File "/Users/xiaochenyue/Desktop/zjy/gpt-sovits/GPT_SoVITS/prepare_datasets/1-get-text.py", line 51, in <module>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xiaochenyue/Desktop/zjy/gpt-sovits/GPT_SoVITS/prepare_datasets/1-get-text.py", line 51, in <module>
    bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir)
    bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 515, in from_pretrained
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 515, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
    model_class = _get_model_class(config, cls._model_mapping)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 377, in _get_model_class
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 377, in _get_model_class
    supported_models = model_mapping[type(config)]
    supported_models = model_mapping[type(config)]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 690, in __getitem__
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 690, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 704, in _load_attr_from_module
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 704, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 648, in getattribute_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 648, in getattribute_from_module
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
Unable to import backend : mxnet
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
Unable to import backend : mxnet
Traceback (most recent call last):
  File "/Users/xiaochenyue/Desktop/zjy/gpt-sovits/webui.py", line 499, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs/venti/2-name2text-0.txt'`
文件找不到是小事，backend出事是大事

**Comment by zhou20120904** [comment]
顺便说句，如果我想启动其他东西，多半也会出现Unable to import backend : mxnet的提示

**Comment by zhou20120904** [comment]
用python3.10说不定就好了（小声bb）

**Comment by zhou20120904** [comment]
还真可以！
