### ISSUE TITLE
SOVITS训练 GPU里的CUDA0% 没爆内存 控制台也没反应 半小时1小时后报错这样

### ISSUE THREAD

**Issue by LouisNee** [RVC-Boss/GPT-SoVITS#1572]
"D:\GPT-SoVITS-v2-240821\runtime\python.exe" GPT_SoVITS/s2_train.py --config "D:\GPT-SoVITS-v2-240821\TEMP/tmp_s2.json"
[E C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (localhost, 42673).
Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2-240821\GPT_SoVITS\s2_train.py", line 601, in <module>
    main()
  File "D:\GPT-SoVITS-v2-240821\GPT_SoVITS\s2_train.py", line 57, in main
    mp.spawn(
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\GPT-SoVITS-v2-240821\GPT_SoVITS\s2_train.py", line 76, in run
    dist.init_process_group(
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (localhost, 42673).

**Comment by LouisNee** [comment]
为了处理这个问题已经网上找答案找了几天了不知道怎么解决！~

**Comment by XXXXRT666** [comment]
关闭防火墙

**Comment by LouisNee** [comment]
> 关闭防火墙

试过了 关了杀毒 关了防火墙

**Comment by b1ackwater3** [comment]
请问解决了吗

**Comment by LouisNee** [comment]
重装操作系统把n 卡的驱动升级到最新

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: b1ackwater3 ***@***.***>
发送时间: Tuesday, September 10, 2024 1:44:26 PM
收件人: RVC-Boss/GPT-SoVITS ***@***.***>
抄送: LouisNee ***@***.***>; Author ***@***.***>
主题: Re: [RVC-Boss/GPT-SoVITS] SOVITS训练 GPU里的CUDA0% 没爆内存 控制台也没反应 半小时1小时后报错这样 (Issue #1572)


请问解决了吗

―
