### ISSUE TITLE
v1升级到v2,训练中文模型,一键三联时,开启文本获取时报错了.

### ISSUE THREAD

**Issue by dassiyu** [RVC-Boss/GPT-SoVITS#1576]
zhxiyan.mp3_0000883200_0000927360.wav 现在多少钱？ Traceback (most recent call last):
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 92, in process
    phones, word2ph, norm_text = clean_text(
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 36, in clean_text
    language_module = __import__("text."+language_module_map[language],fromlist=[language_module_map[language]])
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\text\chinese2.py", line 28, in <module>
    from text.g2pw import G2PWPinyin, correct_pronunciation
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\text\g2pw\__init__.py", line 1, in <module>
    from text.g2pw.g2pw import *
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\text\g2pw\g2pw.py", line 11, in <module>
    from .onnx_api import G2PWOnnxConverter
  File "D:\GPT-SoVITS v2\GPT-SoVITS\GPT_SoVITS\text\g2pw\onnx_api.py", line 17, in <module>
    from opencc import OpenCC
ModuleNotFoundError: No module named 'opencc'

**Comment by XXXXRT666** [comment]
如果是整合包,那就去下最新整合包,如果不是,就手动安装

**Comment by dassiyu** [comment]
谢谢回复，是整合包,覆盖后再次pip install -r requirements.txt 后还是报这个错。。

**Comment by dassiyu** [comment]
可以了，我没在激活环境下安装。现在可以了
