### ISSUE TITLE
GPT训练报错 折磨我三天了大神给个解决方案

### ISSUE THREAD

**Issue by LouisNee** [RVC-Boss/GPT-SoVITS#1577]
GPT训练时报错信息
"D:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "D:\GPT-SoVITS\TEMP/tmp_s1.yaml"
Traceback (most recent call last):
  File "D:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 12, in <module>
    from pytorch_lightning import seed_everything
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\utilities\types.py", line 40, in <module>
    from torchmetrics import Metric
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchmetrics\utilities\imports.py", line 54, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "D:\GPT-SoVITS\runtime\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "importlib\__init__.py", line 127, in import_module
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\GPT-SoVITS\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

文档解决方案
在runtime文件夹中打开cmd，输入python -m pip uninstall torch torchaudio
以及python -m pip install torch==2.3.0 torchaudio --index-url https://download.pytorch.org/whl/cu118

命令安装完后的警告
WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'D:\GPT-SoVITS\runtime\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
torch-directml 0.2.0.dev230426 requires torch==2.0.0, but you have torch 2.3.0 which is incompatible.
torchvision 0.15.1 requires torch==2.0.0, but you have torch 2.3.0 which is incompatible.

打开整合包启动 go-webui.bat 后的报警

D:\GPT-SoVITS>runtime\python.exe webui.py zh_CN
Traceback (most recent call last):
  File "D:\GPT-SoVITS\webui.py", line 9, in <module>
    import json,yaml,torch,pdb,re,shutil
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\GPT-SoVITS\runtime\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

D:\GPT-SoVITS>pause
请按任意键继续. . .

**Comment by foreverhell** [comment]
看样子是环境有问题，版本不匹配
试试bash install.sh

**Comment by foreverhell** [comment]
看样子是环境有问题，版本不匹配
试试bash install.sh
或者pip install -r requirements.txt

**Comment by bfloat16** [comment]
用这个工具https://github.com/lucasg/Dependencies，检查D:\GPT-SoVITS\runtime\lib\site-packages\torch\lib\fbgemm.dll缺失了哪个dll，然后手动下载，放到fbgemm.dll旁边

**Comment by RVC-Boss** [comment]
按照楼上的方法试试看呢？

**Comment by LouisNee** [comment]
解决了，我重装了系统吧n 卡驱动升级到最新版本没问题了

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: RVC-Boss ***@***.***>
发送时间: Tuesday, September 10, 2024 7:22:29 PM
收件人: RVC-Boss/GPT-SoVITS ***@***.***>
抄送: LouisNee ***@***.***>; Author ***@***.***>
主题: Re: [RVC-Boss/GPT-SoVITS] GPT训练报错 折磨我三天了大神给个解决方案 (Issue #1577)


按照楼上的方法试试看呢？

―

**Comment by maolintao** [comment]
我的问题这样解决了，删除GPT-SoVITS-v3lora-20250228\runtime\Lib\site-packages\torchaudio\lib目录下_torchaudio.pyd这个文件的前缀下划线
参考：https://github.com/neonbjb/tortoise-tts/issues/298#issuecomment-2174432438

I just navigated to Python\Python312\Lib\site-packages\torchaudio\lib and removed the _ prefix on torchaudio.pyd. Maybe there's a reason that the underscore was there?
我刚刚导航到 Python\Python312\Lib\site-packages\torchaudio\lib 并删除了 torchaudio.pyd 上的 _ 前缀。也许下划线存在是有原因的？

File "D:\AI\GPT-SoVITS-v3lora-20250228\runtime\lib\site-packages\torch_ops.py", line 643, in load_library ctypes.CDLL(path) File "ctypes__init__.py", line 374, in init FileNotFoundError: Could not find module 'D:\AI\GPT-SoVITS-v3lora-20250228\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

笔记本电脑，win11，家庭版，也报这个错误，请问笔记本电脑集成显卡可以跑这个吗，报错解决

**Comment by nanhui69** [comment]
linux 下有这个问题么？
