### ISSUE TITLE
新代码在纯CPU电脑上，无法刷新模型列表

### ISSUE THREAD

**Issue by eureka6** [RVC-Boss/GPT-SoVITS#1589]
新git clone的代码，在**CPU-only**情况下，刷新模型列表，提示ERROR，搭建方法和8月中旬完全一致，那时候是没有这样的报错的。

![b8c48929bc066bdc11584a79df2ce193.png](https://ice.frostsky.com/2024/09/06/b8c48929bc066bdc11584a79df2ce193.png)

命令行报错如下
```
Running on local URL:  http://0.0.0.0:9874
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/gradio/route_utils.py", line 686, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/gradio/route_utils.py", line 702, in simple_response
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/opt/miniconda3/envs/tts/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

GPT回答这个：
>这个错误看起来是由于 Pydantic 库在处理某些类型时出现了问题。__pydantic_core_schema__ 属性缺失通常表示库版本不兼容或者内部接口变化。
    1.确保 Pydantic、FastAPI 和 Uvicorn 都是最新版本，并且它们之间兼容。
    2.如果是最近更新过库，尝试回退到旧版本看看是否解决问题。
    3.检查你的代码中是否有不符合 Pydantic 标准的部分。

此外，运行`pip install -r requirements.txt`提示：
```
WARNING: typer 0.12.5 does not provide the extra 'all'
```

**Comment by eureka6** [comment]
把`requirements.txt`里的`gradio`一项，改为`gradio==4.43.0`，即可成功推理，只是命令行提示有点问题。

```
<All keys matched successfully>
Number of parameter: 77.61M
Number of parameter: 77.61M
<All keys matched successfully>
```

**Comment by XXXXRT666** [comment]
降级fastapi

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/3488cffd68752ce72f91d581585770ff18c9a1b3

**Comment by Mnji4** [comment]
救命恩人

**Comment by shmilyfuu** [comment]
> 把`requirements.txt`里的`gradio`一项，改为`gradio==4.43.0`，即可成功推理，只是命令行提示有点问题。
> 
> ```
> <All keys matched successfully>
> Number of parameter: 77.61M
> Number of parameter: 77.61M
> <All keys matched successfully>
> ```

帮大忙了！
