### ISSUE TITLE
error occured while I click on the "go-webui.bat"

### ISSUE THREAD

**Issue by fatdennis** [RVC-Boss/GPT-SoVITS#1614]
D:\GPT-SoVITS-v2-240821>runtime\python.exe webui.py
Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2-240821\webui.py", line 48, in <module>
    from tools import my_utils
  File "D:\GPT-SoVITS-v2-240821\tools\my_utils.py", line 4, in <module>
    import gradio as gr
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\processing_utils.py", line 21, in <module>
    from gradio import utils, wasm_utils
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 52, in <module>
    from gradio.data_classes import FileData
  File "D:\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\data_classes.py", line 18, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (C:\Users\Dennis\AppData\Roaming\Python\Python39\site-packages\pydantic\__init__.cp39-win_amd64.pyd)

D:\GPT-SoVITS-v2-240821>pause
請按任意鍵繼續 . . .

Then, cannot proceed further

**Comment by bfloat16** [comment]
删掉系统里面自带的python

**Comment by fatdennis** [comment]
> 删掉系统里面自带的python

如果uninstall python的，其他AI app會否有影響？

**Comment by bfloat16** [comment]
> > 删掉系统里面自带的python
> 
> 如果uninstall python的，其他AI app會否有影響？

如果别的app使用的是系统里面的python，那会有影响
如果是自带python运行环境则没问题

**Comment by RVC-Boss** [comment]
改下你系统的python根目录文件夹名称，要用的时候再改回来也行，或者有人提出独立环境不参考系统环境影响的办法
