### ISSUE TITLE
一键三联时，哪位大神遇见过这个问题？TypeError: unsupported operand type(s) for +: 'ZipFilePathPointer' and 'str'

### ISSUE THREAD

**Issue by ztl198573** [RVC-Boss/GPT-SoVITS#1628]
一键三联第一步时，第一步开启文本获取，遇见英文音频就会报这个错，

nie_0912.WAV_0008968000_0009176640.wav Big data technologies enable organization to process. Traceback (most recent call last):
  File "/home/xrk/data2/sun_ai_dev/GPT-SoVITS-v2/GPT_SoVITS/prepare_datasets/1-get-text.py", line 92, in process
    phones, word2ph, norm_text = clean_text(
  File "/home/xrk/data2/sun_ai_dev/GPT-SoVITS-v2/GPT_SoVITS/text/cleaner.py", line 46, in clean_text
    phones = language_module.g2p(norm_text)
  File "/home/xrk/data2/sun_ai_dev/GPT-SoVITS-v2/GPT_SoVITS/text/english.py", line 365, in g2p
    phone_list = _g2p(text)
  File "/home/xrk/data2/sun_ai_dev/GPT-SoVITS-v2/GPT_SoVITS/text/english.py", line 272, in __call__
    tokens = pos_tag(words)  # tuples of (word, tag)
  File "/home/xrk/miniconda3/envs/gpt_sovits_v2/lib/python3.9/site-packages/nltk/tag/__init__.py", line 168, in pos_tag
    tagger = _get_tagger(lang)
  File "/home/xrk/miniconda3/envs/gpt_sovits_v2/lib/python3.9/site-packages/nltk/tag/__init__.py", line 110, in _get_tagger
    tagger = PerceptronTagger()
  File "/home/xrk/miniconda3/envs/gpt_sovits_v2/lib/python3.9/site-packages/nltk/tag/perceptron.py", line 183, in __init__
    self.load_from_json(lang)
  File "/home/xrk/miniconda3/envs/gpt_sovits_v2/lib/python3.9/site-packages/nltk/tag/perceptron.py", line 274, in load_from_json
    with open(loc + TAGGER_JSONS[lang]["weights"]) as fin:
TypeError: unsupported operand type(s) for +: 'ZipFilePathPointer' and 'str'

**Comment by ztl198573** [comment]
呃……好吧，我自己解决掉了，因为众所周知的原因，我是通过镜像下载的nltk_data,然后进行的离线部署，nltk_data里边的文件全都是zip文件，需要逐一手动解压后这样才能被perceptron.py load_from_json加载到，其实提示信息已经很明显了，自己脑抽没有仔细去看一下，希望对其他的使用者能有些帮助

**Comment by RVC-Boss** [comment]
好的

**Comment by CodeAIF** [comment]
1.nltk_data 离线下载并放在ubuntu 目录下，但是还会有英文中文混码输入问题  2.核对nltk 版本，测试了3.9.1版本存在问题，卸载后替换3.8.1解决

**Comment by kkkwjr** [comment]
> 呃……好吧，我自己解决掉了，因为众所周知的原因，我是通过镜像下载的nltk_data,然后进行的离线部署，nltk_data里边的文件全都是zip文件，需要逐一手动解压后这样才能被perceptron.py load_from_json加载到，其实提示信息已经很明显了，自己脑抽没有仔细去看一下，希望对其他的使用者能有些帮助

想问一下具体是怎么操作呢，我跟你有类似的错误。
![image](https://github.com/user-attachments/assets/85de8de7-1ccc-468b-8b98-af7e1567ced4)
上面所有的全部需要解压吗

**Comment by ztl198573** [comment]
你可以看提示，尝试缺那个解压哪个，时间有点长，我记不太清了，我好像是解压了几个，一直报缺，我就批量全解压了
