### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by potatoker** [RVC-Boss/GPT-SoVITS#163]
训练的时候报错：AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

```
Traceback (most recent call last):
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 566, in <module>
    main()
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 53, in main
    mp.spawn(
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 236, in run
    train_and_evaluate(
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 416, in train_and_evaluate
    utils.summarize(
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/utils.py", line 103, in summarize
    writer.add_image(k, v, global_step, dataformats="HWC")
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 614, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 441, in image
    image = make_image(tensor, rescale=rescale)
  File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 486, in make_image
    image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

操作系统为centos

**Comment by RVC-Boss** [comment]
你看看你那Image有哪些缩放方法，我写个有的吧。

**Comment by Nomination-NRB** [comment]
> Image

Image.ANTIALIAS替换为：Image.Resampling.LANCZOS

**Comment by Nomination-NRB** [comment]
> 训练的时候报错：AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
> 
> ```
> Traceback (most recent call last):
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 566, in <module>
>     main()
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 53, in main
>     mp.spawn(
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 236, in run
>     train_and_evaluate(
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 416, in train_and_evaluate
>     utils.summarize(
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/GPT_SoVITS/utils.py", line 103, in summarize
>     writer.add_image(k, v, global_step, dataformats="HWC")
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 614, in add_image
>     image(tag, img_tensor, dataformats=dataformats), global_step, walltime
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 441, in image
>     image = make_image(tensor, rescale=rescale)
>   File "/apdcephfs/private_raymondguo/tts/GPT-SoVITS/env/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 486, in make_image
>     image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)
> AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
> ```
> 
> 操作系统为centos

Image.ANTIALIAS替换为：Image.Resampling.LANCZOS

**Comment by Spphire** [comment]
pip install pillow==9.5.0
降低版本

**Comment by RVC-Boss** [comment]
done
