### ISSUE TITLE
NameError: name 'symbols' is not defined

### ISSUE THREAD

**Issue by ZackRackRole** [RVC-Boss/GPT-SoVITS#1667]
Hi,

When I try to run step 1s -- dataset formatting -- I get the following error:
```
vocal_Saya.wav.reformatted.wav_10.flac_0022832960_0022952000.wav
vocal_Saya.wav.reformatted.wav_10.flac_0022832960_0022952000.wav 拙者としても、そなたのライフを歓迎しよう Traceback (most recent call last):
  File "/content/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 92, in process
    phones, word2ph, norm_text = clean_text(
  File "/content/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 51, in clean_text
    phones = language_module.g2p(norm_text)
  File "/content/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 219, in g2p
    phones = [post_replace_ph(i) for i in phones]
  File "/content/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 219, in <listcomp>
    phones = [post_replace_ph(i) for i in phones]
  File "/content/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 85, in post_replace_ph
    if ph not in symbols:
NameError: name 'symbols' is not defined
```

I am using a colab notebook. I have processed the audio using the modules provided in the webui. The pretrained models I am using are /content/GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth, /content/GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2D2333k.pth, and /content/GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt. My GPU is NVIDIA A100-SXM4-40GB.

This happens with both V1 and V2. 

Is the issue that the pretrained BERT model is GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large, which is a model in Chinese? This box is not editable in the webui.

Thank you.

**Comment by SapphireLab** [comment]
I am confused about the code version you are using because the line number "85" seems to be the latest version but the code has already been commented out as in PR #1390 about two months ago when its line number is "63".
