### ISSUE TITLE
无法打开TTS推理的WebUI且控制台报错：RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by MrA380** [RVC-Boss/GPT-SoVITS#1671]
使用WebUI的1-GPT-SoVITS_TTS中的1c-推理模块时：
无法正常打开TTS推理的WebUI
且控制台（日志）报错：RuntimeError: CUDA error: no kernel image is available for execution on the device
环境：Windows 10 22H2\已配置ffmpeg、ffprobe\GPU：(N)GeForce GTX 650

**Comment by MrA380** [comment]
**Console**
"F:\ai-nina\GPT-SoVITS-v2-240821\runtime\python.exe" GPT_SoVITS/inference_webui_fast.py "zh_CN"
---------------------------------------------TTS Config---------------------------------------------
device              : cuda
is_half             : True
version             : v2
t2s_weights_path    : GPT_weights/芹井仁菜V3-e15.ckpt
vits_weights_path   : SoVITS_weights/芹井仁菜V3_e100_s1800.pth
bert_base_path      : GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
cnhuhbert_base_path : GPT_SoVITS/pretrained_models/chinese-hubert-base
----------------------------------------------------------------------------------------------------

Loading Text2Semantic weights from GPT_weights/芹井仁菜V3-e15.ckpt
Traceback (most recent call last):
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui_fast.py", line 106, in <module>
    tts_pipeline = TTS(tts_config)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 243, in __init__
    self._init_models()
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 268, in _init_models
    self.init_t2s_weights(self.configs.t2s_weights_path)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 346, in init_t2s_weights
    self.t2s_model = self.t2s_model.half()
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 99, in half
    return super().half()
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
**RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.**

**Comment by SapphireLab** [comment]
原因可能是整合包中的 torch 使用的是对应 CUDA 11.8 的版本, CUDA 11.8 支持的显卡算力应在 3.5 以上, 而 GTX 650 只有 3.0.
可参阅 https://en.wikipedia.org/wiki/CUDA#GPUs_supported.

- 可以考虑用 CPU 运行 (简单的修改如下): 
  - 在 `~\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui.py` 中 100 行左右，输入 `device="cpu"`；
  - 类似地，勾选并行推理时，在 `~\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui_fast.py` 中 60 行左右，输入 `device="cpu"` 即可.
- 或者自行降级环境以兼容 GPU, 但版本比较过时不能保证全部顺利运行.
- 换个设备.

**Comment by MrA380** [comment]
**感谢！**
WebUI没问题了
但是我又遇到了问题，我会单开一个issues的！
