### ISSUE TITLE
合成语音时错误，控制台显示RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by MrA380** [RVC-Boss/GPT-SoVITS#1673]
### Main Issues
使用1c-推理模块合成语音时：
**无法正常合成TTS语音**
且控制台（日志）报错：RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
环境：Windows 10 22H2\已配置ffmpeg、ffprobe\GPU：(N)GeForce GTX 650

### Console
Set seed to 943176539
并行推理模式已开启
分桶处理模式已开启
Traceback (most recent call last):
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\blocks.py", line 1267, in call_function
    prediction = await utils.async_iteration(iterator)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 574, in async_iteration
    return await iterator.__anext__()
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 567, in __anext__
    return await anyio.to_thread.run_sync(
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 550, in run_sync_iterator_async
    return next(iterator)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\gradio\utils.py", line 733, in gen_wrapper
    response = next(iterator)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\inference_webui_fast.py", line 146, in inference
    for item in tts_pipeline.run(inputs):
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 726, in run
    self.set_ref_audio(ref_audio_path)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 407, in set_ref_audio
    self._set_prompt_semantic(ref_audio_path)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\GPT_SoVITS\TTS_infer_pack\TTS.py", line 459, in _set_prompt_semantic
    hubert_feature = self.cnhuhbert_model.model(wav16k.unsqueeze(0))[
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 1081, in forward
    extract_features = self.feature_extractor(input_values)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 354, in forward
    hidden_states = conv_layer(hidden_states)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 256, in forward
    hidden_states = self.conv(hidden_states)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "F:\ai-nina\GPT-SoVITS-v2-240821\runtime\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by SapphireLab** [comment]
忘了提醒使用 CPU 时需要调整这个半精度设置了, 考虑后续优化一下.

修改的方式很多, 只要保证 `config.py` 下的 `is_half` 最终为 False 即可 (因为 CPU 不支持半精度运算.)

- 可以在 `config.py` 中约 24 行增加 `infer_device='cpu'`: 指定推理设备为 CPU, 后续条件语句会将 `is_half` 设置为 False;
- 或者在 `config.py` 中约 12 行增加 `is_half=False`: 提前手动指定 `is_half=False`.

相关报错可以参阅 [报错合集 6.5](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt#I8Eq8)

**Comment by RVC-Boss** [comment]
楼上正解。
