### ISSUE TITLE
when SoVITS training， IndexError: list index out of range

### ISSUE THREAD

**Issue by huangyingbo663** [RVC-Boss/GPT-SoVITS#1693]
Traceback (most recent call last):
  File "/root/workspace/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 601, in <module>
    main()
  File "/root/workspace/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 57, in main
    mp.spawn(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

During handling of the above exception, another exception occurred:
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/workspace/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 196, in run
    utils.latest_checkpoint_path("%s/logs_s2" % hps.data.exp_dir, "D_*.pth"),
  File "/root/workspace/GPT-SoVITS/GPT_SoVITS/utils.py", line 120, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/root/workspace/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 232, in run
    torch.load(hps.train.pretrained_s2D, map_location="cpu")["weight"]
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by RVC-Boss** [comment]
The model parameters you downloaded are incomplete. You need to download them again and ensure they are complete.
