### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1024) must match the existing size (768) at non-singleton dimension 0

### ISSUE THREAD

**Issue by shelltea** [RVC-Boss/GPT-SoVITS#1742]
各位大佬求助一下，在进行GPT训练时报错，报错日志如下：
SoVITS训练是正常的。

```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\nn\modules\module.py:1326: UserWarning: expandable_segments not supported on this platform (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/cuda/CUDAAllocatorConfig.h:28.)
  return t.to(

  | Name  | Type                 | Params | Mode
-------------------------------------------------------
0 | model | Text2SemanticDecoder | 77.6 M | train
-------------------------------------------------------
77.6 M    Trainable params
0         Non-trainable params
77.6 M    Total params
310.426   Total estimated model params size (MB)
257       Modules in train mode
0         Modules in eval mode
D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py:230: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  bert_feature = torch.load(path_bert, map_location="cpu")
D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py:230: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  bert_feature = torch.load(path_bert, map_location="cpu")
D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py:230: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  bert_feature = torch.load(path_bert, map_location="cpu")
Epoch 0:   0%|                                                          | 0/175 [00:00<?, ?it/s]D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py:230: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  bert_feature = torch.load(path_bert, map_location="cpu")
[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 184, in <module>
[rank0]:     main(args)
[rank0]:   File "D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 160, in main
[rank0]:     trainer.fit(model, data_module, ckpt_path=ckpt_path)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 538, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\trainer\call.py", line 46, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 574, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 981, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1025, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 205, in run
[rank0]:     self.advance()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 363, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 140, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 212, in advance
[rank0]:     batch, _, __ = next(data_fetcher)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 133, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 60, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 341, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 78, in __next__
[rank0]:     out[i] = next(self.iterators[i])
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\_utils.py", line 715, in reraise
[rank0]:     raise exception
[rank0]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "C:\Users\xxx\scoop\apps\miniconda3\current\envs\GPTSoVits\lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
[rank0]:     return self.collate_fn(data)
[rank0]:   File "D:\Development\Projects\GitHub\RVC-Boss\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 282, in collate
[rank0]:     bert_padded[idx, :, : bert.shape[-1]] = bert
[rank0]: RuntimeError: The expanded size of the tensor (1024) must match the existing size (768) at non-singleton dimension 0.  Target sizes: [1024, 50].  Tensor sizes: [768, 50]
```

**Comment by coolMountain** [comment]
怎么解决这个报错的？

**Comment by shelltea** [comment]
> 怎么解决这个报错的？

没有解决。🤦
