### ISSUE TITLE
语义token提取：PermissionError: [Errno 13] Permission denied: 'GPT_SoVITS\\pretrained_models\\gsv-v2final-pretrained'

### ISSUE THREAD

**Issue by HelloLittleJoey** [RVC-Boss/GPT-SoVITS#1765]
有谁遇到这个问题吗？
"E:\AI\github\GPT-SoVITS\.venv\Scripts\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"E:\AI\github\GPT-SoVITS\.venv\Scripts\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
Traceback (most recent call last):
  File "E:\AI\github\GPT-SoVITS\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 69, in <module>
    torch.load(pretrained_s2G, map_location="cpu")["weight"], strict=False
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'GPT_SoVITS\\pretrained_models\\gsv-v2final-pretrained'
Traceback (most recent call last):
  File "E:\AI\github\GPT-SoVITS\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 69, in <module>
    torch.load(pretrained_s2G, map_location="cpu")["weight"], strict=False
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'GPT_SoVITS\\pretrained_models\\gsv-v2final-pretrained'
Traceback (most recent call last):
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\queueing.py", line 561, in process_events
    response = await route_utils.call_process_api(
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\blocks.py", line 1267, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 574, in async_iteration
    return await iterator.__anext__()
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 567, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 550, in run_sync_iterator_async
    return next(iterator)
  File "E:\AI\github\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 733, in gen_wrapper
    response = next(iterator)
  File "e:\AI\github\GPT-SoVITS\webui.py", line 594, in open1c
    with open(semantic_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/sunyanzi_v2/6-name2semantic-0.tsv'

**Comment by HelloLittleJoey** [comment]
问题解决了，原因是：
1、先开启webui，发现gsv-v2final-pretrained没有下载
2、中途下载gsv-v2final-pretrained底模，手动创建文件夹，报上述错误
3、重启webui后恢复正常
