### ISSUE TITLE
wsl2 amd rocm6.1.3 训练时出现以下错误

### ISSUE THREAD

**Issue by AMD7900XTX** [RVC-Boss/GPT-SoVITS#1818]
```
"/home/user/anaconda3/envs/sd/bin/python" GPT_SoVITS/s2_train.py --config "/home/user/GPT-SoVITS/GPT-SoVITS/TEMP/tmp_s2.json"
phoneme_data_len: 36
wav_data_len: 72
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72/72 [00:00<00:00, 74436.75it/s]
skipped_phone:  0 , skipped_dur:  0
total left:  72
Traceback (most recent call last):
  File "/home/user/GPT-SoVITS/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 601, in <module>
    main()
  File "/home/user/GPT-SoVITS/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 57, in main
    mp.spawn(
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 328, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 284, in start_processes
    while not context.join():
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 203, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 90, in _wrap
    fn(i, *args)
  File "/home/user/GPT-SoVITS/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 188, in run
    net_g = DDP(net_g, device_ids=[rank], find_unused_parameters=True)
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/user/anaconda3/envs/sd/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, internal error - please report this issue to the NCCL developers, NCCL version 2.18.6
ncclInternalError: Internal check failed.
Last error:
Socket recv failed while polling for opId=0x7ee0ccb35bf0

```

**Comment by moyutegong** [comment]
这是NCCL的问题，你需要将s1_train.py 和s2_train.py 对应的代码的nccl改成gloo，s1_train.py 修改后的代码应该是process_group_backend="gloo" ，如果你没有修改其他代码的话，应该是第131行，s2_train.py 修改后的代码应该是 backend = "gloo"，对应位置为第77行

**Comment by AMD7900XTX** [comment]
@moyutegong 此法有用，但s2的有出入，其原代码为
`backend = "gloo" if os.name == "nt" or not torch.cuda.is_available() else "nccl"`
改为 `backend = "gloo" if os.name == "nt" or not torch.cuda.is_available() else "gloo"`,后可运行

**Comment by moyutegong** [comment]
@AMD7900XTX a卡是不需要`if os.name == "nt" or not torch.cuda.is_available() else "nccl"`这段的，直接删除保留`backend = "gloo"`就行了。那个判断是给cuda走nccl用的
