### ISSUE TITLE
AttributeError: FunASRPipeline: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

### ISSUE THREAD

**Issue by Jun2Hou** [RVC-Boss/GPT-SoVITS#182]
2024-01-24 19:17:58,650 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-01-24 19:17:58,651 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-01-24 19:17:58,670 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2024-01-24 19:17:58,678 - modelscope - INFO - AST-Scanning the path "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
2024-01-24 19:18:07,792 - modelscope - INFO - Scanning done! A number of 956 components indexed or updated! Time consumed 9.113605737686157s
2024-01-24 19:18:07,813 - modelscope - INFO - Loading done! Current index file version is 1.11.1, with md5 6647d0be8013b72c9258053cf78c15b2 and a total number of 956 components indexed
2024-01-24 19:18:08,377 - modelscope - INFO - initiate model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-24 19:18:08,377 - modelscope - INFO - initiate model from location tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-24 19:18:08,377 - modelscope - INFO - initialize model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch

tables: 

-----------    ** dataset_classes **    --------------
| class name   | class location                               |
| AudioDataset | funasr/datasets/audio_datasets/datasets.py:7 |
-----------    ** index_ds_classes **    --------------
| class name   | class location                               |
| IndexDSJsonl | funasr/datasets/audio_datasets/index_ds.py:9 |
-----------    ** batch_sampler_classes **    --------------
| class name   | class location                               |
| BatchSampler | funasr/datasets/audio_datasets/samplers.py:7 |
-----------    ** frontend_classes **    --------------
| class name        | class location                       |
| WavFrontend       | funasr/frontends/wav_frontend.py:78  |
| WavFrontendOnline | funasr/frontends/wav_frontend.py:216 |
-----------    ** encoder_classes **    --------------
| class name            | class location                                        |
| BranchformerEncoder   | funasr/models/branchformer/encoder.py:294             |
| ConformerChunkEncoder | funasr/models/bat/conformer_chunk_encoder.py:315      |
| ConformerEncoder      | funasr/models/conformer/encoder.py:286                |
| DFSMN                 | funasr/models/fsmn_vad_streaming/encoder.py:232       |
| EBranchformerEncoder  | funasr/models/e_branchformer/encoder.py:177           |
| FSMN                  | funasr/models/fsmn_vad_streaming/encoder.py:161       |
| SANMEncoder           | funasr/models/sanm/encoder.py:161                     |
| SANMEncoderChunkOpt   | funasr/models/scama/encoder.py:162                    |
| SANMVadEncoder        | funasr/models/ct_transformer_streaming/encoder.py:148 |
| TransformerEncoder    | funasr/models/transformer/encoder.py:139              |
-----------    ** predictor_classes **    --------------
| class name     | class location                                     |
| CifPredictor   | funasr/models/paraformer/cif_predictor.py:15       |
| CifPredictorV2 | funasr/models/paraformer/cif_predictor.py:141      |
| CifPredictorV3 | funasr/models/bicif_paraformer/cif_predictor.py:95 |
-----------    ** model_classes **    --------------
| class name             | class location                                     |
| BiCifParaformer        | funasr/models/bicif_paraformer/model.py:37         |
| Branchformer           | funasr/models/branchformer/model.py:6              |
| CAMPPlus               | funasr/models/campplus/model.py:30                 |
| CTTransformer          | funasr/models/ct_transformer/model.py:30           |
| CTTransformerStreaming | funasr/models/ct_transformer_streaming/model.py:27 |
| Conformer              | funasr/models/conformer/model.py:8                 |
| ContextualParaformer   | funasr/models/contextual_paraformer/model.py:43    |
| EBranchformer          | funasr/models/e_branchformer/model.py:6            |
| Emotion2vec            | funasr/models/emotion2vec/model.py:34              |
| FsmnVADStreaming       | funasr/models/fsmn_vad_streaming/model.py:267      |
| MonotonicAligner       | funasr/models/monotonic_aligner/model.py:24        |
| Paraformer             | funasr/models/paraformer/model.py:26               |
| ParaformerStreaming    | funasr/models/paraformer_streaming/model.py:37     |
| SANM                   | funasr/models/sanm/model.py:13                     |
| SCAMA                  | funasr/models/scama/model.py:38                    |
| SeacoParaformer        | funasr/models/seaco_paraformer/model.py:45         |
| Transformer            | funasr/models/transformer/model.py:20              |
| UniASR                 | funasr/models/uniasr/model.py:25                   |
-----------    ** decoder_classes **    --------------
| class name                                 | class location                                     |
| ContextualParaformerDecoder                | funasr/models/contextual_paraformer/decoder.py:103 |
| DynamicConvolution2DTransformerDecoder     | funasr/models/transformer/decoder.py:588           |
| DynamicConvolutionTransformerDecoder       | funasr/models/transformer/decoder.py:527           |
| FsmnDecoder                                | funasr/models/sanm/decoder.py:198                  |
| FsmnDecoderSCAMAOpt                        | funasr/models/scama/decoder.py:197                 |
| LightweightConvolution2DTransformerDecoder | funasr/models/transformer/decoder.py:465           |
| LightweightConvolutionTransformerDecoder   | funasr/models/transformer/decoder.py:404           |
| ParaformerSANDecoder                       | funasr/models/paraformer/decoder.py:529            |
| ParaformerSANMDecoder                      | funasr/models/paraformer/decoder.py:204            |
| TransformerDecoder                         | funasr/models/transformer/decoder.py:355           |
-----------    ** normalize_classes **    --------------
| class name   | class location                             |
| GlobalMVN    | funasr/models/normalize/global_mvn.py:11   |
| UtteranceMVN | funasr/models/normalize/utterance_mvn.py:8 |
-----------    ** specaug_classes **    --------------
| class name | class location                       |
| SpecAug    | funasr/models/specaug/specaug.py:14  |
| SpecAugLFR | funasr/models/specaug/specaug.py:104 |
-----------    ** tokenizer_classes **    --------------
| class name              | class location                                 |
| CharTokenizer           | funasr/tokenizer/char_tokenizer.py:10          |
| SentencepiecesTokenizer | funasr/tokenizer/sentencepiece_tokenizer.py:11 |

Traceback (most recent call last):
  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/audio/funasr/model.py", line 55, in __init__
    self.model = AutoModel(model=model_dir, **kwargs)

  File "/root/anaconda3/envs/bs/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 93, in __init__
    model, kwargs = self.build_model(**kwargs)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 163, in build_model
    kwargs["token_list"] = tokenizer.token_list

AttributeError: 'CharTokenizer' object has no attribute 'token_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 62, in __init__
    super().__init__(model=model, **kwargs)
  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/aaa/GPT-SoVITS/tools/damo_asr/cmd-asr.py", line 16, in <module>
    inference_pipeline = pipeline(

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(

  File "/root/anaconda3/envs/b/lib/python3.11/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: FunASRPipeline: GenericFunASR: 'CharTokenizer' object has no attribute 'token_list'

**Comment by LauraGPT** [comment]
Solution : https://github.com/RVC-Boss/GPT-SoVITS/issues/194#issuecomment-1910205929

**Comment by jackywongboy** [comment]
Hi, can u fix the problem? I am facing the same issues but no hope, i change the code in cmd_asr.py still dosen't work.

**Comment by LauraGPT** [comment]
> Hi, can u fix the problem? I am facing the same issues but no hope, i change the code in cmd_asr.py still dosen't work.

1. delete the model
2. pip install -U funasr
3. try it again
