### ISSUE TITLE
关于打标环节的PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by qiaokelihahaj** [RVC-Boss/GPT-SoVITS#1824]
如下
Traceback (most recent call last):
  File "C:\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "C:\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "C:\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "C:\GPT-SoVITS-beta0706\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\hahaj\\Desktop\\biao'
管理员也不好使

**Comment by qiaokelihahaj** [comment]
没事了，我的问题

**Comment by CDKhsjsbbs** [comment]
你的是什么问题啊？
