### ISSUE TITLE
小问题求解决

### ISSUE THREAD

**Issue by AX686XXX** [RVC-Boss/GPT-SoVITS#188]

**Comment by AX686XXX** [comment]
"F:\sovi2\GPT-SoVITS\beta\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"F:\sovi2\GPT-SoVITS\beta\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "F:\sovi2\GPT-SoVITS\beta\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: 'F:\\sovi2\\GPT-SoVITS\\beta\\GPT-SoVITS-beta\\output\\slicer_opt.list"'
Traceback (most recent call last):
  File "F:\sovi2\GPT-SoVITS\beta\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: 'F:\\sovi2\\GPT-SoVITS\\beta\\GPT-SoVITS-beta\\output\\slicer_opt.list"'
Traceback (most recent call last):
  File "F:\sovi2\GPT-SoVITS\beta\GPT-SoVITS-beta\webui.py", line 515, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/huaqiai/2-name2text-0.txt'
ERROR: The process "432" not found.
ERROR: The process "3584" not found.
