### ISSUE TITLE
大佬们，在文本获取这一步失败了，该如何解决啊

### ISSUE THREAD

**Issue by Anh0923** [RVC-Boss/GPT-SoVITS#1886]
Traceback (most recent call last):
  File "E:\AI cover\GPT-SoVITS-v2-240821\runtime\lib\site-packages\g2pk2\g2pk2.py", line 88, in get_mecab
    return m.Mecab()
  File "E:\AI cover\GPT-SoVITS-v2-240821\runtime\lib\site-packages\eunjeon\_mecab.py", line 106, in __init__
    raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
Exception: The MeCab dictionary does not exist at "E:\AI cover\GPT-SoVITS-v2-240821\runtime\Lib\site-packages\eunjeon\data\mecabrc". Is the dictionary correctly installed?
You can also try entering the dictionary path when initializing the Mecab class: "Mecab('/some/dic/path')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI cover\GPT-SoVITS-v2-240821\GPT_SoVITS\prepare_datasets\1-get-text.py", line 92, in process
    phones, word2ph, norm_text = clean_text(
  File "E:\AI cover\GPT-SoVITS-v2-240821\GPT_SoVITS\text\cleaner.py", line 36, in clean_text
    language_module = __import__("text."+language_module_map[language],fromlist=[language_module_map[language]])
  File "E:\AI cover\GPT-SoVITS-v2-240821\GPT_SoVITS\text\korean.py", line 226, in <module>
    _g2p=G2p()
  File "E:\AI cover\GPT-SoVITS-v2-240821\runtime\lib\site-packages\g2pk2\g2pk2.py", line 30, in __init__
    self.mecab = self.get_mecab()
  File "E:\AI cover\GPT-SoVITS-v2-240821\runtime\lib\site-packages\g2pk2\g2pk2.py", line 90, in get_mecab
    raise print(f'you have to install eunjeon. "pip install eunjeon"')
TypeError: exceptions must derive from BaseException

**Comment by Anh0923** [comment]
> 删掉路径里的空格

文件路径里吗？用的是打标完自动填充的

**Comment by Anh0923** [comment]
已解决，换了一位大佬的整合包下载
