### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by xiujiePei** [RVC-Boss/GPT-SoVITS#1891]
Detailed problem description is as follows

Traceback (most recent call last):
  File "/Users/peixiujie/Desktop/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 31, in uvr
    pre_fun = func(
  File "/Users/peixiujie/Desktop/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/vr.py", line 33, in __init__
    cpk = torch.load(model_path, map_location="cpu")
  File "/Users/peixiujie/Library/Python/3.9/lib/python/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/peixiujie/Library/Python/3.9/lib/python/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

how to do

**Comment by XXXXRT666** [comment]
Wrong Repo

**Comment by RVC-Boss** [comment]
↑ is right.
