### ISSUE TITLE
GPT训练报错，未生成模型文件

### ISSUE THREAD

**Issue by xiaoowen** [RVC-Boss/GPT-SoVITS#1893]
GPU: 
  - nividia L20
 
conda:
```txt
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.15.2                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
altair                    5.4.1                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
aom                       3.6.0                h6a678d5_0  
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
av                        12.3.0                   pypi_0    pypi
binutils_impl_linux-64    2.40                 ha1999f0_7    conda-forge
blas                      1.0                         mkl  
brotli                    1.0.9                    pypi_0    pypi
brotli-python             1.0.9           py310h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.7.2             h06a4308_0  
cairo                     1.16.0               hb05425b_5  
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.17.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7                    pypi_0    pypi
cmake                     3.26.4               h96355d8_0  
cn2an                     0.5.22                   pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              43.0.0                   pypi_0    pypi
ctranslate2               4.3.1                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.6                          3    nvidia
cudnn                     8.9.2.26               cuda12_0  
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.21.0                   pypi_0    pypi
dav1d                     1.2.1                h5eee18b_0  
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
editdistance              0.8.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
expat                     2.6.2                h6a678d5_0  
fastapi                   0.112.2                  pypi_0    pypi
faster-whisper            1.0.3                    pypi_0    pypi
ffmpeg                    6.1.1                h4c62175_0  
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
funasr                    1.0.27                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
g2p-en                    2.1.0                    pypi_0    pypi
g2pk2                     0.0.3                    pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
gcc                       14.1.0               h6f9ffa1_1    conda-forge
gcc_impl_linux-64         14.1.0               h3c94d91_1    conda-forge
giflib                    5.2.1                h5eee18b_3  
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2                    pypi_0    pypi
gradio                    4.24.0                   pypi_0    pypi
gradio-client             0.14.0                   pypi_0    pypi
graphite2                 1.3.14               h295c915_1  
grpcio                    1.66.1                   pypi_0    pypi
gxx                       14.1.0               h6f9ffa1_1    conda-forge
gxx_impl_linux-64         14.1.0               h8d00ecb_1    conda-forge
h11                       0.14.0                   pypi_0    pypi
harfbuzz                  4.3.0                hf52aaf7_2  
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.24.6                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
icu                       73.1                 h6a678d5_0  
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
importlib-resources       6.4.4                    pypi_0    pypi
inflect                   7.3.1                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jaconv                    0.4.0                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jieba-fast                0.53                     pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_3  
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
kernel-headers_linux-64   2.6.32              he073ed8_17    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
ko-pron                   1.3                      pypi_0    pypi
krb5                      1.20.1               h143b758_1  
lame                      3.100                h7b6447c_0  
langsegment               0.3.5                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
leptonica                 1.82.0               h42c8aad_2  
lerc                      3.0                  h295c915_0  
libarchive                3.6.2                h6ac8c49_3  
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.68                     0    nvidia
libcurl                   8.9.1                h251f7ec_0  
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_1  
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     14.1.0             h5d3d1c9_101    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libglib                   2.78.4               hdc74915_0  
libgomp                   14.1.0               h77fa898_1    conda-forge
libiconv                  1.16                 h5eee18b_3  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnghttp2                1.57.0               h2d74bed_0  
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libogg                    1.3.5                h27cfd23_1  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
librosa                   0.9.2                    pypi_0    pypi
libsanitizer              14.1.0               hcba0ae0_1    conda-forge
libssh2                   1.11.0               h251f7ec_0  
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-64  14.1.0             h5d3d1c9_101    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libtheora                 1.1.1                h7f8727e_3  
libtiff                   4.5.1                h6a678d5_0  
libuuid                   1.41.5               h5eee18b_0  
libuv                     1.48.0               h5eee18b_0  
libvorbis                 1.3.7                h7b6447c_0  
libvpx                    1.13.1               h6a678d5_0  
libwebp                   1.3.2                h11a3e52_0  
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.10.4               hfdd30dd_2  
lightning-utilities       0.11.7                   pypi_0    pypi
llvm-openmp               14.0.6               h9e868ea_0  
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mkl-fft                   1.3.8                    pypi_0    pypi
mkl-random                1.2.4                    pypi_0    pypi
mkl-service               2.4.0                    pypi_0    pypi
mkl_fft                   1.3.8           py310h5eee18b_0  
mkl_random                1.2.4           py310hdb19cb5_0  
modelscope                1.10.0                   pypi_0    pypi
more-itertools            10.4.0                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
narwhals                  1.6.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.3                      pypi_0    pypi
nltk                      3.9.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.4                   pypi_0    pypi
numpy-base                1.26.4          py310hb5e798b_0  
omegaconf                 2.3.0                    pypi_0    pypi
onnxruntime               1.19.0                   pypi_0    pypi
onnxruntime-gpu           1.19.0                   pypi_0    pypi
openai-whisper            20231117                 pypi_0    pypi
opencc                    1.1.1                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.5.2                he7f1fd0_0  
openssl                   3.0.14               h5eee18b_0  
orjson                    3.10.7                   pypi_0    pypi
oss2                      2.19.0                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pcre2                     10.42                hebb0a14_1  
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2                     pypi_0    pypi
pixman                    0.40.0               h7f8727e_1  
platformdirs              4.2.2                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
proces                    0.1.7                    pypi_0    pypi
protobuf                  5.28.0                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
py3langid                 0.2.2                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyjyutping                1.0.0                    pypi_0    pypi
pynndescent               0.5.13                   pypi_0    pypi
pyopenjtalk               0.3.4                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pypinyin                  0.52.0                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.14              h955ad1f_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-mecab-ko           1.3.7                    pypi_0    pypi
python-mecab-ko-dic       2.1.1.post2              pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytorch                   2.1.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-lightning         2.4.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
resampy                   0.4.3                    pypi_0    pypi
rhash                     1.4.3                hdbd6064_0  
rich                      13.8.0                   pypi_0    pypi
rotary-embedding-torch    0.7.0                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
ruff                      0.6.3                    pypi_0    pypi
safetensors               0.4.4                    pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                72.1.0                   pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
simplejson                3.19.3                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.38.4                   pypi_0    pypi
sympy                     1.13.2                   pypi_0    pypi
sysroot_linux-64          2.12                he073ed8_17    conda-forge
tbb                       2021.8.0             hdb19cb5_0  
tensorboard               2.17.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tesseract                 5.2.0                h6a678d5_0  
threadpoolctl             3.5.0                    pypi_0    pypi
tiktoken                  0.7.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.19.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.1.1                    pypi_0    pypi
torch-complex             0.4.4                    pypi_0    pypi
torchaudio                2.1.1                    pypi_0    pypi
torchmetrics              1.4.1                    pypi_0    pypi
torchtriton               2.1.0                     py310    pytorch
torchvision               0.16.1                   pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.44.2                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typeguard                 4.3.0                    pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
typing_extensions         4.11.0          py310h06a4308_0  
tzdata                    2024.1                   pypi_0    pypi
umap-learn                0.5.6                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
uvicorn                   0.30.6                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.43.0                   pypi_0    pypi
wordsegment               1.3.1                    pypi_0    pypi
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.7                    pypi_0    pypi
zipp                      3.20.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2 
```

log:

```txt
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                 | Params | Mode 
-------------------------------------------------------
0 | model | Text2SemanticDecoder | 77.6 M | train
-------------------------------------------------------
77.6 M    Trainable params
0         Non-trainable params
77.6 M    Total params
310.426   Total estimated model params size (MB)
257       Modules in train mode
0         Modules in eval mode
<All keys matched successfully>
ckpt_path: None
semantic_data_len: 88
phoneme_data_len: 88
                                            item_name                                     semantic_audio
0   taiwanese_accent_female.mp3_0000029440_0000232...  457 114 700 412 792 677 650 438 685 905 316 53...
1   taiwanese_accent_female.mp3_0000572160_0000754...  14 574 729 175 1009 557 1006 949 514 166 6 867...
2   taiwanese_accent_female.mp3_0000926400_0001064...  913 570 14 775 910 949 338 930 160 721 295 763...
3   taiwanese_accent_female.mp3_0001336000_0001528...  208 162 609 171 594 514 475 835 925 996 398 64...
4   taiwanese_accent_female.mp3_0001671040_0001861...  208 885 196 292 56 710 36 48 378 697 625 783 5...
..                                                ...                                                ...
83  taiwanese_accent_female.mp3_0014081920_0014271...  714 28 242 3 817 418 116 736 783 705 742 284 7...
84  taiwanese_accent_female.mp3_0014426880_0014615...  913 140 117 826 836 994 650 33 905 362 670 403...
85  taiwanese_accent_female.mp3_0014754240_0014892...  913 17 594 514 4 133 251 870 578 496 821 867 6...
86  taiwanese_accent_female.mp3_0015024320_0015142...  214 256 807 844 278 272 278 177 696 14 714 600...
87  taiwanese_accent_female.mp3_0015301440_0015369...  14 132 783 124 588 510 831 111 300 487 446 525...

[88 rows x 2 columns]
dataset.__len__(): 176
/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (16) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|          | 0/16 [00:00<?, ?it/s] Traceback (most recent call last):
  File "/mnt/datadisk0/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 183, in <module>
    main(args)
  File "/mnt/datadisk0/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 159, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 539, in fit
    call._call_and_handle_interrupt(
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 575, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1026, in _run_stage
    self.fit_loop.run()
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
    self.advance()
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 455, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 150, in run
    self.advance(data_fetcher)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 322, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 94, in run
    self.advance(kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 114, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 323, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 641, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 634, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/mnt/datadisk0/GPT-SoVITS/GPT_SoVITS/AR/models/t2s_lightning_module.py", line 39, in training_step
    loss, acc = forward(
  File "/mnt/datadisk0/GPT-SoVITS/GPT_SoVITS/AR/models/t2s_model.py", line 428, in forward
    acc = self.ar_accuracy_metric(logits.permute(0, 2, 1).detach(), targets).item()
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/metric.py", line 316, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/metric.py", line 385, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/metric.py", line 560, in wrapped_func
    raise err
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/metric.py", line 550, in wrapped_func
    update(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/classification/stat_scores.py", line 343, in update
    tp, fp, tn, fn = _multiclass_stat_scores_update(
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/functional/classification/stat_scores.py", line 398, in _multiclass_stat_scores_update
    preds_oh = _refine_preds_oh(preds, preds_oh, target, top_k)
  File "/home/ubuntu/miniconda3/envs/gpt-sovits/lib/python3.10/site-packages/torchmetrics/functional/classification/stat_scores.py", line 364, in _refine_preds_oh
    return torch.zeros_like(preds_oh, dtype=torch.int32).scatter_(-1, result.unsqueeze(1).unsqueeze(1), 1)
RuntimeError: Index tensor must have the same number of dimensions as self tensor
Epoch 0:   0%|          | 0/16 [00:01<?, ?it/s]

```

已经尝试过降低 batch_size，依然报错。

大佬们，该如何解决啊，是硬件问题么？

**Comment by benzfy** [comment]
我刚遇到这个问题...试了一下解决了。
方法是：
pip install torchmetrics==1.5

**Comment by xiaoowen** [comment]
> 我刚遇到这个问题...试了一下解决了。 方法是： pip install torchmetrics==1.5

@benzfy 感谢，已解决

**Comment by A8888901F** [comment]
@xiaoowen 我也遇到这个问题，答案没有看懂，请问是如何操作的啊？谢谢！

**Comment by xiaoowen** [comment]
> @xiaoowen 我也遇到这个问题，答案没有看懂，请问是如何操作的啊？谢谢！

执行命令 `pip install torchmetrics==1.5` ，安装这个包，然后重启服务

**Comment by A8888901F** [comment]
@xiaoowen 厉害了我的哥！完全可以的，已解决哦. 感谢😁
