### ISSUE TITLE
启用api.py报错

### ISSUE THREAD

**Issue by Kimdow220807** [RVC-Boss/GPT-SoVITS#190]
D:\AIGC\GPT-SoVITS>D:\AIGC\GPT-SoVITS\runtime\python.exe -m uvicorn api:app --host 127.0.0.1 --port 9880 --reload
INFO:     Will watch for changes in these directories: ['D:\\AIGC\\GPT-SoVITS']
INFO:     Uvicorn running on http://127.0.0.1:9880 (Press CTRL+C to quit)
INFO:     Started reloader process [2252] using StatReload
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\AIGC\GPT-SoVITS\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
usage: __main__.py [-h] [-s SOVITS_PATH] [-g GPT_PATH] [-dr DEFAULT_REFER_PATH] [-dt DEFAULT_REFER_TEXT]
                   [-dl DEFAULT_REFER_LANGUAGE] [-d DEVICE] [-p PORT] [-a BIND_ADDR] [-fp] [-hp] [-hb HUBERT_PATH]
                   [-b BERT_PATH]
__main__.py: error: unrecognized arguments: api:app --host 127.0.0.1 --reload

**Comment by Miuzarte** [comment]
`python .\api.py -p "9880" -a "127.0.0.1" -dr "123.wav" -dt "一二三" -dl "中文"`

直接执行就好了

**Comment by Kimdow220807** [comment]
> `python .\api.py -p "9880" -a "127.0.0.1" -dr "123.wav" -dt "一二三" -dl "中文"`
> 
> 直接执行就好了

理解了，不过FFMPEG还是报错，没影响的吗？
报错内容：
Traceback (most recent call last):
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.

**Comment by Miuzarte** [comment]
> > `python .\api.py -p "9880" -a "127.0.0.1" -dr "123.wav" -dt "一二三" -dl "中文"`
> > 直接执行就好了
> 
> 理解了，不过FFMPEG还是报错，没影响的吗？ 报错内容： 
```
Traceback (most recent call last): File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio_extension__init__.py", line 67, in _init_ffmpeg() File "D:\AIGC\GPT-SoVITS\runtime\lib\site-packages\torchaudio_extension\utils.py", line 87, in _init_ffmpeg raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err ImportError: FFmpeg libraries are not found. Please install FFmpeg.
```

直接试试吧，确定path能调用到ffmpeg吗

**Comment by dicarne** [comment]
我这FFMPEG也报错，但奇怪的是一切运行正常

**Comment by RVC-Boss** [comment]
api代码已更新
