### ISSUE TITLE
ASR运行过程出现numpy相关报错

### ISSUE THREAD

**Issue by Chlitsec** [RVC-Boss/GPT-SoVITS#195]
运行github提供的整合包后，ASR过程出现报错，请大佬指点，谢谢

2024-01-25 16:45:19,811 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-01-25 16:45:19,816 - modelscope - INFO - Loading ast index from C:\Users\Luis\.cache\modelscope\ast_indexer
2024-01-25 16:45:19,920 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 dc0c9ee702463555275a41f8a2fb65fe and a total number of 946 components indexed
2024-01-25 16:45:21,502 - modelscope - INFO - initiate model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-25 16:45:21,503 - modelscope - INFO - initiate model from location tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-25 16:45:21,504 - modelscope - INFO - initialize model from tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-25 16:45:21,509 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-25 16:45:21,509 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-25 16:45:21,509 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2024-01-25 16:45:21,509 - modelscope - WARNING - No preprocessor key ('generic-asr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-01-25 16:45:25,948 - modelscope - WARNING - Model revision not specified, use revision: v1.2.1
2024-01-25 16:45:26,249 - modelscope - INFO - loading vad model from tools/damo_asr/models/speech_fsmn_vad_zh-cn-16k-common-pytorch ...
2024-01-25 16:45:26,252 - modelscope - INFO - loading punctuation model from tools/damo_asr/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch ...
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
If you want use h5py dataset, please pip install h5py, and try it again
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\modelscope\pipelines\audio\asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\funasr\bin\asr_inference_launch.py", line 59, in <module>
    from funasr.utils.cluster_backend import ClusterBackend
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\funasr\utils\cluster_backend.py", line 5, in <module>    import hdbscan
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\hdbscan\__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\hdbscan\hdbscan_.py", line 20, in <module>
    from ._hdbscan_linkage import (
  File "hdbscan\_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
  File "hdbscan\dist_metrics.pyx", line 13, in init hdbscan.dist_metrics
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\GPT-SoVITS\tools\damo_asr\cmd-asr.py", line 16, in <module>
    inference_pipeline = pipeline(
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Users\XXX\Desktop\GPT-SoVITS\runtime\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: AutomaticSpeechRecognitionPipeline: numpy.core.multiarray failed to import

**Comment by baicai-1145** [comment]
runtime\python -m pip install funasr==0.8.7
runtime\python -m pip install funasr==1.0.0
