### ISSUE TITLE
UVR处理UI输入路径只能使用绝对路径，相对路径会报错

### ISSUE THREAD

**Issue by a-cold-bird** [RVC-Boss/GPT-SoVITS#201]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/librosa/core/audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/root/miniconda3/lib/python3.10/site-packages/librosa/core/audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "/root/miniconda3/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/root/miniconda3/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'input/input/vocal_sera.flac': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/workdir/GPT-SoVITS/tools/uvr5/webui.py", line 58, in uvr
    y, sr = librosa.load(inp_path, sr=None)
  File "/root/miniconda3/lib/python3.10/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/librosa/core/audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/root/miniconda3/lib/python3.10/site-packages/librosa/core/audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "/root/miniconda3/lib/python3.10/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/root/miniconda3/lib/python3.10/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'input/input/vocal_sera.flac'

**Comment by a-cold-bird** [comment]
输入待处理音频文件夹路径我填写的input
