### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by ahkimkoo** [RVC-Boss/GPT-SoVITS#210]
Traceback (most recent call last):
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 199, in get_tts_wav
    bert1 = get_bert_feature(norm_text1, word2ph1).to(device)
  File "/root/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 62, in get_bert_feature
    phone_level_feature = torch.cat(phone_level_feature, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensor

**Comment by RVC-Boss** [comment]
xxx
xxx
that's ok


xxx

xxx
not ok

I will fix it later.

**Comment by RVC-Boss** [comment]
> xxx xxx that's ok
> 
> xxx
> 
> xxx not ok
> 
> I will fix it later.

And some other situations such as:
text of A language, but you choose B language
or
null of text
