### ISSUE TITLE
为啥微调SoVITs后cmd中报错

### ISSUE THREAD

**Issue by xu0613** [RVC-Boss/GPT-SoVITS#221]
报错如下：
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 566, in <module>
    main()
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 53, in main
    mp.spawn(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 236, in run
    train_and_evaluate(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 352, in train_and_evaluate
    scaler.step(optim_d)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 370, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 290, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\adamw.py", line 171, in step
    adamw(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\adamw.py", line 321, in adamw
    func(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\torch\optim\adamw.py", line 566, in _multi_tensor_adamw
    denom = torch._foreach_add(exp_avg_sq_sqrt, eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 2.50 GiB already allocated; 643.00 MiB free; 2.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by RVC-Boss** [comment]
显存不够：降低batch_size

**Comment by xu0613** [comment]
感谢
