### ISSUE TITLE
端口报错问题

### ISSUE THREAD

**Issue by qwqpap** [RVC-Boss/GPT-SoVITS#242]
windows11 py3.9
在使用时直接报错端口占用，但是通过powershell查看并没有占用
往大佬解答
以下为报错信息
`ERROR:    [Errno 10048] error while attempting to bind on address ('0.0.0.0', 9874): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
Traceback (most recent call last):
  File "C:\Users\m1573\PycharmProjects\GPT-SoVITS\webui.py", line 769, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
  File "C:\Users\m1573\.conda\envs\GPTSoVits\lib\site-packages\gradio\blocks.py", line 1840, in launch
    ) = networking.start_server(
  File "C:\Users\m1573\.conda\envs\GPTSoVits\lib\site-packages\gradio\networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 9874-9874. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.`
以下为所使用的环境
```
(GPTSoVits) PS C:\Users\*****\PycharmProjects\GPT-SoVITS> conda list
# packages in environment at C:\Users\*****\.conda\envs\GPTSoVits:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.14.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
anyio                     4.2.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2023.12.12           haa95532_0
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cn2an                     0.5.22                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.1                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.8                    pypi_0    pypi
datasets                  2.16.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
editdistance              0.6.2                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fastapi                   0.109.0                  pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
funasr                    0.8.7                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
g2p-en                    2.1.0                    pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
google-auth               2.27.0                   pypi_0    pypi
google-auth-oauthlib      1.2.0                    pypi_0    pypi
gradio                    3.38.0                   pypi_0    pypi
gradio-client             0.8.1                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hdbscan                   0.8.33           py39hd88c2e4_4    conda-forge
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
huggingface-hub           0.20.3                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
inflect                   7.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jieba-fast                0.53                     pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.2.0            py39haa95532_0
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
librosa                   0.9.2                    pypi_0    pypi
lightning-utilities       0.10.1                   pypi_0    pypi
linkify-it-py             2.0.2                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
markdown                  3.5.2                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.4                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py39h2bbff1b_1
mkl_fft                   1.3.8            py39h2bbff1b_0
mkl_random                1.2.4            py39h59b6b97_0
modelscope                1.10.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
numpy-base                1.26.3           py39h65a83cf_0
oauthlib                  3.2.2                    pypi_0    pypi
onnxruntime               1.16.3                   pypi_0    pypi
openjtalk                 0.3.0.dev3               pypi_0    pypi
openssl                   3.0.12               h2bbff1b_0
orjson                    3.9.12                   pypi_0    pypi
oss2                      2.18.4                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.2.0                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py39haa95532_0
platformdirs              4.1.0                    pypi_0    pypi
pooch                     1.8.0                    pypi_0    pypi
proces                    0.1.7                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.5.3                    pypi_0    pypi
pydantic-core             2.14.6                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pypinyin                  0.50.0                   pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
python                    3.9.18               h1aa4202_0
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch-lightning         2.1.3                    pypi_0    pypi
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
referencing               0.32.1                   pypi_0    pypi
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resampy                   0.4.2                    pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.2                    pypi_0    pypi
scikit-learn              1.3.0            py39h4ed8f06_1
scipy                     1.11.4           py39h309d312_0
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.2.2           py39haa95532_0
simplejson                3.19.2                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
starlette                 0.35.1                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0
tokenizers                0.15.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     2.1.2+cu118              pypi_0    pypi
torch-complex             0.4.3                    pypi_0    pypi
torchaudio                2.1.2+cu118              pypi_0    pypi
torchmetrics              1.3.0.post0              pypi_0    pypi
torchvision               0.16.2+cu118             pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.37.1                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
ucrt                      10.0.20348.0         haa95532_0
umap                      0.1.1                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
uvicorn                   0.27.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39haa95532_0
xxhash                    3.4.1                    pypi_0    pypi
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
`
```

**Comment by qwqpap** [comment]
已解决，改一下config.py就可以了

**Comment by xfl888** [comment]
Try this:
net stop winnat
net start winnat
netsh interface ipv4 show excludedportrange protocol=tcp

make sure 9874/9873/9872/9871 is not in the exclusive list.

**Comment by Taoziyibeizhuce** [comment]
和你一样的问题，因为只是爱好并不是很了解相关问题，然后去知乎搜了一下，在任务管理器里面吧python的进程关掉在重新开就可以正常启动了
