### ISSUE TITLE
The "go webui. bat" in the integration package cannot run properly

### ISSUE THREAD

**Issue by a1123211** [RVC-Boss/GPT-SoVITS#252]
The "go webui. bat" in the integration package cannot run properly with the following error:
Runtime \ Python. exe webui.py
Traceback (most recent call last):
File "Z: \ GPT SoVITS \ webui. py", line 39, in<module>
Import graphic as gr
File "Z: \ GPT SoVITS \ runtime \ lib \ site packages \ graphic \ _ init__. py", line 3, in<module>
Import gradient.com components as components
File "Z: \ GPT SoVITS \ runtime \ lib \ site packages \ graphic \ components. py", line 34, in<module>
From graphic import media_ Data, processing_ Utils
File "Z: \ GPT SoVITS \ runtime \ lib \ site packages \ graphic \ processing_utils. py", line 18, in<module>
Import requests
File "C: \ Users \ admin \ AppData \ Roaming \ Python \ Python 39 \ site packages \ requests \ _init__. py", line 95, in<module>
From urllib3. contrib import pyopenssl
File "C: \ Users \ admin \ AppData \ Roaming \ Python \ Python 39 \ site packages \ urllib3 \ contrib \ pyopenssl. py", line 46, in<module>
Import OpenSSL SSL
File "C: \ Users \ admin \ AppData \ Roaming \ Python \ Python 39 \ site packages \ OpenSSL \ _ init__. py", line 8, in<module>
From OpenSSL import crypto, SSL
File "C: \ Users \ admin \ AppData \ Roaming \ Python \ Python 39 \ site packages \ OpenSSL \ crypto. py", line 1556, in<module>
Class X509StoreFlags (object):
File "C: \ Users \ admin \ AppData \ Roaming \ Python \ Python 39 \ site packages \ OpenSSL \ crypto. py", line 1577, in X509StoreFlags
CB_ ISSUER_ CHECK=_ Lib X509_ V_ FLAG_ CB_ ISSUER_ CHECK
AttributeError: module 'lib' has no attribute 'X509_ V_ FLAG_ CB_ ISSUER_ CHECK

**Comment by RVC-Boss** [comment]
更新到最新的代码再试试
