### ISSUE TITLE
在运行一键三联后失败，不知道是什么原因

### ISSUE THREAD

**Issue by JYC1012** [RVC-Boss/GPT-SoVITS#256]
我是在服务器上运行的
"/home/jingyc/.conda/envs/gptsovits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/home/jingyc/.conda/envs/gptsovits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 533, in load_state_dict
    return torch.load(
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/torch/serialization.py", line 814, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data2/jingyc/project1/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 57, in <module>
    bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir)
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3527, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 543, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
Traceback (most recent call last):
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 533, in load_state_dict
    return torch.load(
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/torch/serialization.py", line 814, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data2/jingyc/project1/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 57, in <module>
    bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir)
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3527, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 543, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
Traceback (most recent call last):
  File "/data2/jingyc/project1/GPT-SoVITS/webui.py", line 531, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'

**Comment by ZilongYang** [comment]
我的也是在一键三联后失败，不过是在m1上：
```
"/Users/zilong/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
Traceback (most recent call last):
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    resolved_file = hf_hub_download(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    validate_repo_id(arg_value)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zilong/zWork/py/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zilong/zWork/py/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 450, in cached_file
    resolved_config_file = cached_file(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Traceback (most recent call last):
  File "/Users/zilong/zWork/py/GPT-SoVITS/webui.py", line 531, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/zl/2-name2text-0.txt'
```

**Comment by nephilimbin** [comment]
Reason：Because loss a file of 'cmudict' from nltk
Resolved：create a temp.py in root dir. and execute the following codes:
import nltk
nltk.download('cmudict')

@RVC-Boss Please fix this issue from '.\webui.py'

**Comment by AX686XXX** [comment]
> 原因：因为从 nltk 丢失了 'cmudict' 文件 解决：在根目录中创建一个 temp.py 并执行以下代码： import nltk nltk.download（'cmudict'）
> 
> 请从“.\webui.py”解决此问题

谢谢我解决了

**Comment by ysujiang** [comment]
> 我是在服务器上运行的
> 
> "/home/jingyc/.conda/envs/gptsovits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py "/home/jingyc/.conda/envs/gptsovits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py Traceback (most recent call last): File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 533, in load_state_dict return torch.load( File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/torch/serialization.py", line 814, in load raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None _pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data2/jingyc/project1/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 57, in bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir) File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained return model_class.from_pretrained( File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3527, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 543, in load_state_dict raise OSError( OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned. Traceback (most recent call last): File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 533, in load_state_dict return torch.load( File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/torch/serialization.py", line 814, in load raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None _pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data2/jingyc/project1/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 57, in bert_model = AutoModelForMaskedLM.from_pretrained(bert_pretrained_dir) File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained return model_class.from_pretrained( File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3527, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "/home/jingyc/.conda/envs/gptsovits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 543, in load_state_dict raise OSError( OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned. Traceback (most recent call last): File "/data2/jingyc/project1/GPT-SoVITS/webui.py", line 531, in open1abc with open(txt_path, "r",encoding="utf8") as f: FileNotFoundError: [Errno 2] No such file or directory: 'logs/test01/2-name2text-0.txt'

我也遇到了同样的问题，请问解决了吗

**Comment by sdrz001** [comment]
我也是啊 你们解决了吗

**Comment by XXXXRT666** [comment]
下载问题

**Comment by RVC-Boss** [comment]
楼上正解，nltk在墙外，下载需要自行解决

**Comment by XXXXRT666** [comment]
是pretrained models没下全
