### ISSUE TITLE
ffmpeg error again

### ISSUE THREAD

**Issue by Jeru2023** [RVC-Boss/GPT-SoVITS#266]
ffmpeg 虽然在第一步切割文件slice中已经可以正常工作,但是在第二个tab一件三连中再次报错，更具体的说时在SSL提取时。

Traceback (most recent call last):
  File "D:\dev\replica\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 103, in <module>
    name2go(wav_name)
  File "D:\dev\replica\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 68, in name2go
    tmp_audio = load_audio(wav_path, 32000)
  File "D:\dev\replica\GPT-SoVITS\tools\my_utils.py", line 20, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

--------

D:\dev\replica\GPT-SoVITS\input/4.wav|input|ZH|画面具有美感，开门见山不墨迹，核心是抓住前三秒，抓住用户注意力。 Traceback (most recent call last):
  File "D:\dev\replica\GPT-SoVITS\tools\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\conda_envs\replica\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/tools/my_utils.py
更新一下这个代码，先测试一下是否能找到对应的路径呢？

**Comment by LeoHsu0802** [comment]
遇到了一樣的問題

**Comment by zhuangzhuangliu2345** [comment]
一般按照list的路径找不到wav会出现这样的提示，可以先看下路径。

**Comment by Jeru2023** [comment]
> 遇到了一樣的問題

我确实还是路径问题，这里有两个参数要填写，一个是list，另一个应该是最开始的原始音频，我第二个的路径填错了。

**Comment by panxin801** [comment]
> > 遇到了一樣的問題
> 
> 我确实还是路径问题，这里有两个参数要填写，一个是list，另一个应该是最开始的原始音频，我第二个的路径填错了。

训练集音频目录填写音频wav 文件所在目录就行。我是这样就ok 了
