### ISSUE TITLE
一键三连报错

### ISSUE THREAD

**Issue by Watsonwater** [RVC-Boss/GPT-SoVITS#270]
"D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
  File "D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "os.py", line 684, in __setitem__
  File "os.py", line 684, in __setitem__
  File "os.py", line 742, in check_str
  File "os.py", line 742, in check_str
TypeError: str expected, not NoneType
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\webui.py", line 533, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/QiuQiu/2-name2text-0.txt'
错误: 没有找到进程 "22816"。
错误: 没有找到进程 "13856"。

非常感谢大佬orz

**Comment by yang208115** [comment]
我也是
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/132762661/f21f9830-7462-4464-a925-79eaf9cf75ca)

**Comment by Polaristime2026** [comment]
我也是大家解决了吗？
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/76163264/45c54593-0d41-4b97-9c44-fce75c7e3663)

**Comment by yang208115** [comment]
1我解决，但2和3有报错l

**Comment by yang208115** [comment]
1我解决了，但2和3又报错了

**Comment by yang208115** [comment]
1的解决办法：
去https://huggingface.co/spaces/XzJosh/Taffy-GPT-SoVITS/tree/main/pretrained_models/chinese-roberta-wwm-ext-large下载模型
放在
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/132762661/a49c4a63-2499-4886-ae4c-6a69390c127b)

**Comment by Polaristime2026** [comment]
谢谢我去试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RVC-Boss/GPT-SoVITS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RVC-Boss/GPT-SoVITS] 一键三连报错 (Issue #270)





 
1的解决办法：
 去https://huggingface.co/spaces/XzJosh/Taffy-GPT-SoVITS/tree/main/pretrained_models/chinese-roberta-wwm-ext-large下载模型
 放在
 image.png (view on web)

**Comment by yoko-penta** [comment]
这个我解决了，你看你截图报错的这一段：
```
os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
File "os.py", line 684, in setitem
File "os.py", line 684, in setitem
File "os.py", line 742, in check_str
File "os.py", line 742, in check_str
TypeError: str expected, not NoneType
TypeError: str expected, not NoneType
```

这是一段获取显卡id的报错，表示你`os.environ.get("_CUDA_VISIBLE_DEVICES")`没有获取到显卡列表，可以找到**“D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\GPT_SoVITS\prepare_datasets\1-get-text.py**”这个文件，把这一行的`os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")`改成`os.environ["CUDA_VISIBLE_DEVICES"] = ’0‘`，代表你指定了代号为0的主显卡。后面应该还会遇到这样的错误，按照这个办法改一下试试吧。前提是你有显卡，并且cuda和torch都是对应版本且可用的。我的卡：quadro rtx 6000。仅供参考。

**Comment by Polaristime2026** [comment]
不好意思，我刚刚看到邮件。好的谢谢大佬，我去试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RVC-Boss/GPT-SoVITS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月31日(星期三) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RVC-Boss/GPT-SoVITS] 一键三连报错 (Issue #270)





 
这个我解决了，你看你截图报错的这一段：
 os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES") os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES") File "os.py", line 684, in setitem File "os.py", line 684, in setitem File "os.py", line 742, in check_str File "os.py", line 742, in check_str TypeError: str expected, not NoneType TypeError: str expected, not NoneType  
这是一段获取显卡id的报错，表示你os.environ.get("_CUDA_VISIBLE_DEVICES")没有获取到显卡列表，可以找到**“D:\software\GPT-SoVITS-beta\GPT-SoVITS-beta0128\GPT_SoVITS\prepare_datasets\1-get-text.py**”这个文件，把这一行的os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")改成os.environ["CUDA_VISIBLE_DEVICES"] = ’0‘，代表你指定了代号为0的主显卡。后面应该还会遇到这样的错误，按照这个办法改一下试试吧。前提是你有显卡，并且cuda和torch都是对应版本且可用的。我的卡：quadro rtx 6000。仅供参考。

**Comment by Chenhaolon** [comment]
Traceback (most recent call last):
  File "E:\yuyin\GPT-SoVITS-beta0217fix2\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "E:\yuyin\GPT-SoVITS-beta0217fix2\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "E:\yuyin\GPT-SoVITS-beta0217fix2\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "E:\yuyin\GPT-SoVITS-beta0217fix2\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
PermissionError: [Errno 13] Permission denied: 'E:\\yuyin\\GPT-SoVITS-beta0217fix2\\output\\asr_opt'
大佬这个是啥情况

**Comment by yang208115** [comment]
以管理员身份运行go-webui.bat试试

**Comment by Polaristime2026** [comment]
好的謝謝大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月23日(星期天) 下午4:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RVC-Boss/GPT-SoVITS] 一键三连报错 (Issue #270)














 
以管理员身份运行go-webui.bat试试
