### ISSUE TITLE
中英混合bug 有点多

### ISSUE THREAD

**Issue by selfboot** [RVC-Boss/GPT-SoVITS#271]
1. 英文发音不对

> ChatGPT 告诉我，您的理解是正确的。当您使用指针对象时，您应该通过 uniqueptr 实例

分语音看起来没问题，但是 ChatGPT 发音好奇怪：

```
[]
['挡风玻璃大呢，意味着我们需要更多的关注眼前的道路，和即将到来的事物。']
['zh']
[]
['ChatGPT ', '告诉我，您的理解是正确的。当您使用指针对象时，您应该通过', ' uniqueptr ', '实例。']
['en', 'zh', 'en', 'zh']
```

2. 带下划线就直接转失败了。

<img width="1532" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/2769831/6b074017-9322-4165-b47f-7591e8dd8c6c">

```python
Traceback (most recent call last):
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/data/home/daemonzhao/miniconda3/envs/GPTSoVits11/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/data/home/daemonzhao/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 334, in get_tts_wav
    bert2 = nonen_get_bert_inf(text, text_language)
  File "/data/home/daemonzhao/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 259, in nonen_get_bert_inf
    bert = get_bert_inf(phones, word2ph, norm_text, lang)
  File "/data/home/daemonzhao/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 218, in get_bert_inf
    bert = get_bert_feature(norm_text, word2ph).to(device)
  File "/data/home/daemonzhao/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 89, in get_bert_feature
    phone_level_feature = torch.cat(phone_level_feature, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

**Comment by RVC-Boss** [comment]
下划线我们研究一下

**Comment by selfboot** [comment]
英文发音也是很奇怪，有的音根本就不对。英语多一点，发音就更离谱

**Comment by selfboot** [comment]
像 ChatGPT  ，用英文合成，发现也是错的。

**Comment by RVC-Boss** [comment]
> 英文发音也是很奇怪，有的音根本就不对。英语多一点，发音就更离谱

你提供几个发音有问题的case，我们针对case优化一下？

**Comment by selfboot** [comment]
好啊，只提供文本就行了的吧？

**Comment by andylin12** [comment]
> > 英文发音也是很奇怪，有的音根本就不对。英语多一点，发音就更离谱
> 
> 你提供几个发音有问题的case，我们针对case优化一下？

我遇到的问题是，类似于英文缩略的词都没法读对，比如：
CEO told CTO that we should use GPT to serve ABC company to predict MBTI.

包含CEO、CTO、GPT、ABC、MBTI这些专有名词，英文都尝试直接按照单词读法读。中英混的情况下，很多都是读这种缩略词。

**Comment by andylin12** [comment]
上面那位朋友的示例：
ChatGPT 告诉我，您的理解是正确的。当您使用指针对象时，您应该通过 uniqueptr 实例

chatGPT读了chat部分，GPT部分和缩略词一样的问题。uniqueptr读了unique的部分，ptr读不出来。

**Comment by puck1006** [comment]
识别成全大写的情况， 大多数是要一个音节一个音节的读。

**Comment by v3ucn** [comment]
edge_tts是把_replace为“下划线”，然后读出来

**Comment by andylin12** [comment]
> 识别成全大写的情况， 大多数是要一个音节一个音节的读。

有办法让模型一个音节一个音节的读吗？我尝试把字母分开，A B C D 这样读的都有问题，读的很怪。

**Comment by Misaka-Mikoto-Tech** [comment]
> > 识别成全大写的情况， 大多数是要一个音节一个音节的读。
> 
> 有办法让模型一个音节一个音节的读吗？我尝试把字母分开，A B C D 这样读的都有问题，读的很怪。

A-B-C-D-, 这样就可以一个字母一个字母的读了，我测试ktv是这样的（把ktv改成 k-t-v-）

**Comment by akechend** [comment]
补充一下, 推理可以用engdict-hot， 然后在文字里面使用小写绕过去，比如
```
AI EY1 AY1
```
在这里AI里面的A的发音(EY1)总是会跟前面的辅音产生连读,每次还必须使用标点符号做隔离, 所以其实还是比较别扭。
不知道有无有更好的方法。 

此外还有个问题，比如A股单独一个字母，默认发音是AH0， 但是实际上我们的习惯性发音是EY1，所以希望中文后面也出个热词，方便配置。
