### ISSUE TITLE
在运行一键三联后出错，mac m1

### ISSUE THREAD

**Issue by ZilongYang** [RVC-Boss/GPT-SoVITS#278]
```
"/Users/zilong/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
Traceback (most recent call last):
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
    resolved_file = hf_hub_download(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    validate_repo_id(arg_value)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.
Traceback (most recent call last):

The above exception was the direct cause of the following exception:

  File "/Users/zilong/zWork/py/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
Traceback (most recent call last):
  File "/Users/zilong/zWork/py/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 450, in cached_file
    resolved_config_file = cached_file(
  File "/Users/zilong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Traceback (most recent call last):
  File "/Users/zilong/zWork/py/GPT-SoVITS/webui.py", line 531, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/zl/2-name2text-0.txt'
```

**Comment by Stanley-baby** [comment]
我也是这个问题，请问找到解决方法了吗？
![CleanShot 2024-01-29 at 17 47 16@2x](https://github.com/RVC-Boss/GPT-SoVITS/assets/58399659/e809a157-9593-4592-aef5-ad90076eb32e)

**Comment by danielwii** [comment]
> 我也是这个问题，请问找到解决方法了吗？ ![CleanShot 2024-01-29 at 17 47 16@2x](https://private-user-images.githubusercontent.com/58399659/300408761-e809a157-9593-4592-aef5-ad90076eb32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjIxMjMsIm5iZiI6MTcwNjUyMTgyMywicGF0aCI6Ii81ODM5OTY1OS8zMDA0MDg3NjEtZTgwOWExNTctOTU5My00NTkyLWFlZjUtYWQ5MDA3NmViMzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5NTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYTc1ZTA3NmQzYmY0NTIxMmZhMjFiOTFlYzYzYzk1NjNiYTc0MWFhZjhlY2JiNmRkZjYwZTkxZDY2MDgxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHknzb0B6R7SMuapwmMCfjlCbyUdAdlhoZM1hr6QW0c)

see #256

**Comment by danielwii** [comment]
@ZilongYang 应该是 pretrained_models 目录放错了，如果你 clone 到了 root，里面还有个 GPT-SoVITS 目录。

**Comment by Stanley-baby** [comment]
意思就是在GPT-SoVITS文件夹中新建一个temp.py文件，temp.py文件里填入
```
import nltk
nltk.download('cmudict')
```
然后进入Python虚拟环境运行`temp.py`文件就可以了对吗？

**Comment by Stanley-baby** [comment]
> @ZilongYang 应该是 pretrained_models 目录放错了，如果你 clone 到了 GPT-SoVITS，里面还有个 GPT-SoVITS 目录，pretrained_models 应该放在里面那个 GPT-SoVITS。

模型放对了也是同样的报错：
![CleanShot 2024-01-29 at 19 40 26@2x](https://github.com/RVC-Boss/GPT-SoVITS/assets/58399659/5fb8fd09-e304-4381-98e8-a096df508bb8)

**Comment by xldbilibili** [comment]
搞了一下午 第一国内包有限制 需要自己下 需要的qq邮箱：xldstudio@qq.com 解压完要放到用户目录下
第二 里面要放模型才能运行

**Comment by Lion-Wu** [comment]
确保预训练模型全部正确下载并切放到对应的位置，类似这样：
<img width="1061" alt="Screenshot 2024-01-29 at 21 37 31" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/130235128/3edd41c5-28df-45b7-98ee-7fddb768f57c">

还不行的话试试克隆最新代码，之前有一次代码是出问题的

**Comment by Lion-Wu** [comment]
里面的文件不太一样吧，确保pretrained_models文件夹已经包含了[这个链接](https://huggingface.co/lj1995/GPT-SoVITS/tree/main)中的所有文件，文件名也要一样。或者用我那个网盘的文件，把里面的模型文件替换掉。

**Comment by ZilongYang** [comment]
> @ZilongYang 应该是 pretrained_models 目录放错了，如果你 clone 到了 GPT-SoVITS，里面还有个 GPT-SoVITS 目录，pretrained_models 应该放在里面那个 GPT-SoVITS。

> 确保预训练模型全部正确下载并切放到对应的位置，类似这样： <img alt="Screenshot 2024-01-29 at 21 37 31" width="1061" src="https://private-user-images.githubusercontent.com/130235128/300480204-3edd41c5-28df-45b7-98ee-7fddb768f57c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzgyNzQsIm5iZiI6MTcwNjUzNzk3NCwicGF0aCI6Ii8xMzAyMzUxMjgvMzAwNDgwMjA0LTNlZGQ0MWM1LTI4ZGYtNDViNy05OGVlLTdmZGRiNzY4ZjU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNDE5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzhlZGQ0MjljYzZhNmNkYWM1NDc4MTA2ZTI0NDU3MWJkYWIzODJmZDQ4MGI5NDZjMTM3ZTYzMGRkNGQxYmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2dkJQquWCxSeGpwpNvh4LTHn5Z2-GDZEAInH_MJBo2U">
> 
> 还不行的话试试克隆最新代码，之前有一次代码是出问题的

> 里面的文件不太一样吧，确保pretrained_models文件夹已经包含了[这个链接](https://huggingface.co/lj1995/GPT-SoVITS/tree/main)中的所有模型文件，文件名也要一样。或者用我那个网盘的文件里面的模型文件拖进去。

clone 了链接里的仓库里的文件，并放到了对应的位置，一键三连成功！

**Comment by zhangxirui-1997** [comment]
我clone了最新版，果然是模型放错位置了，感谢大佬 @ZilongYang
