### ISSUE TITLE
使用4090（在AUTODL上）出现了以下几个问题

### ISSUE THREAD

**Issue by IMBAepsilon** [RVC-Boss/GPT-SoVITS#30]
1. FFmpeg报错
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
```
但是ffmpeg -h是正常的，也尝试过
```
- sudo apt install ffmpeg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 141 not upgraded.
```
2. 6006端口被占用
手动改了下源码修改到其他端口解决了这个问题（？）

3. 推理时出现error
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/autodl-tmp/workdir/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 135, in get_tts_wav
    bert = torch.cat([bert1, bert2], 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Wed, 17 Jan 2024 10:14:44 GMT'), (b'server', b'uvicorn'), (b'content-length', b'14'), (b'content-type', b'application/json')])
INFO:httpx:HTTP Request: POST http://localhost:7896/api/predict "HTTP/1.1 500 Internal Server Error"
```
这部分我看没有弹出url可以直接访问，我使用了AUTODL提供的端口转发，7896端口（修改了源码中的6006，因为被占用了）到本地进行操作。（点击推理后出现error）

---

此外，问问目前是否有办法支持使用中文以外的语料吗
音频分割目前支持的应该还可以
标注方面，我本地通过fast-wisper可以标注
但是后面的BERT和SSL是否有模型可以直接使用

（其他卡留待验证，autodl没卡了，有机会再试试3090）

---

还有一些问题我没进一步研究，先询问一下
每一步的操作应该不会依赖前面的文件吧，比如我直接提供标注好的数据（.wav和.list），然后从后面的步骤进行（input之类的文件夹就留空了），应该不会影响吧
另外是推理应该只依赖于预训练模型和GPT（.pth）、SOVIT（.ckpt）的两个权重文件吧，如果只想进行推理，仅拷贝这两个文件到指定文件夹启动即可？

**Comment by RVC-Boss** [comment]
第三个问题，需要autodl镜像的作者更新github仓库，已经修复了。

**Comment by RVC-Boss** [comment]
是否有办法支持使用中文以外的语料：支持，demo里已经有群友测试了日文训练集。英文训练集我们还在测试。
后面的BERT和SSL是否有模型可以直接使用：BERT还没添加英文和日文，相当于现在的BERT执行会自动按中文的执行，然后后面不会利用到。逻辑还是有点问题，我完善下。SSL是兼容的不用管。
数据集的源就是wavs和.list就行了，前面只要.list文件格式对就没问题
推理指依赖于ssl、bert和微调训练的gpt+sovits这几个模型，后面2个是需要额外拷贝的

**Comment by IMBAepsilon** [comment]
另外似乎还有遇到一个问题
.list的路径似乎严格要求 '/' ，一开始使用反斜杠我看终端的输出也转换成了双斜杠，但是最后仍然报错，在我批量替换为正斜杠后似乎就没有问题了（不知道是不是我还有修改哪里，没仔细研究，稍微反馈一句）

**Comment by RVC-Boss** [comment]
> > 第三个问题，需要autodl镜像的作者更新github仓库，已经修复了。
> 
> 好的，我有时间去尝试一下自己搭建一下环境再试试，感谢回答（ん有群，开放吗）

群：671410265

**Comment by 4mm7** [comment]
您好，我注意到您遇到的第一个问题，可以请问一下您是怎么解决的吗？我也遇到了相同的问题，报错是：
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
raise ImportError("FFmpeg libraries are not found. Please install FFmpeg."
