### ISSUE TITLE
达摩asr无法运行

### ISSUE THREAD

**Issue by ISDHN** [RVC-Boss/GPT-SoVITS#301]
Traceback (most recent call last):
  File "E:\AI\vits\GPT-SoVITS\tools\damo_asr\cmd-asr.py", line 26, in <module>
    text = inference_pipeline(audio_in="%s/%s"%(dir,name))["text"]
  File "C:\Program Files\Python310\lib\site-packages\modelscope\pipelines\audio\funasr_pipeline.py", line 73, in __call__
    output = self.model(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\modelscope\models\base\base_model.py", line 35, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "C:\Program Files\Python310\lib\site-packages\modelscope\models\audio\funasr\model.py", line 61, in forward
    output = self.model.generate(*args, **kwargs)
TypeError: AutoModel.generate() missing 1 required positional argument: 'input'

达摩的asr好像换调用方式了

**Comment by yihuitang** [comment]
遇到同样的问题，根据requirements.txt把funasr升级到>=1.0.0后解决了

**Comment by ISDHN** [comment]
我是在1.0.3的asr下出的问题

**Comment by RVC-Boss** [comment]
pip install funasr==1.0.0更新一下

**Comment by ISDHN** [comment]
1.0.0、1.0.2、1.0.3都这样  
damo funasr的repo里有这样一条issue：
https://github.com/alibaba-damo-academy/FunASR/issues/1276

**Comment by yihuitang** [comment]
先卸载再安装试试呢，我是这么操作的

**Comment by ISDHN** [comment]
也是不行  
请问您是哪一天克隆的asr三个模型 
6天前asr的模型有更新

**Comment by yihuitang** [comment]
我用的今天最新的GPT-SoVITS代码库，发现asr错，就把funasr先卸载再安装的。也就是说都是今天安装的

**Comment by ISDHN** [comment]
好的解决了，我克隆的gpt-sovits不是最新的，谢谢

**Comment by LauraGPT** [comment]
If you still run with error, please raise issue in https://github.com/alibaba-damo-academy/FunASR

We have concluded the main difference between the funasr-1.0 and funasr-0.8.8: 
https://github.com/alibaba-damo-academy/FunASR/discussions/1319
