### ISSUE TITLE
Mac运行webui.py报错

### ISSUE THREAD

**Issue by FengtingTang** [RVC-Boss/GPT-SoVITS#305]
我在mac上使用`python web.py`运行时，返回了这样的报错信息：（用户名用xxx代表）
```
Traceback (most recent call last):
  File "/Users/xxx/GPT-SoVITS-main/webui.py", line 777, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda/lib/python3.11/site-packages/gradio/blocks.py", line 1715, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().
```

**Comment by Lion-Wu** [comment]
是跟着步骤一步一步运行下来后出错的吗？重新安装再试试？

**Comment by v3ucn** [comment]
文档里让用3.9，你用的是3.11吧

**Comment by wang1011945095** [comment]
相同的问题 怎么解决的啊???

**Comment by wang1011945095** [comment]
> 文档里让用3.9，你用的是3.11吧

用的是3.9啊 M1芯片

**Comment by caizhuoyue77** [comment]
> 重新开个虚拟环境吧

大佬，请问这种报错怎么解决呀：   import _jieba_fast_functions_py3 as _jieba_fast_functions
ImportError: dlopen(/Users/czy/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/_jieba_fast_functions_py3.cpython-39-darwin.so, 0x0002): tried: '/Users/czy/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/_jieba_fast_functions_py3.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/czy/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/_jieba_fast_functions_py3.cpython-39-darwin.so' (no such file), '/Users/czy/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/_jieba_fast_functions_py3.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Traceback (m

**Comment by tymon42** [comment]
虚拟环境重新用文档命令重新创建一下

**Comment by RVC-Boss** [comment]
concurrency_count 删了改default_concurrency_limit这个参数。gradio版本导致。这个参数含义为最大多少线程同时执行，多的要排队。
