### ISSUE TITLE
1A步骤文本推理报错

### ISSUE THREAD

**Issue by Jeru2023** [RVC-Boss/GPT-SoVITS#316]
昨天成功过一次，今天换了个4分钟的音频再运行一次就在训练过程报错了。之前的切分和标注都已经完成。

Traceback (most recent call last):
  File "D:\dev\replica\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 90, in process
    bert_feature = get_bert_feature(norm_text, word2ph)
  File "D:\dev\replica\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 68, in get_bert_feature
    res = bert_model(**inputs, output_hidden_states=True)
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\transformers\models\bert\modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\transformers\models\bert\modeling_bert.py", line 1006, in forward
    embedding_output = self.embeddings(
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\conda_envs\replica\lib\site-packages\transformers\models\bert\modeling_bert.py", line 238, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (617) must match the size of tensor b (512) at non-singleton dimension 1

**Comment by Jeru2023** [comment]
我又自己解决了，就是重新切割文件，将文件切割的比较平均，每段不会太长也不会太短，再跑一次就行了。不过这里还是要找找原因的，最好也给个建议切割到底每段多长比较合理。
