### ISSUE TITLE
Windows 运行 api.py 报错

### ISSUE THREAD

**Issue by lancemao** [RVC-Boss/GPT-SoVITS#321]
Hi，

在 Windows 下，运行 `python api.py`

```shell
(.venv) PS D:\OpenSource\GPT-SoVITS> python .\api.py
Traceback (most recent call last):
  File "D:\OpenSource\GPT-SoVITS\api.py", line 118, in <module>
    from feature_extractor import cnhubert
ModuleNotFoundError: No module named 'feature_extractor'
```

修改 PYTHONPATH：
```shell
$env:PYTHONPATH = ".\GPT_SoVITS\"  
```

后再次运行：

```shell
(.venv) PS D:\OpenSource\GPT-SoVITS> python .\api.py
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Mao\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\OpenSource\GPT-SoVITS\.venv\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg5
DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Mao\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\OpenSource\GPT-SoVITS\.venv\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg4
DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Mao\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\OpenSource\GPT-SoVITS\.venv\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
[WARN] 未指定SoVITS模型路径, fallback后当前值: GPT_SoVITS/pretrained_models/s2G488k.pth
[WARN] 未指定GPT模型路径, fallback后当前值: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
[INFO] 未指定默认参考音频
[INFO] 半精: True
Some weights of the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base were not used when initializing HubertModel: ['encoder.pos_conv_embed.conv.weight_g', 'encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of HubertModel were not initialized from the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
D:\OpenSource\GPT-SoVITS\.venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
<All keys matched successfully>
Number of parameter: 77.49M
DEBUG:asyncio:Using proactor: IocpProactor
INFO:     Started server process [40880]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:9880 (Press CTRL+C to quit)
```

可以看到服务是启动了，但是 ffmpeg 加载失败。日志说

`FileNotFoundError: Could not find module 'D:\OpenSource\GPT-SoVITS\.venv\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd'`

但这个文件就在那里

Plus：我已经按文档拷贝了 ffmpeg 相关 exe 到项目根目录。我也试着将 ffmpeg.exe 所在目录设置了电脑的环境变量，在 powershell 里面可以输入 ffmpeg 这个命令

麻烦看看是什么问题，感激！

**Comment by wangyi152** [comment]
这个问题我之前也遇到过，不过我是用conda装的环境，直接conda install ffmpeg就好了

**Comment by wangyi152** [comment]
这个问题我之前也遇到过，不过我是用conda装的环境，直接conda install ffmpeg就好了

**Comment by wangyi152** [comment]
这个问题我之前也遇到过，不过我是用conda装的环境，直接conda install ffmpeg就好了

**Comment by amoslue** [comment]
求问楼主最后怎么解决这个问题的？

**Comment by RVC-Boss** [comment]
项目最开头
import sys
sys.path.append("D:\OpenSource\GPT-SoVITS\GPT_SoVITS")
