### ISSUE TITLE
一键三连中途报错

### ISSUE THREAD

**Issue by PangXitong** [RVC-Boss/GPT-SoVITS#333]
已经做好了切割、标注，点击一键三连时报错，显示没有'logs/xxx/2-name2text-0.txt'，但是整个logs文件夹都是他自己生成的啊，我手动创建一个文件，在运行的时候就自己删除了，运行一键三连的终端输出如下：

"/Users/mac/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/Users/mac/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/mac/Desktop/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
  File "/Users/mac/Desktop/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 773, in from_pretrained
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 773, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 356, in cached_file
    resolved_config_file = cached_file(
  File "/Users/mac/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 356, in cached_file
    raise EnvironmentError(
    raise EnvironmentError(
OSError: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large does not appear to have a file named config.json. Checkout 'https://huggingface.co/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/None' for available files.
OSError: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large does not appear to have a file named config.json. Checkout 'https://huggingface.co/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/None' for available files.
Traceback (most recent call last):
  File "/Users/mac/Desktop/GPT-SoVITS/webui.py", line 548, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'

<img width="2048" alt="截屏2024-02-01 09 59 26" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/112756665/ae393e6a-961f-48ae-a87a-8f37bafe6b89">

感谢教导

**Comment by 450586509** [comment]
"OSError: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large does not appear to have a file named config.json."

检查一下为什么这个目录：GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
没有config.json

**Comment by Lion-Wu** [comment]
模型下载的问题，检查一下下载的模型文件名称是否与huggingface上显示的是否相同

**Comment by asdfghkl12345** [comment]
Traceback (most recent call last):
  File "D:\GPT-SoVITS-main\GPT-SoVITS-main\GPT_SoVITS\prepare_datasets\1-get-text.py", line 11, in <module>
Traceback (most recent call last):
  File "D:\GPT-SoVITS-main\GPT-SoVITS-main\GPT_SoVITS\prepare_datasets\1-get-text.py", line 11, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
//就是这儿                返回的是None，他就没法get
  File "C:\Users\wangsishun\AppData\Local\Programs\Python\Python310\lib\os.py", line 684, in __setitem__
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "C:\Users\wangsishun\AppData\Local\Programs\Python\Python310\lib\os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\wangsishun\AppData\Local\Programs\Python\Python310\lib\os.py", line 742, in check_str
    value = self.encodevalue(value)
  File "C:\Users\wangsishun\AppData\Local\Programs\Python\Python310\lib\os.py", line 742, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "D:\GPT-SoVITS-main\GPT-SoVITS-main\webui.py", line 539, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/wangsishun/2-name2text-0.txt'
我没有GPU，他返回来的就是None，报错了。有大佬看看怎么解决

**Comment by PangXitong** [comment]
问题解决了，感谢各位

**Comment by zjsxr1979** [comment]
> 问题解决了，感谢各位

大佬，怎么解决的？一样的问题

**Comment by AoungY** [comment]
将\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets目录下的三个.py文件的
os.environ["CUDA_VISIBLE_DEVICES"]= os.environ.get("_CUDA_VISIBLE_DEVICES")
全部换成：
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
出自yoko-penta的解决方案：https://github.com/RVC-Boss/GPT-SoVITS/issues/270

**Comment by HyH-QAQ** [comment]
改了之后一键三连还是报错啊

**Comment by AoungY** [comment]
用cpu训练：https://github.com/RVC-Boss/GPT-SoVITS/issues/290#issuecomment-1916306780

**Comment by GitHubJiKe** [comment]
> 问题解决了，感谢各位

怎么解决的？分享一下，感谢。

**Comment by thwy1991** [comment]
下载的模型里边的配置文件的名称变动了

**Comment by bigmarten** [comment]
这个问题有人解决了吗，修改os.environ无效。

**Comment by bigmarten** [comment]
已解决。linux上出现此问题，找到windows懒人包，把里面的nltk_data拷贝到环境的搜索路径下，例如： cp /home/saizong/GPT_SoVITS/runtime/nltk_data/ /home/saizong/.conda/envs/GPT-SoVITS/nltk_data

**Comment by tingfengaiai** [comment]
一键三连报错：求大神指导

D:\GPT-SoVITS-beta\GPT-SoVITS>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"D:\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: '"D:\\GPT-SoVITS-beta\\GPT-SoVITS\\output\\asr_opt\\dong.list"'
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: '"D:\\GPT-SoVITS-beta\\GPT-SoVITS\\output\\asr_opt\\dong.list"'
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\webui.py", line 498, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/me/2-name2text-0.txt'
ERROR: The process "6772" not found.
ERROR: The process "29992" not found.

**Comment by tingfengaiai** [comment]
一键三连报错，求大神指导。：：

"D:\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: '"D:\\GPT-SoVITS-beta\\GPT-SoVITS\\output\\asr_opt\\dong.list"'
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 96, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
OSError: [Errno 22] Invalid argument: '"D:\\GPT-SoVITS-beta\\GPT-SoVITS\\output\\asr_opt\\dong.list"'
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS\webui.py", line 498, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/me/2-name2text-0.txt'
ERROR: The process "6772" not found.
ERROR: The process "29992" not found.

**Comment by hhh315xxx** [comment]
我是重新下载了chinese-roberta-wwm-ext-large模型换上去得以解决，应该是之前模型安装有文件缺失。比如config，和pytorch_model这个文件不对，所以老是报错，可以在huggingface或者镜像[https://hf-mirror.com/hfl/chinese-roberta-wwm-ext-large/tree/main下载正解的模型。而且重试时候，要把对应logs文件夹里原来生成的删除掉，重新生成最好，不删除也会报错。]

**Comment by Hellohaki** [comment]
rtf_avg: 0.007: 100%|████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 86.96it/s]
time cost vad: 0.023|████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 86.96it/s]
rtf_avg: -0.003: 100%|██████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 500.01it/s]
rtf_avg_all_samples: 0.053, time_speech_total_all_samples:  3.200, time_escape_total_all_samples: 0.171: 100%|█| 2/2 [0
rtf_avg_per_sample: 0.051, time_speech_total_per_sample:  3.200, time_escape_total_per_sample: 0.164:  50%|▌| 1/2 [00:0
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  6.24it/s]
ASR 任务完成->标注文件路径: E:\GPT-SoVITS-beta0706\output\asr_opt\slicer_opt.list

"E:\GPT-SoVITS-beta0706\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\GPT-SoVITS-beta0706\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0706\GPT_SoVITS\prepare_datasets\1-get-text.py", line 102, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'E:\\GPT-SoVITS-beta0706\\output\\asr_opt'
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0706\GPT_SoVITS\prepare_datasets\1-get-text.py", line 102, in <module>
    with open(inp_text, "r", encoding="utf8") as f:
PermissionError: [Errno 13] Permission denied: 'E:\\GPT-SoVITS-beta0706\\output\\asr_opt'
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0706\webui.py", line 584, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
错误: 没有找到进程 "7312"。
错误: 没有找到进程 "8860"。

大佬们，我这个是什么原因

**Comment by wwzhifeng** [comment]
检查杀毒软件或同步工具：

   - 临时关闭杀毒软件，或者将 E:\GPT-SoVITS-beta0706 目录加入白名单。


Hellohaki ***@***.***> 于2024年11月25日周一 21:55写道：

**Comment by XXXXRT666** [comment]
路径不对，文件路径

**Comment by wwzhifeng** [comment]
OK，感谢建议

XXXXRT666 ***@***.***> 于2024年11月26日周二 05:42写道：
