### ISSUE TITLE
TTS推理WebUI出現錯誤

### ISSUE THREAD

**Issue by win10ogod** [RVC-Boss/GPT-SoVITS#340]
@julian0703
你有頭緒嗎?
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\GPT-SoVITS-beta\GPT_SoVITS\inference_webui.py", line 306, in get_tts_wav
    if (prompt_text[-1] not in splits): prompt_text += "。" if prompt_language != "en" else "."
IndexError: string index out of range

**Comment by win10ogod** [comment]
![Uploading 螢幕擷取畫面 2024-02-01 180612.png…]()

**Comment by win10ogod** [comment]
![Uploading 螢幕擷取畫面 2024-02-01 180612.png…]()

**Comment by win10ogod** [comment]
![螢幕擷取畫面 2024-02-01 180612](https://github.com/RVC-Boss/GPT-SoVITS/assets/125795763/74a73849-9e65-4f17-ad85-88e79aa733e1)

**Comment by baicai-1145** [comment]
没有填参考音频
