### ISSUE TITLE
在GPT training 时显示训练完成但是没有文件导出并且报错ZeroDivisionError: division by zero，SoVITS 正常运行，

### ISSUE THREAD

**Issue by SFowo** [RVC-Boss/GPT-SoVITS#347]
如题 也尝试了不同的音频但是同样的错位

**Comment by SFowo** [comment]
出错代码如下：
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [geo2.adobe.com]:59903 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [geo2.adobe.com]:59903 (system error: 10049 - The requested address is not valid in its context.).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 22
phoneme_data_len: 22
                                            item_name                                     semantic_audio
0   vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 280 486 486 486 486 486 280 53 140 17 5...
1   vocal_Introduction_0rqgq26.aif.reformatted.wav...  722 540 714 760 633 443 443 443 443 377 287 76...
2   vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 280 280 536 490 65 248 230 916 916 27 837 ...
3   vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 214 463 127 916 2 248 623 797 656 142 7...
4   vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 280 280 280 536 200 260 490 5 5 490 142 50...
5   vocal_Introduction_0rqgq26.aif.reformatted.wav...  214 132 738 278 270 687 227 441 146 147 147 14...
6   vocal_Introduction_0rqgq26.aif.reformatted.wav...  582 16 366 687 65 436 908 552 197 124 436 646 ...
7   vocal_Introduction_0rqgq26.aif.reformatted.wav...  214 490 214 16 916 127 247 57 663 76 75 1002 4...
8   vocal_Introduction_0rqgq26.aif.reformatted.wav...  54 98 5 463 916 366 248 524 277 451 824 824 73...
9   vocal_Introduction_0rqgq26.aif.reformatted.wav...  338 365 500 99 500 256 134 539 965 75 524 257 ...
10  vocal_Introduction_0rqgq26.aif.reformatted.wav...  1005 99 916 127 916 247 273 247 2 99 804 190 1...
11  vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 53 875 574 5 916 273 135 243 32 509 748...
12  vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 490 500 463 366 366 687 687 507 142 844...
13  vocal_Introduction_0rqgq26.aif.reformatted.wav...  214 338 463 273 270 788 477 916 775 965 569 58...
14  vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 280 486 486 53 274 623 99 750 565 29 86...
15  vocal_Introduction_0rqgq26.aif.reformatted.wav...  1012 360 1005 2 52 127 477 647 190 1001 533 95...
16  vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 280 486 486 486 486 486 258 574 574 714 61...
17  vocal_Introduction_0rqgq26.aif.reformatted.wav...  214 1005 837 612 173 987 987 697 590 590 402 4...
18  vocal_Introduction_0rqgq26.aif.reformatted.wav...  208 160 500 1005 8 134 504 965 490 75 961 587 ...
19  vocal_Introduction_0rqgq26.aif.reformatted.wav...  520 53 98 368 490 463 463 127 544 57 663 237 1...
20  vocal_Introduction_0rqgq26.aif.reformatted.wav...  1005 5 593 500 248 248 623 90 142 441 277 987 ...
21  vocal_Introduction_0rqgq26.aif.reformatted.wav...  214 360 574 524 139 354 567 567 380 641 654 89...
Traceback (most recent call last):
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 170, in <module>
    main(args)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 146, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT_SoVITS\AR\data\data_module.py", line 29, in setup
    self._train_dataset = Text2SemanticDataset(
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT_SoVITS\AR\data\dataset.py", line 107, in __init__
    self.init_batch()
  File "C:\Users\Zesen\OneDrive\Desktop\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by anyshu** [comment]
same issue

**Comment by lishengjia** [comment]
same issue
