### ISSUE TITLE
api如何开启调用？

### ISSUE THREAD

**Issue by a614349007** [RVC-Boss/GPT-SoVITS#348]
各位大佬，我想问一下现在有api文档么，该如何开启。

**Comment by wangyi152** [comment]
api.py里有接口的调用方法。

**Comment by a614349007** [comment]
我按着app.py上面的测试了一下，运行的时候一直报有个包没安装，但是我看是已经安了的。
(GPTSoVits) E:\GPT-SoVITS\GPT-SoVITS-beta>pip install feature_extractor
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting feature_extractor
  Downloading https://mirrors.aliyun.com/pypi/packages/84/02/1aeb320ec51fcd14045f10a50b6c031da56da4b9b81879d8932b2d544020/feature_extractor-0.0.1-py3-none-any.whl (2.2 kB)
Installing collected packages: feature_extractor
Successfully installed feature_extractor-0.0.1

(GPTSoVits) E:\GPT-SoVITS\GPT-SoVITS-beta>python api.py -dr "E:\GPT-SoVITS\yyz_9m.mp3" -dt "xxxxxxxxxxxxxxxxxxx。" -dl "zh"
Traceback (most recent call last):
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\api.py", line 118, in <module>
    from feature_extractor import cnhubert
ModuleNotFoundError: No module named 'feature_extractor'

**Comment by wangyi152** [comment]
这个包应该是项目里的feature_extractor而不是pypi中的feature_extractor

**Comment by a614349007** [comment]
调用api调用报错。。用的python是包里runtime里面自带的
`  7%|█████▎                                                                         | 101/1500 [00:01<00:22, 61.81it/s]T2S Decoding EOS [249 -> 354]
  7%|█████▌                                                                         | 105/1500 [00:01<00:22, 61.97it/s]
0.361   0.183   1.696   0.431
INFO:     127.0.0.1:64148 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\runtime\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\api.py", line 482, in tts_endpoint
    return handle(
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\api.py", line 442, in handle
    torch.mps.empty_cache()
AttributeError: module 'torch' has no attribute 'mps'`

**Comment by suonian** [comment]
Pytorch 版本不对

**Comment by a614349007** [comment]
我这是window上运行的

**Comment by jiangfan99** [comment]
非常感谢两位大佬的解答，目前安装完VS后就能安装JIEBA-FAST了

**Comment by shenmidigua** [comment]
> 这个包应该是项目里的feature_extractor而不是pypi中的feature_extractor

项目的site-packages里没feature_extractor啊

**Comment by shenmidigua** [comment]
> 我按着app.py上面的测试场景，运行的时候一直报有一个包没安装，但是我看是已经安了的。 (GPTSoVits) E:\GPT-SoVITS\GPT-SoVITS-beta>pip install feature_extractor 查看索引：https://mirrors.aliyun.com/pypi/simple/ 收集feature_extractor 下载[https://mirrors.aliyun.com/pypi/packages/84/02/1aeb320ec51fcd14045f10a50b6c031da56da4b9b81879d8932b2d544020/feature_extractor-0.0 。 1-py3- none-any.whl](https://mirrors.aliyun.com/pypi/packages/84/02/1aeb320ec51fcd14045f10a50b6c031da56da4b9b81879d8932b2d544020/feature_extractor-0.0.1-py3-none-any.whl) (2.2 kB) 安装收集的软件包：feature_extractor 已成功安装 feature_extractor-0.0.1
> 
> (GPTSoVits) E:\GPT-SoVITS\GPT-SoVITS-beta>python api.py -dr "E:\GPT-SoVITS\yyz_9m.mp3" -dt "xxxxxxxxxxxxxxxxxxx。" -dl "zh" Traceback (最近调用最后）： 文件“E：\ GPT-SoVITS \ GPT-SoVITS-beta \ api.py”，第118行，来自 feature_extractor import cnhubert ModuleNotFoundError：没有名为“feature_extractor”的模块

老哥解决了吗

**Comment by wangyi152** [comment]
> > 这个包应该是项目里的feature_extractor而不是pypi中的feature_extractor
> 
> 项目的site-packages里没feature_extractor啊

有的，在项目目录/GPT_SoVITS/feature_extractor 下

**Comment by shandong-jiaotong** [comment]
在文件上方加上
import sys,os,re, logging
now_dir = os.getcwd()
sys.path.insert(0,f"{now_dir}/GPT_SoVITS")

**Comment by badLeigel** [comment]
开启API页面总是报
No named API Routes found for http://localhost:9872/
To expose an API endpoint of your app in this page, set the api_name parameter of the event listener.
For more information, visit the [API Page guide](https://gradio.app/sharing_your_app/#api-page). To hide the API documentation button and this page, set show_api=False in the Blocks.launch() method.
