### ISSUE TITLE
我已经更改了复制网友的data_utils了，但是在GPT训练的时候还是出现ZeroDivisionError: division by zero，求助

### ISSUE THREAD

**Issue by firethreek** [RVC-Boss/GPT-SoVITS#351]
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-4IHMH5U]:51480 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-4IHMH5U]:51480 (system error: 10049 - 在其上下文中，该请求的地址无效。).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 7
phoneme_data_len: 7
                     item_name                                     semantic_audio
0         vit.wav_0_193600.wav  520 486 486 1005 456 565 565 582 565 837 227 2...
1  vit.wav_1196800_1439040.wav  1005 156 880 309 309 309 395 289 354 66 66 407...
2    vit.wav_193600_342080.wav  520 274 227 500 722 216 714 578 586 639 319 97...
3    vit.wav_644160_789760.wav  277 594 771 80 748 686 748 507 277 160 103 722...
4  vit.wav_1004800_1196800.wav  520 290 721 366 593 214 5 500 17 274 366 197 2...
5  vit.wav_1465280_1596800.wav  199 859 728 391 538 605 601 122 203 17 539 4 1...
6    vit.wav_384320_644160.wav  208 696 696 208 239 625 562 886 586 628 333 63...
Traceback (most recent call last):
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 171, in <module>
    main(args)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 147, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\AR\data\data_module.py", line 29, in setup
    self._train_dataset = Text2SemanticDataset(
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 107, in __init__
    self.init_batch()
  File "C:\Program Files\GPT-SoVITS-beta\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by wwy6668219** [comment]
这是除零错误，使用手册的报错合集里有https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e?# 《GPT-SoVITS指南》
