### ISSUE TITLE
使用macbookpro M1，一键三连报错

### ISSUE THREAD

**Issue by zjsxr1979** [RVC-Boss/GPT-SoVITS#352]
用的macbookpro M1，一键三连报错，已经根据yoko-penta的解决方案：https://github.com/RVC-Boss/GPT-SoVITS/issues/270
把 GPT-SoVITS\GPT_SoVITS\prepare_datasets目录下的三个.py文件的
os.environ["CUDA_VISIBLE_DEVICES"]= os.environ.get("_CUDA_VISIBLE_DEVICES")
全部换成：
os.environ["CUDA_VISIBLE_DEVICES"] = "0"，

还是不行，总是报：
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/webui.py", line 548, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/laoLuo/2-name2text-0.txt'

------ 报错
"/Users/shenxirong/anaconda3/envs/GPTSoVits/bin/python3" GPT_SoVITS/prepare_datasets/1-get-text.py
"/Users/shenxirong/anaconda3/envs/GPTSoVits/bin/python3" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 19, in <module>
    from text.cleaner import clean_text
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/text/english.py", line 4, in <module>
    from g2p_en import G2p
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 19, in <module>
    from text.cleaner import clean_text
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/GPT_SoVITS/text/english.py", line 4, in <module>
    from g2p_en import G2p
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/Users/shenxirong/anaconda3/envs/GPTSoVits/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "/Users/shenxirong/01-workdata/00-sourcecode/GPT-SoVITS/webui.py", line 548, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/laoLuo/2-name2text-0.txt'

**Comment by HyH-QAQ** [comment]
加一，请问解决了吗

**Comment by HyH-QAQ** [comment]
你看一下自己的模型是不是放错了位置？
<img width="648" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/154300301/c56b5195-36d4-49a3-8b67-b1b4b4b48754">
放到这个下面：GPT-SoVITS/GPT_SoVITS/pretrained_models
即是：/GPT_SoVITS/pretrained_models/chinese-hubert-base

**Comment by tymon42** [comment]
预训练模型的位置放对了吗？

**Comment by zjsxr1979** [comment]
> 你看一下自己的模型是不是放错了位置？ <img alt="image" width="648" src="https://private-user-images.githubusercontent.com/154300301/301842661-c56b5195-36d4-49a3-8b67-b1b4b4b48754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODU1MTYsIm5iZiI6MTcwNjg4NTIxNiwicGF0aCI6Ii8xNTQzMDAzMDEvMzAxODQyNjYxLWM1NmI1MTk1LTM2ZDQtNDlhMy04YjY3LWIxYjRiNGI0ODc1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODY3ZmY2Yjk1ZGQ3ZjQxZGVjMWQ4YzUxOGY3MzFmNzNhYWQ5YTQ2MDFkYmJlNTM2ZGYxMDU0NGI2M2JlOTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OkpuHVVwZV_8rQXzsTwXZ3Di0bYpjtWr1Wm4Iv0SL-I"> 放到这个下面：GPT-SoVITS/GPT_SoVITS/pretrained_models 即是：/GPT_SoVITS/pretrained_models/chinese-hubert-base

我没放错啊，就是在项目GPT_SoVITS根目录下的GPT_SoVITS/pretrained_models 里面
<img width="1226" alt="截屏2024-02-02 22 54 25" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/57403983/db2d2d6d-77e6-455f-955a-4669e691bc86">

**Comment by tymon42** [comment]
还有个情况你也要检查下，这些模型的大小是不是100兆左右的大小（至少不能是若干 kb）

通过 某些途径下载的模型是个 alias 链接文件。

**Comment by zjsxr1979** [comment]
> 预训练模型的位置放对了吗？

没错啊，就是在项目GPT_SoVITS根目录下的GPT_SoVITS/pretrained_models 里面，我还找了台windows试了下封装版，能跑，对比了windows版本的安装目录，没错啊

**Comment by tymon42** [comment]
> > 预训练模型的位置放对了吗？
> 
> 没错啊，就是在项目GPT_SoVITS根目录下的GPT_SoVITS/pretrained_models 里面，我还找了台windows试了下封装版，能跑，对比了windows版本的安装目录，没错啊

那就不是 alias 文件的问题。

**Comment by zjsxr1979** [comment]
> 还有个情况你也要检查下，这些模型的大小是不是100兆左右的大小（至少不能是若干 kb）
> 
> 通过 某些途径下载的模型是个 alias 链接文件。

是的，都是100兆左右，对比了windows能跑的那个版本文件，大小完全一样

**Comment by tymon42** [comment]
我的的 m2 直接拉取代码就行了，不用改代码。你该代码是遇到什么问题了吗？

**Comment by zjsxr1979** [comment]
> 我的的 m2 直接拉取代码就行了，不用改代码。你该代码是遇到什么问题了吗？

我没改任何代码。。。

**Comment by tymon42** [comment]
或者你可以把 WEB UI 的截图放上来，看看是不是路径每填对。

**Comment by HyH-QAQ** [comment]
用cpu训练：https://github.com/RVC-Boss/GPT-SoVITS/issues/290#issuecomment-1916306780

**Comment by zjsxr1979** [comment]
> 或者你可以把 WEB UI 的截图放上来，看看是不是路径没填对。

<img width="1293" alt="截屏2024-02-02 23 21 48" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/57403983/6e2e890b-d3b0-4214-8610-70688cee305e">

**Comment by zjsxr1979** [comment]
> 用cpu训练：[#290 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/290#issuecomment-1916306780)

试过了，都改成cpu了，问题依旧，没有任何变化，还是一样的报错

**Comment by tymon42** [comment]
https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt#W3oBn

我这些地方都是用绝对路径的，可以试试

> > 或者你可以把 WEB UI 的截图放上来，看看是不是路径没填对。
> 
> <img alt="截屏2024-02-02 23 21 48" width="1293" src="https://private-user-images.githubusercontent.com/57403983/301889104-6e2e890b-d3b0-4214-8610-70688cee305e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzA5NzYsIm5iZiI6MTcwNjkzMDY3NiwicGF0aCI6Ii81NzQwMzk4My8zMDE4ODkxMDQtNmUyZTg5MGItZDNiMC00MjE0LTg2MTAtNzA2ODhjZWUzMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAzMjQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMmY2NGNiN2RkYTk2ZDI4Yzc1YTA4MjIyMDg4YmVlNzQyNmUzNWI5OTNlMWUwOGExOWNiYmIxOTM0MmI4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZGc5r0YjWCi3tmezJoREOVstQmT8FtTsmLUmHICWGA">

**Comment by ISDHN** [comment]
似乎是nltk这个库的文件有问题，尝试卸载重装看看（？

**Comment by ISDHN** [comment]
似乎是nltk这个库的文件有问题，尝试卸载重装看看（？

**Comment by mhkz** [comment]
我的m1也是同样报错，但是没有解决

**Comment by Lion-Wu** [comment]
看起来是nltk的问题。用户文件夹中应该有一个nltk_data的文件夹，把它删掉重新运行试试，也有可能是网的问题，导致下载失败

**Comment by projoy** [comment]
我的是windows10，也遇到了这个问题，后来解决了。

问题过程如下：
1.最开始的时候机器上没有配置nltk_data，直接运行“一键三连”时，GPT-SoVITS会从github上拉取nltk。因为拉取的太慢，就手工停止了。
2.然后，手工安装了nltk，配置路径为d:/nltk_data
3.再运行“一键三连”时，就报了这个错误。

解决如下：
检查发现，在C:\\Users\\xxxx\\AppData\\Roaming\\nltk_data这个路径下存在一个nltk_data目录，应该是第一次自动下载的不完整的数据。把C:\\Users\\xxxx\\AppData\\Roaming\\nltk_data这个目录删除，使用d:/nltk_data。然后再重新运行服务，一切正常了

**Comment by paulhahaha** [comment]
解决了吗

**Comment by gallonyin** [comment]
我解决了，在本地下载一下两个文件（需要翻墙，本地开个vpn）。

使用python写个脚本下载：
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('cmudict')

然后可以在本地找到两个文件，我的电脑目录是：
C:\Users\gallo\AppData\Roaming\nltk_data\taggers\averaged_perceptron_tagger.zip
C:\Users\gallo\AppData\Roaming\nltk_data\corpora\cmudict.zip

把这两个文件拷贝到服务器上，我的服务器目录是：
/root/nltk_data/taggers/averaged_perceptron_tagger.zip
/root/nltk_data/corpora/cmudict.zip
linux服务器的话 你可以先看下~/nltk_data 这个目录的位置。

然后这个报错就没了。

**Comment by gallonyin** [comment]
[averaged_perceptron_tagger.zip](https://github.com/user-attachments/files/16542659/averaged_perceptron_tagger.zip)
[cmudict.zip](https://github.com/user-attachments/files/16542683/cmudict.zip)
文件直接发这里试试

**Comment by RVC-Boss** [comment]
nltk库文件的问题可以参考楼上这些回复。
