### ISSUE TITLE
GPT-SoVITS在格式化训练集后训练无法导出模型

### ISSUE THREAD

**Issue by a1123211** [RVC-Boss/GPT-SoVITS#353]
以下是我的运行日志：
Z:\GPT-SoVITS-beta>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"Z:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/s2_train.py --config "Z:\GPT-SoVITS-beta\TEMP/tmp_s2.json"
"Z:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "Z:\GPT-SoVITS-beta\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
INFO:ZhangLang:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 8, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 3, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/ZhangLang'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/ZhangLang', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'ZhangLang', 'pretrain': None, 'resume_step': None}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 170, in <module>
    main(args)
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 127, in main
    model: Text2SemanticLightningModule = Text2SemanticLightningModule(
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 26, in __init__
    torch.load(pretrained_s1, map_location="cpu")["weight"]
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Z:/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt'
Traceback (most recent call last):
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "Z:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 85, in run
    train_dataset = TextAudioSpeakerLoader(hps.data)  ########
  File "Z:\GPT-SoVITS-beta\GPT_SoVITS\module\data_utils.py", line 56, in __init__
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by wwy6668219** [comment]
这是除零错误，使用手册的报错合集里有https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e?# 《GPT-SoVITS指南》
