### ISSUE TITLE
ubuntu上安装环境后，运行python api.py 报错typeError

### ISSUE THREAD

**Issue by iloveming** [RVC-Boss/GPT-SoVITS#357]
(gpt) root@notebook-bd2a8881-c0f5-11ee-9fd1-000000198b56-6b95796899-j2d66:/opt/ml/server/GPT-SoVITS# python api.py 
Traceback (most recent call last):
  File "api.py", line 128, in <module>
    from text.cleaner import clean_text
  File "/opt/ml/server/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/opt/ml/server/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 100, in <module>
    def pyopenjtalk_g2p_prosody(text: str, drop_unvoiced_vowels: bool = True) -> list[str]:
TypeError: 'type' object is not subscriptable

大佬知道怎么回事吗

**Comment by RVC-Boss** [comment]
fixed.

**Comment by czg2066** [comment]
大佬解决了吗？能给一下教程吗？
