### ISSUE TITLE
MacOS M1合成中文和英文语音都没问题，唯独合成日文语音时报Error

### ISSUE THREAD

**Issue by fedavinci** [RVC-Boss/GPT-SoVITS#360]
```
Downloading: "https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz"
dic.tar.gz: 0.00B [00:00, ?B/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
dic.tar.gz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 369, in get_tts_wav
    phones2, word2ph2, norm_text2 = nonen_clean_text_inf(text, text_language)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 263, in nonen_clean_text_inf
    phones, word2ph, norm_text = clean_text_inf(textlist[i], lang)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 238, in clean_text_inf
    phones, word2ph, norm_text = clean_text(text, language)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 23, in clean_text
    phones = language_module.g2p(norm_text)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 183, in g2p
    phones = preprocess_jap(norm_text, with_prosody)
  File "/Users/taoxu/Desktop/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 85, in preprocess_jap
    p = pyopenjtalk.g2p(sentence)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyopenjtalk/__init__.py", line 99, in g2p
    _lazy_init()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyopenjtalk/__init__.py", line 79, in _lazy_init
    _extract_dic()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyopenjtalk/__init__.py", line 66, in _extract_dic
    urlretrieve(_DICT_URL, filename, reporthook=t.update_to)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by RVC-Boss** [comment]
因为他要从github下一个东西，然后你的网络连不上github，解决办法是手动下载然后放到那个包的根目录下解压。

**Comment by fedavinci** [comment]
> 因为他要从github下一个东西，然后你的网络连不上github，解决办法是手动下载然后放到那个包的根目录下解压。

<img width="266" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/142563240/ad9df137-3782-4db9-bbc4-ccd73a4511e9">
已经解压好了，要放到哪个包的根目录下？

**Comment by Samkumayui** [comment]
> 因为他要从github下一个东西，然后你的网络连不上github，解决办法是手动下载然后放到那个包的根目录下解压。

请问,是放到哪个文件夹下面.

**Comment by XXXXRT666** [comment]
site-packages/pyopenjtalk
