### ISSUE TITLE
OpenDL微调报错：No supported gpu backend found

### ISSUE THREAD

**Issue by caizhuoyue77** [RVC-Boss/GPT-SoVITS#363]
在OpenDL新建了一个实例，在训练GPT和Solvits模型的时候报错说没有GPU：（一次只训练了一个，都显示这个错误）

<img width="1387" alt="截屏2024-02-03 10 23 18" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/149372809/0e0cb563-b6d5-44e0-bfec-089c0c2e5085">

```
AssertionError: Only GPU training is allowed.
"/root/miniconda3/bin/python" GPT_SoVITS/s1_train.py --config_file "TEMP/tmp_s1.yaml" 
Seed set to 1234
Traceback (most recent call last):
  File "/root/workdir/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 171, in <module>
    main(args)
  File "/root/workdir/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 110, in main
    trainer: Trainer = Trainer(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 401, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 152, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 372, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_fabric.utilities.exceptions.MisconfigurationException: No supported gpu backend found!
```

**Comment by RVC-Boss** [comment]
现在应该已支持，除非系统cuda不对，参考readme的已测试环境
