### ISSUE TITLE
打标未自动弹出 webui    报错FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by QLuxQ** [RVC-Boss/GPT-SoVITS#383]
Traceback (most recent call last):
  File "H:\AI\gpt sovits\GPT-SoVITS\beta\GPT-SoVITS-beta\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "H:\AI\gpt sovits\GPT-SoVITS\beta\GPT-SoVITS-beta\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "H:\AI\gpt sovits\GPT-SoVITS\beta\GPT-SoVITS-beta\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "H:\AI\gpt sovits\GPT-SoVITS\beta\GPT-SoVITS-beta\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\AI\\gpt sovits\\GPT-SoVITS\\beta\\GPT-SoVITS-beta\\output\\asr_opt.list'

**Comment by QLuxQ** [comment]
eemmm 没事了，要点击文件然后用左上角的主页，点复制路径
