### ISSUE TITLE
GPT训练出错

### ISSUE THREAD

**Issue by Pandaft** [RVC-Boss/GPT-SoVITS#401]
在 `1B-微调训练` 中进行 GPT 训练时出错。

## 环境版本

 - GPU: RTX 2060 6G
 - CUDA Version: 11.7
 - torch: 1.13.1+cu116
 - torchvision: 0.14.1+cu116
 - torchaudio: 0.13.1

## 报错信息

```log
"C:\Users\panda\.conda\envs\GPTSoVits\python.exe" GPT_SoVITS/s1_train.py --config_file "D:\AI\GPT-SoVITS\GPT-SoVITS\TEMP/tmp_s1.yaml"
Traceback (most recent call last):
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 18, in <module>
    from AR.models.t2s_lightning_module import Text2SemanticLightningModule
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 10, in <module>
    from AR.models.t2s_model import Text2SemanticDecoder
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\AR\models\t2s_model.py", line 14, in <module>
    from AR.modules.transformer import LayerNorm
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\AR\modules\transformer.py", line 13, in <module>
    from AR.modules.activation import MultiheadAttention
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\AR\modules\activation.py", line 15, in <module>
    from AR.modules.patched_mha_with_cache import multi_head_attention_forward_patched
  File "D:\AI\GPT-SoVITS\GPT-SoVITS\GPT_SoVITS\AR\modules\patched_mha_with_cache.py", line 2, in <module>
    from torch.nn.functional import (
ImportError: cannot import name '_canonical_mask' from 'torch.nn.functional' (C:\Users\panda\.conda\envs\GPTSoVits\lib\site-packages\torch\nn\functional.py)
```

**Comment by Pandaft** [comment]
torch 版本过低，在更新显卡驱动、CUDA Toolkit 和 torch 后顺利解决该问题。

**Comment by Wei-JL** [comment]
我也遇见了这个问题，找到能用的torch版本了，指令如下:
`pip install torch==2.1 torchvision torchaudio -i https://pypi.tuna.tsinghua.edu.cn/simple`
