### ISSUE TITLE
请问现在可以用日语训练吗？

### ISSUE THREAD

**Issue by BZBY** [RVC-Boss/GPT-SoVITS#404]
==，我直接用日语语音和标注训练，会报错。是不是得换个底模（

**Comment by Treemh** [comment]
一键三连报错吗？我这边用日语一键三连会报错，但多点几次后又可以通过

**Comment by BZBY** [comment]
> 一键三连报错吗？我这边用日语一键三连会报错，但多点几次后又可以通过

不是，是gpt训练那部分，是不是得换个日语底模啊

`Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0128\GPT_SoVITS\s1_train.py", line 170, in <module>
    main(args)
  File "E:\GPT-SoVITS-beta0128\GPT_SoVITS\s1_train.py", line 146, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "E:\GPT-SoVITS-beta0128\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "E:\GPT-SoVITS-beta0128\GPT_SoVITS\AR\data\data_module.py", line 29, in setup
    self._train_dataset = Text2SemanticDataset(
  File "E:\GPT-SoVITS-beta0128\GPT_SoVITS\AR\data\dataset.py", line 107, in __init__
    self.init_batch()
  File "E:\GPT-SoVITS-beta0128\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero`

**Comment by RVC-Boss** [comment]
日语已经支持了
确保.list文件语种标识为ja
然后音频路径不含中文就可以
