### ISSUE TITLE
点击“开启SoVits训练”报以下错误

### ISSUE THREAD

**Issue by wanghx1121** [RVC-Boss/GPT-SoVITS#405]
"D:\install\conda\envs\GPTSoVits\python.exe" GPT_SoVITS/s2_train.py --config "e:\GPT-SoVITS\TEMP/tmp_s2.json"
INFO:dhxy666:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 8, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/dhxy666'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/dhxy666', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'dhxy666', 'pretrain': None, 'resume_step': None}
Traceback (most recent call last):
  File "e:\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "e:\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 68, in _wrap
    fn(i, *args)
  File "e:\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 75, in run
    dist.init_process_group(
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "D:\install\conda\envs\GPTSoVits\lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Unknown error

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/159092899/9ac6a849-c440-469d-a704-41bfac24be05)

环境信息：
显卡：RTX 4070
python=3.9

麻烦大佬帮忙看看

**Comment by ns2250225** [comment]
跟我遇到的一样，已经解决了，可以参考 #397

**Comment by wanghx1121** [comment]
> 跟我遇到的一样，已经解决了，可以参考 #397

感谢，感谢！~
