### ISSUE TITLE
启动TTS推理webui报错

### ISSUE THREAD

**Issue by Dubnium-105** [RVC-Boss/GPT-SoVITS#408]
ImportError: cannot import name ‘get_num_classes’ from ‘torchmetrics.utilities.data’
在搜索后降级torchmetrics到0.5后出现：
ImportError: cannot import name 'MulticlassAccuracy' from 'torchmetrics.classification'
搜索无果后前来求助
py39 torch2.0 cu118 win10

前：E:\tools\GPT-SoVITS-beta0128>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"E:\tools\GPT-SoVITS-beta0128\runtime\python.exe" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "E:\tools\GPT-SoVITS-beta0128\GPT_SoVITS\inference_webui.py", line 54, in <module>
    from AR.models.t2s_lightning_module import Text2SemanticLightningModule
  File "E:\tools\GPT-SoVITS-beta0128\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 9, in <module>
    from pytorch_lightning import LightningModule
  File "D:\APPDATA\Roaming\Python\Python39\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "D:\APPDATA\Roaming\Python\Python39\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "D:\APPDATA\Roaming\Python\Python39\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "D:\APPDATA\Roaming\Python\Python39\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "D:\APPDATA\Roaming\Python\Python39\site-packages\pytorch_lightning\metrics\utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (E:\tools\GPT-SoVITS-beta0128\runtime\lib\site-packages\torchmetrics\utilities\data.py)

后：
"E:\tools\GPT-SoVITS-beta0128\runtime\python.exe" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "E:\tools\GPT-SoVITS-beta0128\GPT_SoVITS\inference_webui.py", line 54, in <module>
    from AR.models.t2s_lightning_module import Text2SemanticLightningModule
  File "E:\tools\GPT-SoVITS-beta0128\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 10, in <module>
    from AR.models.t2s_model import Text2SemanticDecoder
  File "E:\tools\GPT-SoVITS-beta0128\GPT_SoVITS\AR\models\t2s_model.py", line 19, in <module>
    from torchmetrics.classification import MulticlassAccuracy
ImportError: cannot import name 'MulticlassAccuracy' from 'torchmetrics.classification' (E:\tools\GPT-SoVITS-beta0128\runtime\lib\site-packages\torchmetrics\classification\__init__.py)

**Comment by Dubnium-105** [comment]
删除APPDATA\Roaming\Python\Python39\site-packages解决

**Comment by ZJDqtjs** [comment]
感谢楼主，这个方法也解决了我的问题

![Image](https://github.com/user-attachments/assets/2f7bd113-2930-4a30-8d02-5a09c77556d4)
