### ISSUE TITLE
macOS pro M1 运行python webui.py报错

### ISSUE THREAD

**Issue by kingname** [RVC-Boss/GPT-SoVITS#420]
```bash
Traceback (most recent call last):
  File "/Users/kingname/Projects/GPT-SoVITS/webui.py", line 48, in <module>
    import gradio as gr
  File "/Users/kingname/opt/anaconda3/envs/GPTSoVites/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/kingname/opt/anaconda3/envs/GPTSoVites/lib/python3.9/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/Users/kingname/opt/anaconda3/envs/GPTSoVites/lib/python3.9/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/Users/kingname/opt/anaconda3/envs/GPTSoVites/lib/python3.9/site-packages/gradio_client/documentation.py)
```

**Comment by evpeople** [comment]
pip install gradio_client==0.8.1 使用这个

**Comment by RVC-Boss** [comment]
已更新gradio依赖
