### ISSUE TITLE
一键三连报错No such file or directory: 'logs/xxx/6-name2semantic-0.tsv'

### ISSUE THREAD

**Issue by Silicon7420** [RVC-Boss/GPT-SoVITS#432]
rt

F:\GPT-SoVITS-beta>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Building prefix dict from the default dictionary ...
Loading model from cache F:\GPT-SoVITS-beta\TEMP\jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache F:\GPT-SoVITS-beta\TEMP\jieba.cache
Loading model cost 0.700 seconds.
Prefix dict has been built succesfully.
Loading model cost 0.737 seconds.
Prefix dict has been built succesfully.
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 10, in <module>
    from feature_extractor import cnhubert
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\feature_extractor\__init__.py", line 1, in <module>
    from . import cnhubert, whisper_enc
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\feature_extractor\cnhubert.py", line 3, in <module>
    import librosa
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
Traceback (most recent call last):
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 10, in <module>
    from feature_extractor import cnhubert
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\feature_extractor\__init__.py", line 1, in <module>
    from . import cnhubert, whisper_enc
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\feature_extractor\cnhubert.py", line 3, in <module>
    import librosa
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"F:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 22, in <module>
    import logging, librosa, utils, torch
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\__init__.py", line 77, in <module>
Traceback (most recent call last):
  File "F:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 22, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\utils.py", line 9, in <module>
    import logging, librosa, utils, torch
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 209, in <module>
    import numba
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\__init__.py", line 42, in <module>
    from . import core
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 5, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\convert.py", line 7, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
    from . import notation
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\core\notation.py", line 8, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
    from ..util.exceptions import ParameterError
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\chens\AppData\Roaming\Python\Python39\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
Traceback (most recent call last):
  File "F:\GPT-SoVITS-beta\webui.py", line 614, in open1abc
    with open(semantic_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/6-name2semantic-0.tsv'
ERROR: The process "31652" not found.
ERROR: The process "13300" not found.

**Comment by liuliu1024** [comment]
解决了吗

**Comment by Yangxiaoda1** [comment]
解决了吗

**Comment by donttal** [comment]
解决了吗

**Comment by shihaiyang-world** [comment]
怎么解的呢？6-name2semantic-0.tsv 这个就是不生成...

**Comment by zzk2021** [comment]
同样的问题，之前漏了哪一步？

**Comment by XXXXRT666** [comment]
一键三连

**Comment by 0002kgHg** [comment]
解决了吗？

**Comment by Yangxiaoda1** [comment]
Yes thanks!发自我的 iPhone在 2024年8月8日，14:44，0002kgHg ***@***.***> 写道：﻿
解决了吗？

**Comment by xinbu** [comment]
> Yes thanks!发自我的 iPhone在 2024年8月8日，14:44，0002kgHg ***@***.***> 写道：﻿
> 解决了吗？
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

怎么解决的？
