### ISSUE TITLE
在colab上用不了了吗？（已解决）附问：一键三连过程报错问题

### ISSUE THREAD

**Issue by Treemh** [RVC-Boss/GPT-SoVITS#439]
在colab上运行后并没有像以前一样弹出网址，而是直接把全部代码运行完毕了，这里附上最后一个代码块的运行结果
Traceback (most recent call last):
  File "/content/gpt-sovits/webui.py", line 33, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py)

**Comment by RVC-Boss** [comment]
pip install gradio_client==0.8.1再启动webui试试？

**Comment by Treemh** [comment]
> pip install gradio_client==0.8.1 再启动webui尝试？

成功了，十分感谢QWQ

**Comment by Treemh** [comment]
> pip install gradio_client==0.8.1

还有就是想跟一个问题：在一键三连过程中第一次报错（可能是我的素材有背景音），但是在多次一键三联后又能成功，关于这个又什么办法吗？

**Comment by RVC-Boss** [comment]
更新一下最新的colab脚本应该已经可以了
