### ISSUE TITLE
gpt训练报错这是哪里出问题了呢？

### ISSUE THREAD

**Issue by kessness** [RVC-Boss/GPT-SoVITS#456]
D:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "D:\GPT-SoVITS-beta\TEMP/tmp_s1.yaml"
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 12, in <module>
    from pytorch_lightning import seed_everything
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\utilities\types.py", line 40, in <module>
    from torchmetrics import Metric
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\__init__.py", line 22, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchmetrics\utilities\imports.py", line 54, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\lightning_utilities\core\imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "importlib\__init__.py", line 127, in import_module
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "D:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\GPT-SoVITS-beta\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by kessness** [comment]
window 11
306012g
32G内存

**Comment by RVC-Boss** [comment]
不影响使用吧这个？

**Comment by JK737353** [comment]
我也碰到这个问题了，研究一整天，最后发现是我电脑上没装CUDA。

**Comment by kessness** [comment]
问题解决了，是我的显卡驱动出了问题，重装后问题解决

**Comment by CaptainDP** [comment]
只有CPU，能进行GPT训练吗？也报这个错误

**Comment by maolintao** [comment]
File "D:\AI\GPT-SoVITS-v3lora-20250228\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'D:\AI\GPT-SoVITS-v3lora-20250228\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

笔记本电脑，win11，家庭版，也报这个错误，请问笔记本电脑集成显卡可以跑这个吗，报错解决

**Comment by maolintao** [comment]
已解决，删除GPT-SoVITS-v3lora-20250228\runtime\Lib\site-packages\torchaudio\lib目录下_torchaudio.pyd这个文件的前缀下划线
参考：https://github.com/neonbjb/tortoise-tts/issues/298#issuecomment-2174432438

I just navigated to Python\Python312\Lib\site-packages\torchaudio\lib and removed the _ prefix on torchaudio.pyd. Maybe there's a reason that the underscore was there?
我刚刚导航到 Python\Python312\Lib\site-packages\torchaudio\lib 并删除了 torchaudio.pyd 上的 _ 前缀。也许下划线存在是有原因的？

> File "D:\AI\GPT-SoVITS-v3lora-20250228\runtime\lib\site-packages\torch_ops.py", line 643, in load_library ctypes.CDLL(path) File "ctypes__init__.py", line 374, in **init** FileNotFoundError: Could not find module 'D:\AI\GPT-SoVITS-v3lora-20250228\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> 笔记本电脑，win11，家庭版，也报这个错误，请问笔记本电脑集成显卡可以跑这个吗，报错解决
