### ISSUE TITLE
请问可以通过API来推理吗？

### ISSUE THREAD

**Issue by lazycg0427** [RVC-Boss/GPT-SoVITS#459]
我已经训练了微调模型，现在用webUI可以生成非常满意的语音。接下来我希望可以通过API的方式进行调用。查找文档，没有发现API的调用方法，请问可以支持吗？

**Comment by lazycg0427** [comment]
补充下，我希望可以将微调模型部署在服务器上，封装成API调用。这个有教程吗？

**Comment by RVC-Boss** [comment]
要改一下api.py文件

**Comment by lazycg0427** [comment]
> 要改一下api.py文件

感谢大神回复我啊！！！：）。我是希望把我训练的模型放在autodl上，提供API，方便调用。请问能不能出个教程啊，怎么改这个api.py呢

**Comment by lazycg0427** [comment]
API搞好了，但是推理速度比较慢，查了下原因是调用的CPU，所以改了代码强行走cuda，报错了：raceback (most recent call last):
  File "D:\AI Dev\GPT-SoVITS-beta\api.py", line 215, in <module>
    bert_model = bert_model.to(device)
 File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init     
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
在webUI上运行就没有这个问题，cuda是正常在运行的，所以速度比API要更快一些。请大神帮忙看看

**Comment by Artrajz** [comment]
> AssertionError: Torch not compiled with CUDA enabled

这是没有装GPU版pytorch的缘故吧，安装：
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by Artrajz** [comment]
> AssertionError: Torch not compiled with CUDA enabled

这是没有装GPU版pytorch的缘故吧，安装：
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by AWangji** [comment]
> > 要改一下api.py文件
> 
> 走cpu的API调通了，但是cuda的怎么都报错： INFO] 默认参考音频路径: yuanyuan_ref/biedan_87.WAV [INFO] 默认参考音频文本: 直播结束过后啊，我们的价格会恢复到我们的日常价格，所以宝宝们不要错过！ [INFO] 默认参考音频语种: zh [INFO] 半精: False C:\ProgramData\anaconda3\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. torch.utils._pytree._register_pytree_node( Traceback (most recent call last): File "D:\AI Dev\GPT-SoVITS-beta\api.py", line 215, in bert_model = bert_model.to(device) ^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\anaconda3\Lib\site-packages\transformers\modeling_utils.py", line 2014, in to return super().to(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1152, in to return self._apply(convert) ^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply module._apply(fn) File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply module._apply(fn) File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply module._apply(fn) File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 825, in _apply param_applied = fn(param) ^^^^^^^^^ File "C:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1150, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\anaconda3\Lib\site-packages\torch\cuda__init__.py", line 293, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled
> 
> 请大神安排下DL AUTO上走cuda的API教程吧

请问下调api的版本如何调通的？我一直遇到报错：
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/42883258/3afadcc4-1947-4997-99ce-c5e4bfd343fa)
推理到中间就遇到终止符号停了

**Comment by RVC-Boss** [comment]
api已更新
