### ISSUE TITLE
gpt-train----------error

### ISSUE THREAD

**Issue by anthonyyuan** [RVC-Boss/GPT-SoVITS#461]
Global seed set to 1234
Traceback (most recent call last):
  File "/home/anthony/work/third/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 171, in <module>
    main(args)
  File "/home/anthony/work/third/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 110, in main
    trainer: Trainer = Trainer(
  File "/home/anthony/miniconda3/envs/p10/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/anthony/miniconda3/envs/p10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 420, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/anthony/miniconda3/envs/p10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 183, in __init__
    self._check_config_and_set_final_flags(
  File "/home/anthony/miniconda3/envs/p10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 317, in _check_config_and_set_final_flags
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: Precision '16-mixed' is invalid. Allowed precision values: ('64', '32', '16', 'bf16', 64, 32, 16)

**Comment by LeoHsu0802** [comment]
Hi @anthonyyuan , 
I got the same error when running "1Bb-GPT training", may I know how to fix it?

**Comment by 904557558** [comment]
> Hi @anthonyyuan , I got the same error when running "1Bb-GPT training", may I know how to fix it?

@LeoHsu0802 Hi, I also encountered the same error. My reason is that the version of pytorch-lightning is too low, and the error can be solved by upgrading pytorch-lightning. (pip install pytorch-lightning==2.2.1)
