### ISSUE TITLE
启动 API 时报错 [TypeError: dataclass_field() got an unexpected keyword argument 'init']

### ISSUE THREAD

**Issue by hekatech** [RVC-Boss/GPT-SoVITS#473]
```
$ python api.py
Traceback (most recent call last):
  File "D:\_GPTsovits\GPT-SoVITS-beta\api.py", line 121, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\__init__.py", line 370, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\hf_api.py", line 62, in <module>
    from ._inference_endpoints import InferenceEndpoint, InferenceEndpointType
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\_inference_endpoints.py", line 7, in <module>
    from .inference._client import InferenceClient
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\inference\_client.py", line 56, in <module>
    from huggingface_hub.inference._common import (
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\inference\_common.py", line 51, in <module>
    from ._text_generation import TextGenerationStreamResponse, _parse_text_generation_error
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\inference\_text_generation.py", line 59, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\dataclasses.py", line 250, in dataclass
    return create_dataclass(_cls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\dataclasses.py", line 241, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_dataclasses.py", line 154, in complete_dataclass
    schema = gen_schema.generate_schema(cls, from_dunder_get_core_schema=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 838, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1487, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1488, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiphareth\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 941, in _generate_dc_field_schema
    return core_schema.dataclass_field(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dataclass_field() got an unexpected keyword argument 'init'

```
默认参考音频和标记已经写在 api.py 里了
第一次运行的时候是正常的……关掉重启以后就没办法再打开了

**Comment by hekatech** [comment]
去掉 requirements.txt 里 numba 的版本号之后重装依赖解决了【
