### ISSUE TITLE
在gpt訓練的時候遇到以下錯誤

### ISSUE THREAD

**Issue by aaa71541367** [RVC-Boss/GPT-SoVITS#478]
"C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "C:\Users\user\Desktop\GPT-SoVITS-beta\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 170, in <module>
    main(args)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 146, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 947, in _run
    self.strategy.setup_environment()
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 148, in setup_environment
    self.setup_distributed()
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 199, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\lightning_fabric\utilities\distributed.py", line 290, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "C:\Users\user\Desktop\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: unmatched '}' in format string

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/s1_train.py
试试下载这个文件，覆盖同目录同名文件，再训练GPT@aaa71541367
