### ISSUE TITLE
整合包訓練GPT時出現錯誤:RuntimeError: unmatched '}' in format string

### ISSUE THREAD

**Issue by win10ogod** [RVC-Boss/GPT-SoVITS#48]
```
D:\GPT-SoVITS>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"D:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "D:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 171, in <module>
    main(args)
  File "D:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 147, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 947, in _run
    self.strategy.setup_environment()
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 148, in setup_environment
    self.setup_distributed()
  File "D:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 199, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\lightning_fabric\utilities\distributed.py", line 290, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "D:\GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: unmatched '}' in format string
```

**Comment by PLL-L** [comment]
我也一样，过了很久说超时，batch_size为3，其他默认，询问gpt，检查了端口并无占用，请问怎么解决
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/69779037/d1efc5ca-3b76-49e7-b5e8-ad4396df713f)

**Comment by ioritree** [comment]
same problem.

**Comment by jx06T** [comment]
I am facing the same issue as well.
一樣的問題
os : win11
| Package                   | Version     |
| ------------------------- | ----------- |
| absl-py                   | 2.1.0       |
| addict                    | 2.4.0       |
| aiofiles                  | 23.2.1      |
| aiohttp                   | 3.9.1       |
| aiosignal                 | 1.3.1       |
| aliyun-python-sdk-core    | 2.14.0      |
| aliyun-python-sdk-kms     | 2.16.2      |
| altair                    | 5.2.0       |
| annotated-types           | 0.6.0       |
| anyio                     | 4.2.0       |
| async-timeout             | 4.0.3       |
| attrs                     | 23.2.0      |
| audioread                 | 3.0.1       |
| cachetools                | 5.3.2       |
| certifi                   | 2022.12.7   |
| cffi                      | 1.16.0      |
| chardet                   | 5.2.0       |
| charset-normalizer        | 2.1.1       |
| click                     | 8.1.7       |
| cn2an                     | 0.5.22      |
| colorama                  | 0.4.6       |
| coloredlogs               | 15.0.1      |
| contourpy                 | 1.2.0       |
| crcmod                    | 1.7         |
| cryptography              | 42.0.1      |
| cycler                    | 0.12.1      |
| Cython                    | 0.29.37     |
| datasets                  | 2.16.1      |
| decorator                 | 5.1.1       |
| dill                      | 0.3.7       |
| Distance                  | 0.1.3       |
| editdistance              | 0.6.2       |
| einops                    | 0.7.0       |
| exceptiongroup            | 1.2.0       |
| fastapi                   | 0.109.0     |
| ffmpeg-python             | 0.2.0       |
| ffmpy                     | 0.3.1       |
| filelock                  | 3.9.0       |
| flatbuffers               | 23.5.26     |
| fonttools                 | 4.47.2      |
| frozenlist                | 1.4.1       |
| fsspec                    | 2023.10.0   |
| funasr                    | 0.8.7       |
| future                    | 0.18.3      |
| g2p-en                    | 2.1.0       |
| gast                      | 0.5.4       |
| google-auth               | 2.27.0      |
| google-auth-oauthlib      | 1.2.0       |
| gradio                    | 3.38.0      |
| gradio_client             | 0.8.1       |
| grpcio                    | 1.60.0      |
| h11                       | 0.14.0      |
| hdbscan                   | 0.8.33      |
| httpcore                  | 1.0.2       |
| httpx                     | 0.26.0      |
| huggingface-hub           | 0.20.3      |
| humanfriendly             | 10.0        |
| idna                      | 3.4         |
| importlib-metadata        | 7.0.1       |
| inflect                   | 7.0.0       |
| jaconv                    | 0.3.4       |
| jamo                      | 0.4.1       |
| jieba                     | 0.42.1      |
| jieba_fast                | 0.53        |
| Jinja2                    | 3.1.2       |
| jmespath                  | 0.10.0      |
| joblib                    | 1.3.2       |
| jsonschema                | 4.21.1      |
| jsonschema-specifications | 2023.12.1   |
| kaldiio                   | 2.18.0      |
| kiwisolver                | 1.4.5       |
| librosa                   | 0.9.2       |
| lightning-utilities       | 0.10.1      |
| linkify-it-py             | 2.0.2       |
| llvmlite                  | 0.39.1      |
| Markdown                  | 3.5.2       |
| markdown-it-py            | 2.2.0       |
| MarkupSafe                | 2.1.3       |
| matplotlib                | 3.8.2       |
| mdit-py-plugins           | 0.3.3       |
| mdurl                     | 0.1.2       |
| modelscope                | 1.10.0      |
| mpmath                    | 1.3.0       |
| multidict                 | 6.0.4       |
| multiprocess              | 0.70.15     |
| networkx                  | 3.0         |
| nltk                      | 3.8.1       |
| numba                     | 0.56.4      |
| numpy                     | 1.23.5      |
| oauthlib                  | 3.2.2       |
| onnxruntime               | 1.16.3      |
| orjson                    | 3.9.12      |
| oss2                      | 2.18.4      |
| packaging                 | 23.2        |
| pandas                    | 2.2.0       |
| Pillow                    | 9.3.0       |
| pip                       | 23.3.2      |
| platformdirs              | 4.1.0       |
| pooch                     | 1.8.0       |
| proces                    | 0.1.7       |
| protobuf                  | 4.23.4      |
| psutil                    | 5.9.8       |
| pyarrow                   | 15.0.0      |
| pyarrow-hotfix            | 0.6         |
| pyasn1                    | 0.5.1       |
| pyasn1-modules            | 0.3.0       |
| pycparser                 | 2.21        |
| pycryptodome              | 3.20.0      |
| pydantic                  | 2.5.3       |
| pydantic_core             | 2.14.6      |
| pydub                     | 0.25.1      |
| pyopenjtalk               | 0.3.3       |
| pyparsing                 | 3.1
If anyone has insights or solutions, I would greatly appreciate the help. Thank you! 
如果有人有見解或解決方案，我將非常感激。 謝謝！

**Comment by julian0703** [comment]
同樣問題
OS: Win11, CUDA 11.8

以下組合都試過問題還是無法解決
Python 3.9, Python 3.10
PyTorch 2.0.1, PyTorch 2.1.2

**Comment by julian0703** [comment]
我找到暫時的解法了
打開GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py
找到這行start_daemon = rank == 0大約在175行
下方增加一行hostname = "localhost"就可以了

**Comment by ioritree** [comment]
> 我找到暫時的解法了 打開GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py 找到這行start_daemon = rank == 0大約在175行 下方增加一行hostname = "localhost"就可以了

但是執行go-webui.bat會報錯...有好有壞

**Comment by DruidTin** [comment]
非常感謝!! 可以用!

**Comment by fgod999** [comment]
> 我找到暫時的解法了 打開GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py 找到這行start_daemon = rank == 0大約在175行 下方增加一行hostname = "localhost"就可以了

已加入，仍然無效

**Comment by julian0703** [comment]
是不是沒有縮排？增加的那行開頭要對齊上一行start_daemon = rank == 0
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/19199590/06419655-83af-4846-82eb-a14de4e55a50)

**Comment by RVC-Boss** [comment]
（遇到这个问题的大家）你们ping 127.0.0.1和ping localhost是同样的结果吗？
看来是地址只能写localhost而不能写127.0.0.1导致的？

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/59f35adad85815df27e9c6b33d420f5ebfd8376b
理论上该commit修复了楼主的问题。如果还不行试试楼上添加hostname = "localhost"的方法。

**Comment by mohancheng** [comment]
"C:\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "C:\GPT-SoVITS-beta\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "C:\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 170, in <module>
    main(args)
  File "C:\GPT-SoVITS-beta\GPT_SoVITS\s1_train.py", line 146, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 947, in _run
    self.strategy.setup_environment()
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 148, in setup_environment
    self.setup_distributed()
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 199, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\lightning_fabric\utilities\distributed.py", line 290, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: unmatched '}' in format string

請問這個該怎麼解決，我按照樓主的方式處理過了，但依舊報錯，還請幫幫忙

**Comment by fgod999** [comment]
其實我用這方法依然無解
但是目前最新的版本就修正了
去更新版本吧

**Comment by light1943** [comment]
> （遇到这个问题的大家@win10ogod @light1943 ）你们ping 127.0.0.1和ping localhost是同样的结果吗？ 看来是地址只能写localhost而不能写127.0.0.1导致的？

是的localhost就是127.0.0.1，但在這裡地址只能寫localhost，寫IP 127.0.0.1會出錯。
這是torch的一個奇怪bug，且似乎只在Windows環境下出現。
改成localhost能解是最近在其他地方有人找到的解法。

新的版本59f35ad已經修復這個問題，不需要修改torch的rendezvous.py了。
感謝幫忙！

**Comment by mohancheng** [comment]
> 其實我用這方法依然無解 但是目前最新的版本就修正了 去更新版本吧

我也用了新版本，依旧无解.....我都觉得是不是我跟这软件八字不合

**Comment by light1943** [comment]
> 我一直在更行版本，但这问题依旧存在，依旧跟我上面遇到的报错一模一样，我真的不知道哪里出错
如果你照我的方式處理過了，報错應該會變成line 177而不是line 176，可以檢查是不是改错檔案了。
如果改對了，也更新到59f35ad之後的版本還是報錯，那可能就要在自己找解法了。
畢竟torch這個奇怪的問題也沒有人真正的去解析它，只知道在某些環境下hostname不吃ip。

File "C:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
return TCPStore(
RuntimeError: unmatched '}' in format string
