### ISSUE TITLE
WAV格式文件出现：FileNotFoundError: [Errno 2] No such file or directory: 'logs/sibug/2-name2text-0.txt'报错

### ISSUE THREAD

**Issue by HiSweetie** [RVC-Boss/GPT-SoVITS#480]
Intel MacBook Pro(2019款) 16inch  i7 9750 显卡：AMD Radeon Pro 5300M

系统版本为MacOS 12.7.3 (21H1015)
切片之后的文件均为.wav后缀
依次执行一键三连操作时，点按speech-to-text按钮时出现如下报错：
LookupError: 
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict

  Searched in:
    - '/Users/mac_for_yu/nltk_data'
    - '/Users/mac_for_yu/miniconda3/envs/GPTSoVits/nltk_data'
    - '/Users/mac_for_yu/miniconda3/envs/GPTSoVits/share/nltk_data'
    - '/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

Traceback (most recent call last):
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/mac_for_yu/Desktop/Software/AI_TTS/GPT-SoVITS-main3/webui.py", line 388, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/sibug/2-name2text-0.txt'
"/Users/mac_for_yu/miniconda3/envs/GPTSoVits/bin/python3" GPT_SoVITS/prepare_datasets/1-get-text.py
"/Users/mac_for_yu/miniconda3/envs/GPTSoVits/bin/python3" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/Users/mac_for_yu/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/mac_for_yu/Desktop/Software/AI_TTS/GPT-SoVITS-main3/webui.py", line 388, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/sibug/2-name2text-0.txt'

<img width="1517" alt="截屏2024-02-14 11 47 41" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/65219561/a9beb9bd-4a79-440b-aba7-bd4b2d27aff9">

之前我在我的Windows电脑上使用一键整合包就没问题，但目前我主要是用Mac办公，希望懂行的朋友能帮忙解决一下这个问题。

**Comment by Lion-Wu** [comment]
创建一个python文件：
```
import nltk
nltk.download('cmudict')
```
然后运行它，会下载一个nltk文件。之后重新运行webui再试试
我运行的时候这个文件是会自动下载的，不知道怎么回事，有很多人没下载
另外[这里](https://github.com/RVC-Boss/GPT-SoVITS/issues/165#issuecomment-1922731928)有人与你相同的配置在GPT训练的时候显示没有GPU可训练，如果出现这个问题的话麻烦跟我说一声，我再看看

**Comment by HiSweetie** [comment]
谢谢。我想我已经解决了一键三连的那个问题，不过，正如你所料，我在进行GPT训练时提示：No supported gpu backend found!<img width="941" alt="截屏2024-02-14 16 30 15" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/65219561/ea0e0ba1-589e-4a1c-b2df-6b55bc1fe2db">

这样的话我在我的这台Mac上就只能先用CPU进行训练了吗？或者是我用我的Windows笔记本电脑训练完之后把训练好的模型拷贝到Mac上使用？这样可行吗？

**Comment by Lion-Wu** [comment]
看来估计是pytorch_lightning的问题，你可以先尝试把项目中GPT_SoVITS/s1_train.py中第112行中的gpu改成cpu看看应该能暂时解决问题

**Comment by HiSweetie** [comment]
我在进行SoVITS训练时还遇到了如下问题：

RuntimeError: MPS backend out of memory (MPS allocated: 6.64 GB, other allocations: 134.57 MB, max allowed: 6.77 GB). Tried to allocate 10.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
在Intel的Mac上，这个程序运行时貌似会占用大量的内存，不过我的Windows笔记本配置也不是最新的，Win本也是i7 9750的CPU，显卡是2070 8G显存，Windows和Mac同样都是16G的内存，但Windows上就没出现这样的情况。

**Comment by Lion-Wu** [comment]
MPS上已知是有内存泄漏的问题的，这个还没找到解决方法…
另外最近加了个DPO协同训练，使得训练显存翻倍了
所以用AMD显卡来训练可能比较难了吧

**Comment by ThreeManager785** [comment]
> 谢谢。我想我已经解决了一键三连的那个问题，不过，正如你所料，我在进行GPT训练时提示：No supported gpu backend found!<img alt="截屏2024-02-14 16 30 15" width="941" src="https://private-user-images.githubusercontent.com/65219561/304669749-ea0e0ba1-589e-4a1c-b2df-6b55bc1fe2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDEyOTgsIm5iZiI6MTcwOTMwMDk5OCwicGF0aCI6Ii82NTIxOTU2MS8zMDQ2Njk3NDktZWEwZTBiYTEtNTg5ZS00YTFjLWIyZGYtNmI1NWJjMWZlMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEzNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmIyNDYwZmU4YmRiNmViZDk1MTQ1OWQyNmE0NmViYmE2MTdmNTllMTk5NGU4YjUxMTJlMWYxYmI2Zjk0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vp_-HVV1H04_NPVJc5keAO6yYqxVRHpipJt5zOJuox4">
> 
> 这样的话我在我的这台Mac上就只能先用CPU进行训练了吗？或者是我用我的Windows笔记本电脑训练完之后把训练好的模型拷贝到Mac上使用？这样可行吗？

我以前忘记了怎么解决的这个问题，但是Mac肯定可以。我现在也在试图解决这个问题。

**Comment by arctan90** [comment]
Same err happened for me. 
Win10 System. Resolved by downloading  cmudict
```
> import nltk
> nltk.download('cmudict')
```
Suggesting add this step to Readme.MD.  :D

---
> 创建一个python文件：
> 
> ```
> import nltk
> nltk.download('cmudict')
> ```
> 
> 然后运行它，会下载一个nltk文件。之后重新运行webui再试试 我运行的时候这个文件是会自动下载的，不知道怎么回事，有很多人没下载 另外[这里](https://github.com/RVC-Boss/GPT-SoVITS/issues/165#issuecomment-1922731928)有人与你相同的配置在GPT训练的时候显示没有GPU可训练，如果出现这个问题的话麻烦跟我说一声，我再看看

**Comment by Lion-Wu** [comment]
> Same err came up to me. A brand new Win10 System. Resolved by downloading cmudict
> 
> ```
> > import nltk
> > nltk.download('cmudict')
> ```
> 
> Suggesting add this step to Readme.MD. :D
> 
> > 创建一个python文件：
> > ```
> > import nltk
> > nltk.download('cmudict')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后运行它，会下载一个nltk文件。之后重新运行webui再试试 我运行的时候这个文件是会自动下载的，不知道怎么回事，有很多人没下载 另外[这里](https://github.com/RVC-Boss/GPT-SoVITS/issues/165#issuecomment-1922731928)有人与你相同的配置在GPT训练的时候显示没有GPU可训练，如果出现这个问题的话麻烦跟我说一声，我再看看

I think it might be caused by poor network connection, because the file will be downloaded automatically when running the project for the first time.

**Comment by xiaolongww** [comment]
可以通过这种方式查看是否有nltk：
import nltk
print("nltk data path:", nltk.data.path)  

通过这种方式，我知道了在C:\Users\Administrator\AppData\Roaming\ntlk_data有这部分数据；而且当另一台计算机出现Resource cmudict not found.Please use the NLTK Downloader to obtain the resource:  时，我直接把这个文件夹的数据拷过去即可
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/1dfee6bf-abf2-406e-b3a3-538b3bbe1e4c)

**Comment by RVC-Boss** [comment]
nltk库缺文件的问题可以参考一下楼上和历史issue的解法
