### ISSUE TITLE
进行 SoVITS 训练时出现分布式网络错误

### ISSUE THREAD

**Issue by xiejianchao** [RVC-Boss/GPT-SoVITS#486]
前边步骤都是正确的，在进行 SoVITS 训练时出现错误，有可能是哪里的问题呢？
日志如下：

```
"D:\Dev\anaconda3\envs\GPTSoVits\python.exe" GPT_SoVITS/s2_train.py --config "D:\Dev\github\GPT-SoVITS\TEMP/tmp_s2.json"INFO:xjc:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 8, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/xjc'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/xjc', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'xjc', 'pretrain': None, 'resume_step': None}
Traceback (most recent call last):
  File "D:\Dev\github\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "D:\Dev\github\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 68, in _wrap
    fn(i, *args)
  File "D:\Dev\github\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 75, in run
    dist.init_process_group(
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "D:\Dev\anaconda3\envs\GPTSoVits\lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Unknown error
```

`本地环境如下：`
```
cuda:12.3
pytorch:2.2.0+cu121
```

`nvidia-smi`
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.12                 Driver Version: 546.12       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P8               4W /  80W |   1752MiB /  8188MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4304    C+G   ...__8wekyb3d8bbwe\WindowsTerminal.exe    N/A      |
|    0   N/A  N/A      7784    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A      9580    C+G   ....0_x64__8wekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     11004    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A     11292    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     13272    C+G   ...n\121.0.2277.112\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     14540    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     14740    C+G   ...n\121.0.2277.112\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     20492    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     22368    C+G   ...oogle\Chrome\Application\chrome.exe    N/A      |
|    0   N/A  N/A     23092    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     25784    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     28704    C+G   ...s (x86)\Tencent\QQMusic\QQMusic.exe    N/A      |
+---------------------------------------------------------------------------------------+
```

`nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:30:42_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

**Comment by SapphireLab** [comment]
#433

**Comment by xiejianchao** [comment]
> #433

多谢。
