### ISSUE TITLE
GPT 训练报错 ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by gaoxigang** [RVC-Boss/GPT-SoVITS#496]
SoVITS训练 正常结束，GPT 训练时 报错，请大佬看下是什么问题呢？

"E:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "E:\GPT-SoVITS\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 16
phoneme_data_len: 16
                              item_name                                     semantic_audio
0   2月15日.WAV_0000000000_0000181440.wav  658 466 1013 964 964 51 978 694 354 868 197 19...
1   2月15日.WAV_0000402560_0000595840.wav  214 171 382 752 752 748 748 272 177 404 441 10...
2   2月15日.WAV_0000816960_0001041920.wav  991 135 619 608 655 81 700 409 9 289 904 953 5...
3   2月15日.WAV_0001243200_0001423040.wav  1012 398 165 165 165 446 798 798 820 732 125 4...
4   2月15日.WAV_0001643200_0001887040.wav  114 477 619 126 984 803 219 522 9 345 232 562 ...
5   2月15日.WAV_0002175360_0002373760.wav  323 8 90 509 509 278 668 687 318 885 745 438 5...
6   2月15日.WAV_0002609920_0002789120.wav  520 72 72 214 184 449 449 702 702 702 30 901 1...
7   2月15日.WAV_0002992000_0003207360.wav  54 271 490 32 142 490 885 885 76 530 505 149 2...
8   2月15日.WAV_0000220800_0000393280.wav  1012 171 290 171 663 873 449 245 303 608 665 5...
9   2月15日.WAV_0000616640_0000816960.wav  913 424 152 712 152 895 830 480 481 481 481 74...
10  2月15日.WAV_0001041920_0001214080.wav  520 53 53 53 72 967 248 713 898 893 893 204 61...
11  2月15日.WAV_0001443200_0001643200.wav  54 474 152 895 898 893 71 962 462 803 743 297 ...
12  2月15日.WAV_0001887040_0002175360.wav  75 210 121 591 591 157 60 831 896 831 545 756 ...
13  2月15日.WAV_0002373760_0002566720.wav  634 278 454 436 8 396 161 467 467 712 610 893 ...
14  2月15日.WAV_0002808960_0002986560.wav  1012 919 464 464 112 36 798 866 392 826 791 93...
15  2月15日.WAV_0003207360_0003456000.wav  248 135 239 252 898 655 532 532 212 1013 948 8...
Traceback (most recent call last):
  File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 171, in <module>
    main(args)
  File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 147, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\data_module.py", line 29, in setup
    self._train_dataset = Text2SemanticDataset(
  File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 107, in __init__
    self.init_batch()
  File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by idolf** [comment]
一键三连后如果报`RuntimeError: Failed to load audio: You input a wrong audio path that does not exists, please fix it!`，就把1a里的`训练集音频文件目录`填上

**Comment by Danny0802** [comment]
> SoVITS训练 正常结束，GPT 训练时 报错，请大佬看下是什么问题呢？
> 
> ## "E:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "E:\GPT-SoVITS\TEMP/tmp_s1.yaml"
> Seed set to 1234
> Using 16bit Automatic Mixed Precision (AMP)
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> 
> ckpt_path: None
> [rank: 0] Seed set to 1234
> Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
> ## distributed_backend=gloo
> All distributed processes registered. Starting with 1 processes
> semantic_data_len: 16 phoneme_data_len: 16 item_name semantic_audio 0 2月15日.WAV_0000000000_0000181440.wav 658 466 1013 964 964 51 978 694 354 868 197 19... 1 2月15日.WAV_0000402560_0000595840.wav 214 171 382 752 752 748 748 272 177 404 441 10... 2 2月15日.WAV_0000816960_0001041920.wav 991 135 619 608 655 81 700 409 9 289 904 953 5... 3 2月15日.WAV_0001243200_0001423040.wav 1012 398 165 165 165 446 798 798 820 732 125 4... 4 2月15日.WAV_0001643200_0001887040.wav 114 477 619 126 984 803 219 522 9 345 232 562 ... 5 2月15日.WAV_0002175360_0002373760.wav 323 8 90 509 509 278 668 687 318 885 745 438 5... 6 2月15日.WAV_0002609920_0002789120.wav 520 72 72 214 184 449 449 702 702 702 30 901 1... 7 2月15日.WAV_0002992000_0003207360.wav 54 271 490 32 142 490 885 885 76 530 505 149 2... 8 2月15日.WAV_0000220800_0000393280.wav 1012 171 290 171 663 873 449 245 303 608 665 5... 9 2月15日.WAV_0000616640_0000816960.wav 913 424 152 712 152 895 830 480 481 481 481 74... 10 2月15日.WAV_0001041920_0001214080.wav 520 53 53 53 72 967 248 713 898 893 893 204 61... 11 2月15日.WAV_0001443200_0001643200.wav 54 474 152 895 898 893 71 962 462 803 743 297 ... 12 2月15日.WAV_0001887040_0002175360.wav 75 210 121 591 591 157 60 831 896 831 545 756 ... 13 2月15日.WAV_0002373760_0002566720.wav 634 278 454 436 8 396 161 467 467 712 610 893 ... 14 2月15日.WAV_0002808960_0002986560.wav 1012 919 464 464 112 36 798 866 392 826 791 93... 15 2月15日.WAV_0003207360_0003456000.wav 248 135 239 252 898 655 532 532 212 1013 948 8... Traceback (most recent call last): File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 171, in main(args) File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 147, in main trainer.fit(model, data_module, ckpt_path=ckpt_path) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit call._call_and_handle_interrupt( File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch return function(*args, **kwargs) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl self._run(model, ckpt_path=ckpt_path) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run call._call_setup_hook(self) # allow user to setup lightning_module in accelerator environment File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook _call_lightning_datamodule_hook(trainer, "setup", stage=fn) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook return fn(*args, **kwargs) File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\data_module.py", line 29, in setup self._train_dataset = Text2SemanticDataset( File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 107, in **init** self.init_batch() File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch for _ in range(max(2, int(min_num / leng))): ZeroDivisionError: division by zero

解决了吗？如果解决了是怎么解决的？

**Comment by gaoxigang** [comment]
> > SoVITS训练 正常结束，GPT 训练时 报错，请大佬看下是什么问题呢？
> > ## "E:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "E:\GPT-SoVITS\TEMP/tmp_s1.yaml"
> > Seed set to 1234
> > Using 16bit Automatic Mixed Precision (AMP)
> > GPU available: True (cuda), used: True
> > TPU available: False, using: 0 TPU cores
> > IPU available: False, using: 0 IPUs
> > HPU available: False, using: 0 HPUs
> > ckpt_path: None
> > [rank: 0] Seed set to 1234
> > Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
> > ## distributed_backend=gloo
> > All distributed processes registered. Starting with 1 processes
> > semantic_data_len: 16 phoneme_data_len: 16 item_name semantic_audio 0 2月15日.WAV_0000000000_0000181440.wav 658 466 1013 964 964 51 978 694 354 868 197 19... 1 2月15日.WAV_0000402560_0000595840.wav 214 171 382 752 752 748 748 272 177 404 441 10... 2 2月15日.WAV_0000816960_0001041920.wav 991 135 619 608 655 81 700 409 9 289 904 953 5... 3 2月15日.WAV_0001243200_0001423040.wav 1012 398 165 165 165 446 798 798 820 732 125 4... 4 2月15日.WAV_0001643200_0001887040.wav 114 477 619 126 984 803 219 522 9 345 232 562 ... 5 2月15日.WAV_0002175360_0002373760.wav 323 8 90 509 509 278 668 687 318 885 745 438 5... 6 2月15日.WAV_0002609920_0002789120.wav 520 72 72 214 184 449 449 702 702 702 30 901 1... 7 2月15日.WAV_0002992000_0003207360.wav 54 271 490 32 142 490 885 885 76 530 505 149 2... 8 2月15日.WAV_0000220800_0000393280.wav 1012 171 290 171 663 873 449 245 303 608 665 5... 9 2月15日.WAV_0000616640_0000816960.wav 913 424 152 712 152 895 830 480 481 481 481 74... 10 2月15日.WAV_0001041920_0001214080.wav 520 53 53 53 72 967 248 713 898 893 893 204 61... 11 2月15日.WAV_0001443200_0001643200.wav 54 474 152 895 898 893 71 962 462 803 743 297 ... 12 2月15日.WAV_0001887040_0002175360.wav 75 210 121 591 591 157 60 831 896 831 545 756 ... 13 2月15日.WAV_0002373760_0002566720.wav 634 278 454 436 8 396 161 467 467 712 610 893 ... 14 2月15日.WAV_0002808960_0002986560.wav 1012 919 464 464 112 36 798 866 392 826 791 93... 15 2月15日.WAV_0003207360_0003456000.wav 248 135 239 252 898 655 532 532 212 1013 948 8... Traceback (most recent call last): File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 171, in main(args) File "E:\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 147, in main trainer.fit(model, data_module, ckpt_path=ckpt_path) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit call._call_and_handle_interrupt( File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch return function(*args, **kwargs) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl self._run(model, ckpt_path=ckpt_path) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run call._call_setup_hook(self) # allow user to setup lightning_module in accelerator environment File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook _call_lightning_datamodule_hook(trainer, "setup", stage=fn) File "E:\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook return fn(*args, **kwargs) File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\data_module.py", line 29, in setup self._train_dataset = Text2SemanticDataset( File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 107, in **init** self.init_batch() File "E:\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch for _ in range(max(2, int(min_num / leng))): ZeroDivisionError: division by zero
> 
> 解决了吗？如果解决了是怎么解决的？

貌似跟数据集也有关系，换了别的数据是可以的

**Comment by cjdiaz98** [comment]
Running into same. Seems due to 4-cnhubert and 5-wav32k folders being empty. Not sure what these folders are for though
