### ISSUE TITLE
RuntimeError: Parent directory logs  does not exist.

### ISSUE THREAD

**Issue by zhangzhiguo0603** [RVC-Boss/GPT-SoVITS#498]
```
H:\GPT-SoVITS-beta\output\slicer_opt/2月1日(2).MP3_0001868160_0002058240.wav|slicer_opt|ZH|我刚才说这一路走来是吧，原来 有一个有一个啊一九九。 Traceback (most recent call last):
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 103, in <module>
    name2go(wav_name)
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 93, in name2go
    my_save(ssl,hubert_path )
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 39, in my_save
    torch.save(fea,tmp_path)
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory logs/徐大夫第二次/4-cnhubert does not exist.
```

**Comment by zhangzhiguo0603** [comment]
这个需要怎么解决，没在问题中搜到过。

**Comment by zhangzhiguo0603** [comment]
```
H:\GPT-SoVITS-beta\output\slicer_opt/2月1日(2).MP3_0001868160_0002058240.wav|slicer_opt|ZH|我刚才说这一路走来是吧，原来 有一个有一个啊一九九。 Traceback (most recent call last):
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 103, in <module>
    name2go(wav_name)
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 93, in name2go
    my_save(ssl,hubert_path )
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 39, in my_save
    torch.save(fea,tmp_path)
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory logs/徐大夫第二次/4-cnhubert does not exist.
```

**Comment by zhangzhiguo0603** [comment]
RuntimeError: Parent directory logs

**Comment by zhangzhiguo0603** [comment]
I’d appreciate it if you could help me.

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/prepare_datasets/1-get-text.py
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
更新这2个文件后重新一键三连。

**Comment by zhangzhiguo0603** [comment]
前面确实解决了，但是SoVITS训练时又出现了这个类似报错，然后同样是替换了GPT_SoVITS\s2_train.py和GPT_SoVITS\utils.py文件，但是还是出现下面报错。

```
INFO:徐大夫第二次:Saving model and optimizer state at iteration 4 to logs/徐大夫第二次/logs_s2\G_233333333333.pth
Traceback (most recent call last):
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 254, in run
    train_and_evaluate(
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\s2_train.py", line 470, in train_and_evaluate
    utils.save_checkpoint(
  File "H:\GPT-SoVITS-beta\GPT_SoVITS\utils.py", line 78, in save_checkpoint
    torch.save(
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory logs/徐大夫第二次 does not exist.
```

**Comment by zhangzhiguo0603** [comment]
前面还有一些报错信息，麻烦开发者大佬查阅。
```
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\optim\lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
0it [00:00, ?it/s]H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:1307] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator ())
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\functional.py:641: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\EmptyTensor.cpp:32.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
H:\GPT-SoVITS-beta\runtime\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 9, 96], strides() = [57120, 96, 1]
bucket_view.sizes() = [1, 9, 96], strides() = [864, 96, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:337.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
```
