### ISSUE TITLE
进行语义token提取时报错

### ISSUE THREAD

**Issue by lanlve** [RVC-Boss/GPT-SoVITS#54]
pytorch2.1.0  py310  cu118  ubuntu22系统环境
文本内容和SSL自监督特征提取都能正常运行 但是进行语义token提取时直接报错

"/opt/conda/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"/opt/conda/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
Traceback (most recent call last):
  File "/root/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 42, in <module>
    hps = utils.get_hparams_from_file(s2config_path)
AttributeError: module 'utils' has no attribute 'get_hparams_from_file'
Traceback (most recent call last):
  File "/root/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 42, in <module>
    hps = utils.get_hparams_from_file(s2config_path)
AttributeError: module 'utils' has no attribute 'get_hparams_from_file'

**Comment by jlxylt123** [comment]
python utils库和文件utils冲突了，直接pip uninstall utils就好了
