### ISSUE TITLE
还是go-webui.bat无法运行的问题

### ISSUE THREAD

**Issue by 025nju** [RVC-Boss/GPT-SoVITS#542]
输出如下：

E:\GPT-SoVITS-beta0217>runtime\python.exe webui.py
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\webui.py", line 4, in <module>
    import json,yaml,warnings,torch
  File "E:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "E:\GPT-SoVITS-beta0217\runtime\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

E:\GPT-SoVITS-beta0217>pause
请按任意键继续. . .

成功运行过 pip install -r requirements.txt，还是不行。
各位有遇到过吗？谢谢。

**Comment by SapphireLab** [comment]
不知你是什么系统？以及之前是否安装过 32 位的 python？

**Comment by 025nju** [comment]
> 不知你是什么系统？以及之前是否安装过 32 位的 python？

win11  64位的系统，Python 3.9.1

**Comment by MatthewHA233** [comment]
我也遇到了这个问题

**Comment by 385766470** [comment]
G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>runtime\python.exe webui.py
Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\webui.py", line 48, in <module>
    import gradio as gr
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>pause
请按任意键继续. . .
今天突然遇到这个情况，请大佬帮忙解答一下

**Comment by RVC-Boss** [comment]
已修复
