### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by Laixinsz** [RVC-Boss/GPT-SoVITS#555]
(GPTSoVits) [root@localhost GPTSoVits]# python GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/GPTSoVits/GPT_SoVITS/inference_webui.py", line 55, in <module>
    import librosa, torch
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import decompose
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/librosa/decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/sklearn/__init__.py", line 83, in <module>
    from . import (
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /home/root/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/sklearn/__check_build:
__init__.py               _check_build.cpython-39-x86_64-linux-gnu.so__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

**Comment by liuliu1024** [comment]
请问解决了吗

**Comment by Laixinsz** [comment]
> 请问解决了吗

centos直接启动inference_webui会报错，现在直接用api.py启动，直接调api可以用。
