### ISSUE TITLE
更新后， 系统找不到指定的文件

### ISSUE THREAD

**Issue by werran2** [RVC-Boss/GPT-SoVITS#558]
推理的时候

Traceback (most recent call last):
  File "F:\GPT-SoVITS\tools\my_utils.py", line 17, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "F:\GPT-SoVITS\tools\my_utils.py", line 17, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\GPT-SoVITS\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\GPT-SoVITS\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "F:\GPT-SoVITS\runtime\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "F:\GPT-SoVITS\GPT_SoVITS\inference_webui.py", line 407, in get_tts_wav
    refer = get_spepc(hps, ref_wav_path)  # .to(device)
  File "F:\GPT-SoVITS\GPT_SoVITS\inference_webui.py", line 187, in get_spepc
    audio = load_audio(filename, int(hps.data.sampling_rate))
  File "F:\GPT-SoVITS\tools\my_utils.py", line 23, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] 系统找不到指定的文件。

**Comment by FURYFOR** [comment]
请问是如何解决的呢？

**Comment by zeushera140** [comment]
有解决办法么？
