### ISSUE TITLE
OSError: AF_UNIX path too long 

### ISSUE THREAD

**Issue by liuliu1024** [RVC-Boss/GPT-SoVITS#572]
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/work/anaconda3/envs/gouwei-env/gptSoVits_torch_211/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long

**Comment by XXXXRT666** [comment]
路径太长
