### ISSUE TITLE
0c-中文批量离线ASR工具

### ISSUE THREAD

**Issue by ZiJuySHI** [RVC-Boss/GPT-SoVITS#576]
在进行“0c-中文批量离线ASR工具”时，他提示了“ASR任务完成, 查看终端进行下一步”但是实际是没有生成文件的
且报错内容为“Traceback (most recent call last):
  File "/Users/zijuys/GPT-SoVITS/tools/asr/funasr_asr.py", line 17, in <module>
    model = AutoModel(
  File "/Users/zijuys/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 92, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/Users/zijuys/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 185, in build_model
    load_pretrained_model(
  File "/Users/zijuys/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/train_utils/load_pretrained_model.py", line 99, in load_pretrained_model
    src_state = torch.load(path, map_location=map_location)
  File "/Users/zijuys/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/zijuys/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.”

MacBook Pro
16-inch, 2019
2.3 GHz 八核Intel Core i9
Intel UHD Graphics 630 1536 MB
16 GB 2667 MHz DDR4

**Comment by LauraGPT** [comment]
What is you funasr version?

**Comment by zhangyue2709** [comment]
+1 same bug, centos 9上一样报错

**Comment by zhangyue2709** [comment]
请问你们的问题解决了吗

**Comment by shai2** [comment]
删除掉文件夹内的东西 执行自动下载  感觉资源有问题  遇到过吗
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/24568088/55152768-ad7e-44a2-9e8c-3550be6823ef)

**Comment by xiao-xingshi** [comment]
解决了吗，MacOS一样的问题

**Comment by dakun333** [comment]
我遇到了同样的问题，已经解决。问题原因是使用git clone https://www.modelscope.cn/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git，克隆的model.pt文件不是原文件是损坏的，日志里面也能看到是加载它引起的，我们只需要去对应目录里面把三个文件夹下面的model.pt，删除后重新下载就好了。eg:wget -c https://modelscope.cn/api/v1/models/iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/repo\?Revision\=master\&FilePath\=model.pt
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/42396024/f98b1c8a-8774-4a45-b426-9008c2020b06)
