### ISSUE TITLE
最后一步了，开启SoVITS训练时，总是报这个错

### ISSUE THREAD

**Issue by leon-ch** [RVC-Boss/GPT-SoVITS#583]
这是报错信息，batch数据在下面
Traceback (most recent call last):
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 600, in <module>
    main()
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 56, in main
    mp.spawn(
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 254, in run
    train_and_evaluate(
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/s2_train.py", line 299, in train_and_evaluate
    for batch_idx, (
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/ENTER/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/module/data_utils.py", line 190, in __call__
    torch.LongTensor([x[1].size(1) for x in batch]),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenhao/Documents/Python/OpenSource/GPT-SoVITS/GPT_SoVITS/module/data_utils.py", line 190, in <listcomp>
    torch.LongTensor([x[1].size(1) for x in batch]),
                      ^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

打印出来的batch数据感觉很奇怪
[(tensor([[[ 0.0591,  0.0886,  0.0907,  ..., -0.0054, -0.0870, -0.0870],
         [ 0.0806,  0.2927,  0.3062,  ...,  0.0289,  0.2507,  0.2507],
         [ 0.0374,  0.0919,  0.0940,  ...,  0.0439,  0.0238,  0.0238],
         ...,
         [ 0.0176, -0.2179, -0.2151,  ...,  0.1406,  0.1003,  0.1003],
         [-0.0017, -0.1947, -0.1869,  ...,  0.1085,  0.0553,  0.0553],
         [-0.0515, -0.0130, -0.0058,  ...,  0.0510,  0.0850,  0.0850]]],
       dtype=torch.float16), tensor([2.2809e+00+0.0000e+00j, 1.1657e+00+5.4116e-01j, 3.3823e-01+1.7427e+00j,
         ..., 3.7124e-04-1.8959e-03j, 3.0137e-03-1.4698e-04j,
        7.7841e-03+0.0000e+00j]), tensor([[0.0000e+00, 0.0000e+00, 3.0518e-05,  ..., 2.1667e-03, 2.8687e-03,
         2.1362e-03]]), tensor([317., 196., 155., 142., 122., 119., 122., 100., 122., 119., 225.,  97.,
        225., 144.,   1., 319., 108., 225., 144., 320., 212., 122., 230., 221.,
        176., 127., 134., 127., 107., 124., 164., 222.,  99.,   1., 125., 256.,
        224., 134., 320., 240., 221., 176., 252., 235., 316., 108., 127., 107.,
        124., 164.,   3.]))]

**Comment by leon-ch** [comment]
救命啊，有兄弟遇到过这个吗？

**Comment by shaooping** [comment]
你试着调整一下batch_size，为保存频率的倍数

**Comment by zhangyue2709** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by RVC-Boss** [comment]
fixed
