### ISSUE TITLE
执行ASR时报错  cannot import name 'CTC' from 'funasr.models.ctc' (N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\models\ctc\__init__.py)

### ISSUE THREAD

**Issue by hqqttjiang** [RVC-Boss/GPT-SoVITS#599]
"N:\AI\GPT-SoVITS\runtime\python.exe" tools/asr/fasterwhisper_asr.py -i "N:\AI\GPT-SoVITS\output\slicer_opt" -o "output/asr_opt" -s medium.en -l en -p float16
If you want use h5py dataset, please pip install h5py, and try it again
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
Traceback (most recent call last):
  File "N:\AI\GPT-SoVITS\tools\asr\fasterwhisper_asr.py", line 12, in <module>
    from tools.asr.funasr_asr import only_asr
  File "N:\AI\GPT-SoVITS\tools\asr\funasr_asr.py", line 8, in <module>
    from funasr import AutoModel
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\__init__.py", line 31, in <module>
    import_submodules(__name__)
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\__init__.py", line 28, in import_submodules
    results.update(import_submodules(name))
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\__init__.py", line 28, in import_submodules
    results.update(import_submodules(name))
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\__init__.py", line 18, in import_submodules
    package = importlib.import_module(package)
  File "importlib\__init__.py", line 127, in import_module
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\export\models\__init__.py", line 1, in <module>
    from funasr.models.e2e_asr_paraformer import Paraformer, BiCifParaformer, ParaformerOnline
  File "N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\models\e2e_asr_paraformer.py", line 18, in <module>
    from funasr.models.ctc import CTC
ImportError: cannot import name 'CTC' from 'funasr.models.ctc' (N:\AI\GPT-SoVITS\runtime\lib\site-packages\funasr\models\ctc\__init__.py)

**Comment by hqqttjiang** [comment]
在runtime下尝试pip install -U rotary_embedding_torch 也无效  报错依旧

**Comment by LauraGPT** [comment]
What is your version of funasr
