### ISSUE TITLE
ValueError: Input cfg is not an OmegaConf config object (dict)

### ISSUE THREAD

**Issue by fengyunzaidushi** [RVC-Boss/GPT-SoVITS#604]
前面步骤都正常，点击开启离线批量ASR报错：

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/53250064/98e54d42-033f-4c86-ab8c-2bca0ffa7e4c)

`
Traceback (most recent call last):
  File "/mnt/sda/github/02yue/GPT-SoVITS/tools/asr/funasr_asr.py", line 17, in <module>
    model = AutoModel(
  File "/opt/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 92, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/opt/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 143, in build_model
    kwargs = download_model(**kwargs)
  File "/opt/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "/opt/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 53, in download_from_ms
    return OmegaConf.to_container(kwargs, resolve=True)
  File "/opt/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 569, in to_container
    raise ValueError(
ValueError: Input cfg is not an OmegaConf config object (dict)

`

命令行运行也是报错：
`
 python tools/asr/funasr_asr.py -i "/mnt/sda/github/02yue/GPT-SoVITS/output/denoise_opt" -o "output/asr_opt"

`

**Comment by fengyunzaidushi** [comment]
解决了。是因为下载 [Damo ASR Model](https://modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/files), [Damo VAD Model](https://modelscope.cn/models/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/files), and [Damo Punc Model](https://modelscope.cn/models/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/files) 模型的时候，下载了魔搭的版本，应该用 git clone 下载
