### ISSUE TITLE
ASR中调用faster whisper时，提示找不到cublas64_12.dll

### ISSUE THREAD

**Issue by sipeter** [RVC-Boss/GPT-SoVITS#607]
Traceback (most recent call last):
  File "D:\GSV\GPT-SoVITS\tools\asr\fasterwhisper_asr.py", line 74, in execute_asr
    for segment in segments:
  File "D:\DEV\anaconda3\envs\GPTSoVits\lib\site-packages\faster_whisper\transcribe.py", line 941, in restore_speech_timestamps
    for segment in segments:
  File "D:\DEV\anaconda3\envs\GPTSoVits\lib\site-packages\faster_whisper\transcribe.py", line 445, in generate_segments
    encoder_output = self.encode(segment)
  File "D:\DEV\anaconda3\envs\GPTSoVits\lib\site-packages\faster_whisper\transcribe.py", line 629, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded

在conda环境中，pytorch2.2.1+cu118，用funasr转写中文，训练，推理都没有问题，但调用faster whisper时，提示找不到cublas64_12.dll。把整合包中runtime拷贝到项目目录，运行则不会报错，尝试更换pytorch2.1.2+cu118，2.0.0+cu118都不能解决问题；同样是faster-whisper 0.10.0，整合包中的transcribe.py与我项目中的transcribe.py文件内容不一致，但即使将整合包中faster-whisper 0.10.0覆盖到项目中，故障现象依旧。是不是哪个依赖文件需要调用到cublas64_12.dll？

**Comment by DARK-STUDIOHK** [comment]
Try

pip install faster-whisper==0.10.1

**Comment by sipeter** [comment]
> Try
> 
> pip install faster-whisper==0.10.1 I have the same problem, but I solve it after doing this
Thanks for your reply, I'll try it

**Comment by sipeter** [comment]
> Try
> 
> pip install faster-whisper==0.10.1 I have the same problem, but I solve it after doing this

Thanks for your reply, I'll try it
