### ISSUE TITLE
Can we have a mps?

### ISSUE THREAD

**Issue by Lorre-Ramon** [RVC-Boss/GPT-SoVITS#61]
I currently ran into a bit of a problem that may have something to do with my CUDA. I'm a MacBook M1 user, so naturally, I don't have a GPU that fits CUDA. Normally I would expect setting CPU to the device as an alternative, which, for the record, I did see the codes, but it did not work smoothly on my device. Torch has launched mps for Apple Silicon users as an alternative to CUDA, I was wondering when the developer can update this.

The following is the Error I received when I was formatting the train set(1-训练集格式化工具). Maybe I got it all wrong why this error happen, please kindly help solve this.

```Python
"/Users/improvise/miniconda/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/Users/improvise/miniconda/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/Users/improvise/Desktop/GPT-SoVITS-main/GPT_SoVITS/prepare_datasets/1-get-text.py", line 53, in <module>
    bert_model = bert_model.half().to(device)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2460, in to
    return super().to(*args, **kwargs)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
Traceback (most recent call last):
  File "/Users/improvise/Desktop/GPT-SoVITS-main/GPT_SoVITS/prepare_datasets/1-get-text.py", line 53, in <module>
    bert_model = bert_model.half().to(device)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2460, in to
    return super().to(*args, **kwargs)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    return self._apply(convert)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    param_applied = fn(param)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/sit    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
e-packages/torch/nn/modules/module.py", line 1158, in convert
    module._apply(fn)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    param_applied = fn(param)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/improvise/miniconda/envs/GPTSoVits/lib/python3.9/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/improvise/Desktop/GPT-SoVITS-main/webui.py", line 529, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/test01/2-name2text-0.txt'
```
ps. The output in the folder `logs` is like this: `/Users/improvise/Desktop/GPT-SoVITS-main/logs/test01/3-bert`, the folder is empty.

**Comment by hydra-li** [comment]
M1pro too

**Comment by RoversX** [comment]
Have you guys tried CPU inference? I've currently tested So-vits-svc and bert-vits2 for CPU inference.

**Comment by RoversX** [comment]
> Have you guys tried CPU inference? I've currently tested So-vits-svc and bert-vits2 for CPU inference.

CPU inference Work! 

<img width="1352" alt="Screenshot 2024-01-18 at 2 09 15 PM" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/85817538/3f815414-298b-4e6b-8ac8-796bec78e4c2">

**Comment by RoversX** [comment]
> Have you guys tried CPU inference? I've currently tested So-vits-svc and bert-vits2 for CPU inference.

<img width="842" alt="Screenshot 2024-01-18 at 2 23 51 PM" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/85817538/1b2229f1-7a6e-4aac-985c-4a2814bccce6">

**Comment by Lorre-Ramon** [comment]
I try to manually adjust all `'cuda:0'` into `'cuda:0' if torch.cuda.is_available() else "cpu"`, and it worked.

**Comment by zhouhao27** [comment]
> > Have you guys tried CPU inference? I've currently tested So-vits-svc and bert-vits2 for CPU inference.
> 
> CPU inference Work!
> 
> <img alt="Screenshot 2024-01-18 at 2 09 15 PM" width="1352" src="https://private-user-images.githubusercontent.com/85817538/297881767-3f815414-298b-4e6b-8ac8-796bec78e4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjM2MDEsIm5iZiI6MTcwNjMyMzMwMSwicGF0aCI6Ii84NTgxNzUzOC8yOTc4ODE3NjctM2Y4MTU0MTQtMjk4Yi00ZTZiLThhYzgtNzk2YmVjNzhlNGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAyNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDY0MWRkMGQwNzNiNzdhMzY1NmM5NzU4NmFmZTFmMzU4ZGI3YTFjM2JjMzUzNTA2M2U3OThiZjZmNTI3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5BKklHZq2_bU8IEGD8mWNtOqp9YOW5rs1s34mpuoBY">

How? I can't start `webui.py` at all.

**Comment by RoversX** [comment]
> > > Have you guys tried CPU inference? I've currently tested So-vits-svc and bert-vits2 for CPU inference.
> > 
> > 
> > CPU inference Work!
> > <img alt="Screenshot 2024-01-18 at 2 09 15 PM" width="1352" src="https://private-user-images.githubusercontent.com/85817538/297881767-3f815414-298b-4e6b-8ac8-796bec78e4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjM2MDEsIm5iZiI6MTcwNjMyMzMwMSwicGF0aCI6Ii84NTgxNzUzOC8yOTc4ODE3NjctM2Y4MTU0MTQtMjk4Yi00ZTZiLThhYzgtNzk2YmVjNzhlNGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAyNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDY0MWRkMGQwNzNiNzdhMzY1NmM5NzU4NmFmZTFmMzU4ZGI3YTFjM2JjMzUzNTA2M2U3OThiZjZmNTI3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5BKklHZq2_bU8IEGD8mWNtOqp9YOW5rs1s34mpuoBY">
> 
> How? I can't start `webui.py` at all.

u use ```python web.py``` to start webui
