### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by fengyunzaidushi** [RVC-Boss/GPT-SoVITS#617]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/53250064/87e50b4f-fbd7-482d-840f-f801c0d6a1e6)

下次启动，直接进行推理，为什么会报错：
`(GPTSoVits2) ubuntu@ubuntu:/mnt/sda/github/02yue/GPT-SoVITS2$ python webui.py 
Running on local URL:  http://0.0.0.0:9874
"/opt/miniconda3/envs/GPTSoVits2/bin/python" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "/mnt/sda/github/02yue/GPT-SoVITS2/GPT_SoVITS/inference_webui.py", line 55, in <module>
    import librosa, torch
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
"/opt/miniconda3/envs/GPTSoVits2/bin/python" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "/mnt/sda/github/02yue/GPT-SoVITS2/GPT_SoVITS/inference_webui.py", line 55, in <module>
    import librosa, torch
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
"/opt/miniconda3/envs/GPTSoVits2/bin/python" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "/mnt/sda/github/02yue/GPT-SoVITS2/GPT_SoVITS/inference_webui.py", line 55, in <module>
    import librosa, torch
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
"/opt/miniconda3/envs/GPTSoVits2/bin/python" GPT_SoVITS/inference_webui.py
Traceback (most recent call last):
  File "/mnt/sda/github/02yue/GPT-SoVITS2/GPT_SoVITS/inference_webui.py", line 55, in <module>
    import librosa, torch
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/miniconda3/envs/GPTSoVits2/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
`

**Comment by fengyunzaidushi** [comment]
解决了 ，卸载numpy并重新安装numpy1.23.5
`
pip uninstall numpy
pip install numpy==1.23.5
`
