### ISSUE TITLE
开启一键三连报错，找不到文件，

### ISSUE THREAD

**Issue by laobiao139** [RVC-Boss/GPT-SoVITS#656]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/45176234/e049ca8e-e7bd-4492-9f98-84f77364067b)
`"E:\Anaconda3-5.3.1\envs\sovits\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\Anaconda3-5.3.1\envs\sovits\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\python\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
Traceback (most recent call last):
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "D:\python\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
  File "E:\Anaconda3-5.3.1\envs\sovits\lib\os.py", line 685, in __setitem__
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "E:\Anaconda3-5.3.1\envs\sovits\lib\os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "E:\Anaconda3-5.3.1\envs\sovits\lib\os.py", line 743, in check_str
    value = self.encodevalue(value)
  File "E:\Anaconda3-5.3.1\envs\sovits\lib\os.py", line 743, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "D:\python\GPT-SoVITS-beta0217\webui.py", line 556, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/zhuboD/2-name2text-0.txt'
错误: 没有找到进程 "2516"。
错误: 没有找到进程 "27140"。`

我自己建了一个logs/zhuboD/2-name2text-0.txt文件也不行

**Comment by KamioRinn** [comment]
跟找不到文件没关系，环境问题。

**Comment by coranholmes** [comment]
> 跟找不到文件没关系，环境问题。

我也遇到了这个问题，在MAC环境下的，请问该如何解决呢？

**Comment by laobiao139** [comment]
> 跟找不到文件没关系，环境问题。

谢谢，已经解决，把下载touch gpu版本就行了

**Comment by AShanWang** [comment]
> > 跟找不到文件没关系，环境问题。
> 
> 谢谢，已经解决，把下载touch gpu版本就行了

你好
我遇到和你相同点的错误，我的是英特尔集显；
具体怎么操作啊！
在哪儿下？
请赐教
