### ISSUE TITLE
我在训练时遇到一个奇怪的错误

### ISSUE THREAD

**Issue by KakaoXI** [RVC-Boss/GPT-SoVITS#659]
This is the code error:
Traceback (most recent call last):
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 85, in run
    train_dataset = TextAudioSpeakerLoader(hps.data)  ########
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\module\data_utils.py", line 103, in __init__
    assert len(audiopaths_sid_text_new) > 1  # 至少能凑够batch size，这里todo
AssertionError

"C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "C:\Users\Kakao\Downloads\GPT-SoVITS\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

semantic_data_len: 1
phoneme_data_len: 1
    item_name                                     semantic_audio
0  hitomi.wav  550 849 84 867 512 512 512 655 862 0 915 923 4...
Traceback (most recent call last):
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 180, in <module>
    main(args)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\s1_train.py", line 156, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\runtime\lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\AR\data\data_module.py", line 29, in setup
    self._train_dataset = Text2SemanticDataset(
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 107, in __init__
    self.init_batch()
  File "C:\Users\Kakao\Downloads\GPT-SoVITS\GPT_SoVITS\AR\data\dataset.py", line 187, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by KC888-cpu** [comment]
请问有解决么，我也碰到了
