### ISSUE TITLE
mac电脑报错

### ISSUE THREAD

**Issue by chengreg** [RVC-Boss/GPT-SoVITS#682]
Traceback (most recent call last):
  File "/Users/chengq/Documents/ai/GPT-SoVITS/tools/slice_audio.py", line 31, in slice
    audio = load_audio(inp_path, 32000)
  File "/Users/chengq/Documents/ai/GPT-SoVITS/tools/my_utils.py", line 23, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

https://i0.hdslb.com/bfs/new_dyn/fb4b64665b9f1556fa5f340e6631dc88429555528.jpg@!web-comment-note.avif

**Comment by SapphireLab** [comment]
大概是没装 ffmpeg 吧, 可以先看看[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/znoph9dtetg437xb).

**Comment by XXXXRT666** [comment]
是否安装ffmpeg？是否在终端能直接调用ffmpeg？若皆可以，可以尝试![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/157766680/016b542b-a6d2-432b-acb1-4cb84f5e1407)

**Comment by RVC-Boss** [comment]
楼上正解，装下ffmpeg-python库

**Comment by 1peng** [comment]
mac电脑下边有个.DS_Store隐藏文件删掉，或改源码过滤掉

**Comment by XXXXRT666** [comment]
跟DS_Store无关
