### ISSUE TITLE
TypeError: Invalid file (44100, array([-1,  0,  0, ...,  0,  0,  0], dtype=int16))

### ISSUE THREAD

**Issue by lonngxiang** [RVC-Boss/GPT-SoVITS#698]
TypeError: Invalid file: (44100, array([-1,  0,  0, ...,  0,  0,  0], dtype=int16))

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/40717349/662f8465-6908-46ca-a6ca-66f6db4e12c7)

**Comment by lonngxiang** [comment]
Traceback (most recent call last):
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/utils.py", line 521, in async_iteration
    return await iterator.__anext__()
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/utils.py", line 514, in __anext__
    return await anyio.to_thread.run_sync(
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/utils.py", line 497, in run_sync_iterator_async
    return next(iterator)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/gradio/utils.py", line 678, in gen_wrapper
    response = next(iterator)
  File "/mnt/data/loong/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 329, in get_tts_wav
    wav16k, sr = librosa.load(ref_wav_path, sr=16000)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/librosa/core/audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/mnt/data/anaconda3/envs/chatchat/lib/python3.10/site-packages/soundfile.py", line 1212, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: (44100, array([-1,  0,  0, ...,  0,  0,  0], dtype=int16))

**Comment by lonngxiang** [comment]
找到问题了，gr.Audio()内必须要传入type="filepath";不然后续librosa读取不了路径
