### ISSUE TITLE
降噪不能用，请各位大佬帮帮忙

### ISSUE THREAD

**Issue by feiskygod** [RVC-Boss/GPT-SoVITS#699]
2024-03-07 15:36:16,835 - modelscope - WARNING - No preprocessor field found in cfg.
2024-03-07 15:36:16,835 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-03-07 15:36:16,835 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/Users/fed/.cache/modelscope/hub/damo/speech_frcrn_ans_cirm_16k'}. trying to build by task and model information.
2024-03-07 15:36:16,835 - modelscope - WARNING - No preprocessor key ('speech_frcrn_ans_cirm_16k', 'acoustic-noise-suppression') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-03-07 15:36:16,836 - modelscope - INFO - cuda is not available, using cpu instead.
Traceback (most recent call last):
  File "/Users/fed/Downloads/GPT-SoVITS-main/GPT-SoVITS/tools/cmd-denoise.py", line 26, in <module>
    execute_denoise(
  File "/Users/fed/Downloads/GPT-SoVITS-main/GPT-SoVITS/tools/cmd-denoise.py", line 14, in execute_denoise
    for name in tqdm(os.listdir(input_folder)):

**Comment by RVC-Boss** [comment]
没贴全，看不出来

**Comment by feiskygod** [comment]
"/Users/fed/opt/anaconda3/envs/GPTSoVits/bin/python" tools/cmd-denoise.py -i "/Users/feiskygod/Downloads/测试 001.mp3" -o "output/denoise_opt" -p float32
2024-03-07 19:28:54,819 - modelscope - INFO - PyTorch version 2.3.0.dev20240306 Found.
2024-03-07 19:28:54,820 - modelscope - INFO - Loading ast index from /Users/fed/.cache/modelscope/ast_indexer
2024-03-07 19:28:54,853 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 d410ad02d07cc90be508b2eb9d71b28c and a total number of 946 components indexed
2024-03-07 19:28:58,408 - modelscope - WARNING - Model revision not specified, use revision: v1.0.2
2024-03-07 19:29:00,078 - modelscope - INFO - initiate model from /Users/feiskygod/.cache/modelscope/hub/damo/speech_frcrn_ans_cirm_16k
2024-03-07 19:29:00,078 - modelscope - INFO - initiate model from location /Users/fed/.cache/modelscope/hub/damo/speech_frcrn_ans_cirm_16k.
2024-03-07 19:29:00,079 - modelscope - INFO - initialize model from /Users/feiskygod/.cache/modelscope/hub/damo/speech_frcrn_ans_cirm_16k
2024-03-07 19:29:00,567 - modelscope - WARNING - No preprocessor field found in cfg.
2024-03-07 19:29:00,567 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-03-07 19:29:00,567 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/Users/fed/.cache/modelscope/hub/damo/speech_frcrn_ans_cirm_16k'}. trying to build by task and model information.
2024-03-07 19:29:00,567 - modelscope - WARNING - No preprocessor key ('speech_frcrn_ans_cirm_16k', 'acoustic-noise-suppression') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-03-07 19:29:00,568 - modelscope - INFO - cuda is not available, using cpu instead.
Traceback (most recent call last):
  File "/Users/fed/Downloads/GPT-SoVITS-main/GPT-SoVITS/tools/cmd-denoise.py", line 26, in <module>
    execute_denoise(
  File "/Users/fed/Downloads/GPT-SoVITS-main/GPT-SoVITS/tools/cmd-denoise.py", line 14, in execute_denoise
    for name in tqdm(os.listdir(input_folder)):
NotADirectoryError: [Errno 20] Not a directory: '/Users/fed/Downloads/测试 001.mp3'

大佬帮忙看下

**Comment by SapphireLab** [comment]
降噪的输入路径仅支持文件夹.

**Comment by RVC-Boss** [comment]
第一面的功能除了打标外都是写文件夹路径批量处理的
