### ISSUE TITLE
批量ASR 突然报错了，请帮忙看看～！

### ISSUE THREAD

**Issue by feiskygod** [RVC-Boss/GPT-SoVITS#704]
Traceback (most recent call last):
  File "/Users/fed/Downloads/GPT-SoVITS-main/GPT-SoVITS/tools/asr/funasr_asr.py", line 17, in <module>
    model = AutoModel(
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 92, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 143, in build_model
    kwargs = download_model(**kwargs)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 32, in download_from_ms
    kwargs["tokenizer_conf"]["token_list"] = os.path.join(model_or_path, "tokens.txt")
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/Users/fed/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key tokenizer_conf
    full_key: tokenizer_conf
    object_type=dict

**Comment by feiskygod** [comment]
删除 asr 目录的 model 后就好了

**Comment by c4fun** [comment]
应该是模型更新了。原来的模型不适用了。
我也是碰到了类似的错误，删掉原来的models文件之后，重新下载就好了。

**Comment by Song367** [comment]
我删除了，还是这样

**Comment by XXXXRT666** [comment]
> 我删除了，还是这样
> 
> 

M系列Mac去用中文教程里Mac教程的一键包试试，别的用教程里的Damo ASR Model压缩包看看
