### ISSUE TITLE
训练报错，大神帮忙

### ISSUE THREAD

**Issue by feiskygod** [RVC-Boss/GPT-SoVITS#705]
"/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/s1_train.py --config_file "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/TEMP/tmp_s1.yaml" 
Seed set to 1234
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
semantic_data_len: 0
phoneme_data_len: 0
Empty DataFrame
Columns: [item_name, semantic_audio]
Index: []
Traceback (most recent call last):
  File "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 180, in <module>
    main(args)
  File "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/GPT_SoVITS/s1_train.py", line 156, in main
    trainer.fit(model, data_module, ckpt_path=ckpt_path)
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/Users/feiskygod/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/GPT_SoVITS/AR/data/data_module.py", line 30, in setup
    self._train_dataset = Text2SemanticDataset(
  File "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/GPT_SoVITS/AR/data/dataset.py", line 108, in __init__
    self.init_batch()
  File "/Users/feiskygod/Downloads/GPT-SoVITS-main/GPT-SoVITS/GPT_SoVITS/AR/data/dataset.py", line 188, in init_batch
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by SapphireLab** [comment]
先看看[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt) 是否能解决你的问题

**Comment by Lion-Wu** [comment]
也有可能是数据集的问题，用切分工具切分一下后再尝试

**Comment by XXXXRT666** [comment]
检查一件三连
