### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by wrl1224** [RVC-Boss/GPT-SoVITS#720]
Traceback (most recent call last):
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS/tools/asr/funasr_asr.py", line 8, in <module>
    from funasr import AutoModel
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/funasr/__init__.py", line 33, in <module>
    from funasr.auto.auto_model import AutoModel
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 13, in <module>
    from funasr.utils.load_utils import load_bytes
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/funasr/utils/load_utils.py", line 7, in <module>
    import librosa
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/heike/anaconda3/envs/GPT-SoVITS/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

在执行中文批量离线ASR工具的环节遇到了以上报错，希望告知原因

**Comment by SapphireLab** [comment]
通常是因为 numpy 和 numba 的版本不适配, 可以尝试更换一下 numba 版本或 numpy 版本.

**Comment by wrl1224** [comment]
谢谢!问题解决了,我这边尝试安装了最新版的numba 和numpy ,报错解决了
