### ISSUE TITLE
在进行一键三连的时候报错

### ISSUE THREAD

**Issue by GrootLiu** [RVC-Boss/GPT-SoVITS#725]
  ~/liuao/GPT-SoVITS   main ?1 ❯ python webui.py --listen                                                                                                             7s  GPTSoVits jss41@node41  08:24:14
Running on local URL:  http://0.0.0.0:9874
"/home/jss41/miniconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/home/jss41/miniconda3/envs/GPTSoVits/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jss41/liuao/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 767, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 600, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Traceback (most recent call last):
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jss41/liuao/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 56, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_pretrained_dir)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 767, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 600, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/jss41/miniconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Traceback (most recent call last):
  File "/home/jss41/liuao/GPT-SoVITS/webui.py", line 580, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/liuao/2-name2text-0.txt'

**Comment by GrootLiu** [comment]
使用 Linux 运行该开源程序时报错，系统设置如下：
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by GrootLiu** [comment]
.-/+oossssoo+/-.               jss41@node41
        `:+ssssssssssssssssss+:`           ------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: ThinkServer SR668 V2 V2
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-91-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 46 days, 16 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1146 (dpkg), 4 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Gold 6338N (128) @ 3.500GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: NVIDIA 31:00.0 NVIDIA Corporation Device 2684
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 4573MiB / 1031633MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

**Comment by GrootLiu** [comment]
conda 4.8.3

**Comment by GrootLiu** [comment]
Sat Mar  9 08:29:19 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:31:00.0 Off |                  Off |
| 34%   32C    P8              12W / 450W |      6MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by GrootLiu** [comment]
![Uploading Snipaste_2024-03-09_16-30-10.png…]()

**Comment by SapphireLab** [comment]
关键句子: `OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'.`
请检查该目录下是否有相应的预训练模型.

**Comment by arctan90** [comment]
See this [suggestion](https://github.com/RVC-Boss/GPT-SoVITS/issues/480#issuecomment-1977917939)
Try your lucky.

**Comment by GrootLiu** [comment]
> 关键句子: `OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'.` 请检查该目录下是否有相应的预训练模型.

多谢您的回答~

**Comment by zhangyue2709** [comment]
我也遇到了相同的问题，请问你怎么解决的呢

**Comment by kulame** [comment]
同样的问题。
```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.
```
