### ISSUE TITLE
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded

### ISSUE THREAD

**Issue by wrl1224** [RVC-Boss/GPT-SoVITS#727]
loading faster whisper model: large large
  0%|                                                                                                                                         | 0/349 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-beta0306/tools/asr/fasterwhisper_asr.py", line 61, in execute_asr
    segments, info = model.transcribe(
  File "/home/heike/anaconda3/envs/GPT-SoVITS-beta0306/lib/python3.9/site-packages/faster_whisper/transcribe.py", line 344, in transcribe
    encoder_output = self.encode(segment)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-beta0306/lib/python3.9/site-packages/faster_whisper/transcribe.py", line 762, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded

  0%|                                                                                                                                         | 0/349 [00:00<?, ?it/s]
ASR报错不知道怎么解决

**Comment by lin-xiaosheng** [comment]
我用用pip freeze > ./requirements.txt导出了全部依赖。之后在另外一台机器上copy了整个项目文件，并pip install了导出的requirements.txt文件。目前在离线转写的时候也报了以上错误

**Comment by RVC-Boss** [comment]
可以回滚下上个版本，0306升级了pytorch版本，现在看来有问题，看看0217版本的整合包，也会有这个问题吗？@wrl1224 @lin-xiaosheng
