### ISSUE TITLE
RuntimeError: The size of tensor a (350) must match the size of tensor b (524) at non-singleton dimension 2

### ISSUE THREAD

**Issue by SRbone** [RVC-Boss/GPT-SoVITS#744]
```
Traceback (most recent call last):
  File "./s2_train.py", line 600, in <module>
    main()
  File "./s2_train.py", line 56, in main
    mp.spawn(
  File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 202, in start_processes
    while not context.join():
  File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 74, in _wrap
    fn(i, *args)
  File "D:\GPT_SoVITS\s2_train.py", line 268, in run
    train_and_evaluate(
  File "D:\GPT_SoVITS\s2_train.py", line 385, in train_and_evaluate
    loss_kl = kl_loss(z_p, logs_q, m_p, logs_p, z_mask) * hps.train.c_kl
  File "D:\GPT_SoVITS\module\losses.py", line 57, in kl_loss
    kl = logs_p - logs_q - 0.5
RuntimeError: The size of tensor a (350) must match the size of tensor b (524) at non-singleton dimension 2
```

**Comment by nickshui** [comment]
> 开启SoVITS训练时报错：
> 
> ```
> D:\python\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
> Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
>   return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
> D:\python\lib\site-packages\torch\functional.py:650: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\EmptyTensor.cpp:32.)
>   return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
> 0it [00:07, ?it/s]
> 0it [00:07, ?it/s]
> 
> Traceback (most recent call last):
>   File "./s2_train.py", line 600, in <module>
>     main()
>   File "./s2_train.py", line 56, in main
>     mp.spawn(
>   File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 246, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
>   File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 202, in start_processes
>     while not context.join():
>   File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 163, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 1 terminated with the following error:
> Traceback (most recent call last):
>   File "D:\python\lib\site-packages\torch\multiprocessing\spawn.py", line 74, in _wrap
>     fn(i, *args)
>   File "D:\GPT_SoVITS\s2_train.py", line 268, in run
>     train_and_evaluate(
>   File "D:\GPT_SoVITS\s2_train.py", line 385, in train_and_evaluate
>     loss_kl = kl_loss(z_p, logs_q, m_p, logs_p, z_mask) * hps.train.c_kl
>   File "D:\GPT_SoVITS\module\losses.py", line 57, in kl_loss
>     kl = logs_p - logs_q - 0.5
> RuntimeError: The size of tensor a (350) must match the size of tensor b (524) at non-singleton dimension 2
> ```


我也在摸索，下午出现类似的错误：RuntimeError: The size of tensor a (869) must match the size of tensor b (512) at non-singleton dimension 1

可能问题是你切割的音频时长太长，你的显存不够处理了。我的显存是6G，基本超过17秒的音频都出错
解决方法是，将threshold的值调小一点，会让分割的音频比较短，后者你手动调整，使得音频时长不要超过20秒。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/43905968/f4e5dd3d-644d-426d-ab75-eabdbbc7638a)

**Comment by EmbraceDaytime** [comment]
return _VF.  stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT doesn't support signals of half type with compute capability less than SM_53, but the device containing input half tensor only has SM_50

这个怎么解决？

**Comment by KexingWestRoad** [comment]
开启SoVITS时没报错，开启GPT训练时报错
RuntimeError: The size of tensor a (1025) must match the size of tensor b (120) at non-singleton dim

**Comment by Hjlvx** [comment]
> 开启SoVITS时没报错，开启GPT训练时报错 RuntimeError: The size of tensor a (1025) must match the size of tensor b (120) at non-singleton dim 这个也是音频太长导致吗？我的音频是40s，mac book pro 16G内存

我和你一样的问题，请问你解决了吗?我的语音时长全都是2-5秒的，显存8G，sovits正常，但是一开始训练gpt就报错

**Comment by SRbone** [comment]
好久之前的问题了，有两点需要注意：1.整理音频数据，较长的音频数据需要较大显存。2. txt文件中的文字不要有生僻字或者生僻符号。

**Comment by AnInsomniacy** [comment]
> 开启SoVITS时没报错，开启GPT训练时报错 RuntimeError: The size of tensor a (1025) must match the size of tensor b (120) at non-singleton dim 这个也是音频太长导致吗？我的音频是40s，mac book pro 16G内存

我也和你一样，m1pro一训练gpt就报你上面的错误，47秒的素材，分割后每个最长7秒
