### ISSUE TITLE
求助, OSError: [WinError 1314] 用戶端沒有這項特殊權限。

### ISSUE THREAD

**Issue by firzen348** [RVC-Boss/GPT-SoVITS#745]
ARS过程中出现的错误,不知道怎么解决,我选的是Faster Whisper, large和ja
以下是错误时的代码

model.bin: 100%|██████████████████████████████████████████████████████████████████| 3.09G/3.09G [04:37<00:00, 11.1MB/s]
Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\asr\fasterwhisper_asr.py", line 49, in execute_asr
    model = WhisperModel(model_path, device="cuda", compute_type=precision)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\faster_whisper\transcribe.py", line 124, in __init__
    model_path = download_model(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\faster_whisper\utils.py", line 100, in download_model
    return huggingface_hub.snapshot_download(repo_id, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\tqdm\contrib\concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\tqdm\contrib\concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\tqdm\std.py", line 1183, in __iter__
    for obj in iterable:
  File "concurrent\futures\_base.py", line 609, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\file_download.py", line 1469, in hf_hub_download
    _create_symlink(blob_path, pointer_path, new_blob=True)
  File "E:\GPT-SoVITS-beta\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\lib\site-packages\huggingface_hub\file_download.py", line 916, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)
OSError: [WinError 1314] 用戶端沒有這項特殊權限。: '..\\..\\blobs\\931c77a740890c46365c7ae0c9d350ba3cca908f' -> 'C:\\Users\\wongl\\.cache\\huggingface\\hub\\models--Systran--faster-whisper-large-v3\\snapshots\\edaa852ec7e145841d8ffdb056a99866b5f0a478\\preprocessor_config.json'

**Comment by SapphireLab** [comment]
没有权限的话可以考虑管理员模式运行, 如果你会的话.jpg.

或者可以考虑以下方式:
你的默认缓存目录是 `C:/Users/wongl/.cache/huggingface/hub/models--Systran--faster-whisper-large-v3` 并且 `model.bin` 已经下好了, 可以**移动**该文件夹到项目的 `tools/asr/models/` 下并且**重命名**为 `faster-whisper-large-v3`.
然后[手动下载](https://hf-mirror.com/Systran/faster-whisper-large-v3/tree/main) 其他文件补充完整.

重启 webui 后顺利识别的话在 Faster Whisper 模型下拉选单中会显示 `large-v3-local`, 选择即可.
