### ISSUE TITLE
一键三连执行到2-get-hubert-wav32k.py出现MemoryError

### ISSUE THREAD

**Issue by bigmarten** [RVC-Boss/GPT-SoVITS#751]
可用内存还有20G，如何解决？
"/home/saizong/.conda/envs/GPT-SoVITS/bin/python" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"/home/saizong/.conda/envs/GPT-SoVITS/bin/python" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
Traceback (most recent call last):
  File "/home/saizong/GPT-SoVITS-0302/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py", line 10, in <module>
    from feature_extractor import cnhubert
  File "/home/saizong/GPT-SoVITS-0302/GPT_SoVITS/feature_extractor/__init__.py", line 1, in <module>
    from . import cnhubert, whisper_enc
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
MemoryError
Traceback (most recent call last):
  File "/home/saizong/GPT-SoVITS-0302/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py", line 10, in <module>
    from feature_extractor import cnhubert
  File "/home/saizong/GPT-SoVITS-0302/GPT_SoVITS/feature_extractor/__init__.py", line 1, in <module>
    from . import cnhubert, whisper_enc
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
MemoryError

**Comment by RVC-Boss** [comment]
内存不足？电脑多少G内存？以及前端是开了2个进程吗？（0-0那个字符串）

**Comment by bigmarten** [comment]
两份钟的音频，如果用30s音频够了吗？&nbsp;


J.bigmarten
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月13日(星期三) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RVC-Boss/GPT-SoVITS] 一键三连执行到2-get-hubert-wav32k.py出现MemoryError (Issue #751)





 
以及有没有超长音频
