### ISSUE TITLE
同步了新版本后在一键三连的第三步时报这个错

### ISSUE THREAD

**Issue by liangtongt** [RVC-Boss/GPT-SoVITS#759]
"/home/ltt/anaconda3/envs/gpt-sovits/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"/home/ltt/anaconda3/envs/gpt-sovits/bin/python" GPT_SoVITS/prepare_datasets/3-get-semantic.py
/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/ltt/zhibo/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 48, in <module>
    vq_model = SynthesizerTrn(
  File "/home/ltt/zhibo/GPT-SoVITS/GPT_SoVITS/module/models.py", line 896, in __init__
    self.quentizer.eval()
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SynthesizerTrn' object has no attribute 'quentizer'
Traceback (most recent call last):
  File "/home/ltt/zhibo/GPT-SoVITS/GPT_SoVITS/prepare_datasets/3-get-semantic.py", line 48, in <module>
    vq_model = SynthesizerTrn(
  File "/home/ltt/zhibo/GPT-SoVITS/GPT_SoVITS/module/models.py", line 896, in __init__
    self.quentizer.eval()
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SynthesizerTrn' object has no attribute 'quentizer'
Traceback (most recent call last):
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/ltt/anaconda3/envs/gpt-sovits/lib/python3.9/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/ltt/zhibo/GPT-SoVITS/webui.py", line 519, in open1c
    with open(semantic_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/molly2/6-name2semantic-0.tsv'

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/module/models.py#L896
找到这个文件，将self.quentizer.eval()改为self.quantizer.eval()

**Comment by RVC-Boss** [comment]
> https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/module/models.py#L896 找到这个文件，将self.quentizer.eval()改为self.quantizer.eval()

fixed.
