### ISSUE TITLE
一键三连第二部报错

### ISSUE THREAD

**Issue by liuchunyu524** [RVC-Boss/GPT-SoVITS#766]
/data2/parkliu/GPT-SoVITS/data/slicer/aud.wav_0003795200_0003985280.wav|slicer|ZH|完善个人所得税制度。也可以说，随着个税制度变得更科学、更合理。 Traceback (most recent call last):
  File "/data2/parkliu/GPT-SoVITS/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py", line 109, in <module>
    name2go(wav_name,wav_path)
  File "/data2/parkliu/GPT-SoVITS/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py", line 83, in name2go
    ssl=model.model(tensor_wav16.unsqueeze(0))["last_hidden_state"].transpose(1,2).cpu()#torch.Size([1, 768, 215])
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 1081, in forward
    extract_features = self.feature_extractor(input_values)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 354, in forward
    hidden_states = conv_layer(hidden_states)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 256, in forward
    hidden_states = self.conv(hidden_states)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data2/parkliu/GPT-SoVITS/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by SapphireLab** [comment]
自己配置模型的话应该需要装 cuDNN了(或者是兼容性出错。
