### ISSUE TITLE
开启TTS推理WebUI时，控制台报错

### ISSUE THREAD

**Issue by qinzhijun** [RVC-Boss/GPT-SoVITS#798]
![~((61ETO2})P`HK 3}M0$YO](https://github.com/RVC-Boss/GPT-SoVITS/assets/1711794/8b3d76e9-5960-4970-a955-f6bbdf02ec12)

![JUA`_U3E4O HTFKXZ)_5C2F](https://github.com/RVC-Boss/GPT-SoVITS/assets/1711794/e11a42aa-110b-4c37-800f-efa601a50a26)

![Uploading 222.png…]()

如图，勾选“是否开启TTS推理WebUI”时，控制台报错，缺少的py文件看上去都在，操作系统win10，从123pan.com上下载的整合包“GPT-SoVITS-beta0306fix2.7z”，具体的报错日志如下：

J:\GPT-SoVITS>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"J:\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/inference_webui.py
J:\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
J:\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'J:\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg5
DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'J:\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg4
DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'J:\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "J:\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
J:\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Some weights of the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base were not used when initializing HubertModel: ['encoder.pos_conv_embed.conv.weight_g', 'encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of HubertModel were not initialized from the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
J:\GPT-SoVITS\runtime\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
<All keys matched successfully>
Number of parameter: 77.49M
DEBUG:root:Using proactor: IocpProactor
DEBUG:root:Using proactor: IocpProactor
Running on local URL:  http://0.0.0.0:9872

**Comment by geekh-33** [comment]
+1,我也是提示缺了个 module，但我看了下这个 module 是楼主自己定义的
ModuleNotFoundError: No module named 'text'
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/43328870/3f73ac23-82e4-40ca-9e1d-31e4909556f8)

**Comment by supertaog** [comment]
屏幕截图 2024-04-18 131947报错位置已经给出了，在 utils.py 文件的这里，ffmpeg的几个版本都在这个画横杠的键中，报错找不到ffmpeg，原因只有没有ffmpeg和路径不对。找到ffmpeg存放目录。image这样将地址添加到环境变量中

**Comment by supertaog** [comment]
> <img alt="屏幕截图 2024-04-18 131947" width="432" src="https://private-user-images.githubusercontent.com/162496386/323475592-55ddb681-9e17-48c2-971e-15370045889a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzQxMzEsIm5iZiI6MTcxMzg3MzgzMSwicGF0aCI6Ii8xNjI0OTYzODYvMzIzNDc1NTkyLTU1ZGRiNjgxLTllMTctNDhjMi05NzFlLTE1MzcwMDQ1ODg5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMjAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2MDZjODA4N2ExNmNjZWI1MmU3YmExYjg2MDVhN2E3NGY0NmQ2M2VkMTAyN2ZlNTcyN2IwMDhhOWQ4YjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NBTG5bMDkxaW__rMFNuj3-4qhCqHeVxZnyKgd5NMUzg">报错位置已经给出了，在 utils.py 文件的这里，ffmpeg的几个版本都在这个画横杠的键中，报错找不到ffmpeg，原因只有没有ffmpeg和路径不对。找到ffmpeg存放目录。<img alt="image" width="410" src="https://private-user-images.githubusercontent.com/162496386/323476767-b25d1755-7cb5-47b9-8ab4-3f8d46b3a51b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzQxMzEsIm5iZiI6MTcxMzg3MzgzMSwicGF0aCI6Ii8xNjI0OTYzODYvMzIzNDc2NzY3LWIyNWQxNzU1LTdjYjUtNDdiOS04YWI0LTNmOGQ0NmIzYTUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMjAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ3ZTZjZDBiYjRjNzVkZWM5YmFjYWIxMjQyYjZjMWNkZWMxZDVkYjczYjg4ZjM4MTNhZmZiYTVhZGQ1NjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vjoz4wxJqgqyjvOOBTBafgx9BS95Jy1b9NPNxYfeC8A">这样将地址添加到环境变量中

**Comment by Ancolie18** [comment]
您好，同样的ffmpeg错误，按照下面的路径加了环境变量但还是报错。按照请问您解决了吗？

> > <img alt="屏幕截图 2024-04-18 131947" width="432" src="https://private-user-images.githubusercontent.com/162496386/323475592-55ddb681-9e17-48c2-971e-15370045889a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzQxMzEsIm5iZiI6MTcxMzg3MzgzMSwicGF0aCI6Ii8xNjI0OTYzODYvMzIzNDc1NTkyLTU1ZGRiNjgxLTllMTctNDhjMi05NzFlLTE1MzcwMDQ1ODg5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMjAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2MDZjODA4N2ExNmNjZWI1MmU3YmExYjg2MDVhN2E3NGY0NmQ2M2VkMTAyN2ZlNTcyN2IwMDhhOWQ4YjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NBTG5bMDkxaW__rMFNuj3-4qhCqHeVxZnyKgd5NMUzg">报错位置已经给出了，在 utils.py 文件的这里，ffmpeg的几个版本都在这个画横杠的键中，报错找不到ffmpeg，原因只有没有ffmpeg和路径不对。找到ffmpeg存放目录。<img alt="image" width="410" src="https://private-user-images.githubusercontent.com/162496386/323476767-b25d1755-7cb5-47b9-8ab4-3f8d46b3a51b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzQxMzEsIm5iZiI6MTcxMzg3MzgzMSwicGF0aCI6Ii8xNjI0OTYzODYvMzIzNDc2NzY3LWIyNWQxNzU1LTdjYjUtNDdiOS04YWI0LTNmOGQ0NmIzYTUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMjAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ3ZTZjZDBiYjRjNzVkZWM5YmFjYWIxMjQyYjZjMWNkZWMxZDVkYjczYjg4ZjM4MTNhZmZiYTVhZGQ1NjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vjoz4wxJqgqyjvOOBTBafgx9BS95Jy1b9NPNxYfeC8A">这样将地址添加到环境变量中

**Comment by supertaog** [comment]
> 您好，同样的ffmpeg错误，按照下面的路径加了环境变量但还是报错。按照请问您解决了吗？
> 这得看看报错内容。
