### ISSUE TITLE
ModuleNotFoundError: No module named 'text'

### ISSUE THREAD

**Issue by geekh-33** [RVC-Boss/GPT-SoVITS#819]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/43328870/6aa7e74a-c89f-46e8-beda-481eed8baf80)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/43328870/0e962354-73e7-425a-a76f-c01a8e0912cb)

### 代码版本： 
整合包 GPT-SoVITS-beta0306fix2

### 问题：
运行到 **一键三连** 时报错，控制台输出：
"D:\ProgramWork\miniconda3\envs\traiceVoicePy39V2\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\ProgramWork\miniconda3\envs\traiceVoicePy39V2\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\code\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
  File "D:\code\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
    from text.cleaner import clean_text
ModuleNotFoundError: No module named 'text'
ModuleNotFoundError: No module named 'text'
Traceback (most recent call last):
  File "d:\code\GPT-SoVITS-beta0306fix2\webui.py", line 580, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/BaiZhanTang/2-name2text-0.txt'
错误: 没有找到进程 "12160"。
错误: 没有找到进程 "11156"。

望大佬们能解惑下，谢谢

**Comment by XXXXRT666** [comment]
用整合包自带python，双击bat运行

**Comment by XXXXRT666** [comment]
你也可以重装环境之后再试试看本地环境启动
