### ISSUE TITLE
我如果输入了 请读出来abcdefg 就会出错

### ISSUE THREAD

**Issue by 7yilink** [RVC-Boss/GPT-SoVITS#845]
结果如下：注，使用的中英文混和

前端处理后的文本(每句): ['请读出来abcdefg。 ']
ERROR:tts_backend:Exception on /tts [POST]
Traceback (most recent call last):
  File "D:\face\GPT-SoVITS-Inference\runtime\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\face\GPT-SoVITS-Inference\runtime\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\face\GPT-SoVITS-Inference\runtime\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\face\GPT-SoVITS-Inference\runtime\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\face\GPT-SoVITS-Inference\Inference\src\tts_backend.py", line 97, in tts
    sampling_rate, audio_data = next(gen)
  File "D:\face\GPT-SoVITS-Inference\GPT_SoVITS\TTS_infer_pack\TTS.py", line 579, in run
    pred_semantic_list, idx_list = self.t2s_model.model.infer_panel(
  File "D:\face\GPT-SoVITS-Inference\GPT_SoVITS\AR\models\t2s_model.py", line 642, in infer_panel
    xy_padding_mask.view(bsz, 1, 1, src_len).expand(-1, self.num_head, -1, -1)
RuntimeError: shape '[1, 1, 1, 171]' is invalid for input of size 163
INFO:werkzeug:127.0.0.1 - - [22/Mar/2024 10:10:52] "POST /tts HTTP/1.1" 500 -

应当是中英文分词出现了问题，abcdefg被分成了中文，所以就会报错

**Comment by KamioRinn** [comment]
实际输入的目标文本(每句): 请读出来abcdefg。
['请读出来', 'abcdefg。 ']
['zh', 'en']
前端处理后的文本(每句): 请读出来abcdefg.

无法复现，请更新代码及依赖后重试

**Comment by 7yilink** [comment]
直接使用官方的可以了，A 会读成 e(恶） 我想让它 读成 哎，需要把配置改成什么样的

**Comment by KamioRinn** [comment]
> 直接使用官方的可以了，A 会读成 e(恶） 我想让它 读成 哎，需要把配置改成什么样的

大写A读诶，小写a读额
