### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by wrl1224** [RVC-Boss/GPT-SoVITS#850]
############ 切分文本 ############
实际输入的目标文本:
你好问题测试。(＾ω＾)
实际输入的目标文本(切句后):
你好问题测试。
(＾ω＾)
############ 提取文本Bert特征 ############
 50%|█████     | 1/2 [00:00<00:00, 36.25it/s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/heike/anaconda3/envs/GPT-SoVITS-0319/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/api.py", line 514, in tts_endpoint
    return handle_new(text, text_lang, ref_audio_path, prompt_text, prompt_lang,text_split_method)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/api.py", line 475, in handle_new
    sampling_rate, audio_data = next(gen)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/GPT_SoVITS/inference_webui.py", line 147, in inference
    yield next(tts_pipline.run(inputs))
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/GPT_SoVITS/TTS_infer_pack/TTS.py", line 642, in run
    data = self.text_preprocessor.preprocess(text, text_lang, text_split_method)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py", line 60, in preprocess
    phones, bert_features, norm_text = self.segment_and_extract_feature_for_text(text, lang)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py", line 103, in segment_and_extract_feature_for_text
    phones, bert_features, norm_text = self.extract_bert_feature(textlist, langlist)
  File "/home/heike/hkdata/Code/wrl/GPT-SoVITS-0310-liuyue/GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py", line 157, in extract_bert_feature
    bert_feature = torch.cat(bert_feature_list, dim=1)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

这个问题是我在尝试使用api.py 进行推理遇到的

传入需要生成的音频文本为：你好问题测试。(＾ω＾)

则会触发以上报错。

但是传入的是：你好问题测试(＾ω＾)

则不会报错。

**Comment by XXXXRT666** [comment]
按照句号切分后，颜文字成为单独句子，因其不含音素，或者说在clean text中被全部过滤，故报错，删除颜文字或句号，使用原版api可解决
