### ISSUE TITLE
TTS推理WebUI->需要合成的文本对于空行的改进

### ISSUE THREAD

**Issue by c4fun** [RVC-Boss/GPT-SoVITS#86]
## 问题描述
在TTS推理中，如果有空行，则会报错

### 报错截图
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/5254836/f9354cfd-3cc0-4a73-8a5d-cc76a31bbead)

### 命令行报错信息
```
Running on local URL:  http://0.0.0.0:9872
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.gradio.app:443
DEBUG:urllib3.connectionpool:https://api.gradio.app:443 "POST /gradio-launched-analytics/ HTTP/1.1" 200 None
DEBUG:httpcore.connection:connect_tcp.started host='localhost' port=9872 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f14bf5b2310>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache /home/xxx/code/github.com/temp/GPT-SoVITS/TEMP/jieba.cache
DEBUG:jieba:Loading model from cache /home/xxx/code/github.com/temp/GPT-SoVITS/TEMP/jieba.cache
Loading model cost 0.266 seconds.
DEBUG:jieba:Loading model cost 0.266 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
  2%|█▉                                                                                                                    | 24/1500 [00:00<00:06, 235.86it/s]T2S Decoding EOS [119 -> 154]
  2%|██▊                                                                                                                   | 35/1500 [00:00<00:05, 247.83it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 408, in async_iteration
    return next(iterator)
  File "/home/xxx/code/github.com/temp/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 188, in get_tts_wav
    bert2 = get_bert_feature(norm_text2, word2ph2).to(device)
  File "/home/xxx/code/github.com/temp/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 55, in get_bert_feature
    phone_level_feature = torch.cat(phone_level_feature, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Fri, 19 Jan 2024 12:33:06 GMT'), (b'server', b'uvicorn'), (b'content-length', b'14'), (b'content-type', b'application/json')])
INFO:httpx:HTTP Request: POST http://localhost:9872/api/predict "HTTP/1.1 500 Internal Server Error"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'date', b'Fri, 19 Jan 2024 12:33:07 GMT'), (b'server', b'uvicorn'), (b'content-length', b'16'), (b'content-type', b'application/json')])
INFO:httpx:HTTP Request: POST http://localhost:9872/reset "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
```

## Mitigation
如果去掉空行，则没有问题。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/5254836/a27d2297-5801-4b46-82f3-ad9b4c5788c9)

## 期望表现
- 对于空行有预处理，这样就算有空行，也不会报错。

**Comment by RVC-Boss** [comment]
已解决。

**Comment by c4fun** [comment]
> 最新代码，报蕾丝的错误： File "/Users/yunyuexingsheng/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread return await future File "/Users/yunyuexingsheng/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run result = context.run(func, *args) File "/Users/yunyuexingsheng/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/gradio/utils.py", line 408, in async_iteration return next(iterator) File "/Users/yunyuexingsheng/IdeaProjects/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 196, in get_tts_wav bert1 = get_bert_feature(norm_text1, word2ph1).to(device) File "/Users/yunyuexingsheng/IdeaProjects/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 60, in get_bert_feature phone_level_feature = torch.cat(phone_level_feature, dim=0) RuntimeError: torch.cat(): expected a non-empty list of Tensors

我后来也发现了，你查一下你的文件里面，是不是有一行纯符号的。比如“=”，“-”，“*”组成的分隔符，这些符号都是不可以TTS发声的，所以报错了。

我之前的排除空格是一个初步的解决方案，它只排除了空行，没有排除分隔符。如果要解决这种分隔符问题，有两种思路：
1. 把不能发声的分隔符，单独做个字典，然后做匹配。如果一行的全部字符都在这个字典内，则跳过改行。
2. 直接try-catch。

##临时解决方案：删掉文件中的分隔符行
