### ISSUE TITLE
当用训练好的两个文件直接调用API时候

### ISSUE THREAD

**Issue by xihajun** [RVC-Boss/GPT-SoVITS#877]
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 532, in load_state_dict
    return torch.load(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1039, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/GPT-SoVITS/api.py", line 210, in <module>
    bert_model = AutoModelForMaskedLM.from_pretrained(bert_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3335, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 542, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
```
请问不知道是哪里需要git lfs pull呢，在当前页面试过了感觉不太行

还是说模型没有下载好，能不能直接用HF？

**Comment by xihajun** [comment]
# Clone the required DAMO ASR models
git clone https://www.modelscope.cn/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git
git clone https://www.modelscope.cn/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch.git
git clone https://www.modelscope.cn/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch.git

found it

**Comment by xihajun** [comment]
还是不行

**Comment by XXXXRT666** [comment]
预训练模型
