### ISSUE TITLE
WSL 训练模型时报错

### ISSUE THREAD

**Issue by shyo641** [RVC-Boss/GPT-SoVITS#913]
使用了 conda 虚拟环境，cuda12.4，python39，应该是多进程的原因？报错重复了很多遍。

"/home/shyo/miniconda3/envs/GPTSOVITS/bin/python3" GPT_SoVITS/s2_train.py --config "/mnt/d/Hobbies/GPT-SoVITS/TEMP/tmp_s2.json"
INFO:ql_en:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 4, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 2, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/ql_en'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/ql_en', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'ql_en', 'pretrain': None, 'resume_step': None}
phoneme_data_len: 47
wav_data_len: 94
100%|█████████████████████████████████████████████████████████████████████████████████| 94/94 [00:00<00:00, 1312.05it/s]
skipped_phone:  0 , skipped_dur:  0
total left:  94
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
ssl_proj.weight not requires_grad
ssl_proj.bias not requires_grad
INFO:ql_en:loaded pretrained GPT_SoVITS/pretrained_models/s2G488k.pth
<All keys matched successfully>
INFO:ql_en:loaded pretrained GPT_SoVITS/pretrained_models/s2D488k.pth
<All keys matched successfully>
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
0it [00:00, ?it/s]/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
OSError: [Errno 95] Operation not supported
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
OSError: [Errno 95] Operation not supported
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/shyo/miniconda3/envs/GPTSOVITS/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported

**Comment by xiaokang00010** [comment]
What's ur solution to it? I encountered the same issue today.
