### ISSUE TITLE
UVR  使用中出现  No such file or directory

### ISSUE THREAD

**Issue by xiaolongww** [RVC-Boss/GPT-SoVITS#915]
各位大佬好，这里我想问个问题：
启动UVR后我填入路径、选择H2后点击执行，控制台出现报错：
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/b839eb3b-3696-4860-a271-14d1fea51894)

另外网页端的日志如下：
高兴 [高质量].wav.reformatted.wav->Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\core\audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\core\audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\BaiduNetdiskDownload\\sadtalkerrrrrrrrrrr\\GPT-SoVITS-main\\TEMP/高兴 [高质量].wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\webui.py", line 82, in uvr
    pre_fun._path_audio_(
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\vr.py", line 62, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\core\audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\core\audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\BaiduNetdiskDownload\\sadtalkerrrrrrrrrrr\\GPT-SoVITS-main\\TEMP/高兴 [高质量].wav.reformatted.wav'

这是截图：

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/9c826640-d250-43dd-87a6-4a6c14c7f768)

希望有大佬能解惑，提前感谢了！

**Comment by iamcym** [comment]
不要用带中文的路径

**Comment by SapphireLab** [comment]
中文关系不大，问题在 ffmpeg 命令中路径没有用引号包括，因此执行时遇到了空格，导致文件路径读取不完整，转换失败导致后续步骤找不到文件。

临时方法：去掉文件名中的空格
修复方法：#917

**Comment by xiaolongww** [comment]
好的，首先感谢大佬们的回复  : )
然后我试了将文件名空格删除后，重新尝试，发现虽然仍然报错，不过输出信息略有不同：

控制台——
![企业微信截图_17121323796007](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/6edae820-bc41-473b-959a-862156f1a7d9)

网页端——
高兴[高质量].wav.reformatted.wav->Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\webui.py", line 82, in uvr
    pre_fun._path_audio_(
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\vr.py", line 121, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\lib\lib_v5\spec_utils.py", line 401, in cmb_spectrogram_to_wave
    spectrogram_to_wave(
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\tools\uvr5\lib\lib_v5\spec_utils.py", line 299, in spectrogram_to_wave
    wave_left = librosa.istft(spec_left, hop_length=hop_length)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
  File "D:\BaiduNetdiskDownload\sadtalkerrrrrrrrrrr\GPT-SoVITS-main\env39\lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/832130d2-a8e1-48c3-8da9-01656ddc9670)

**Comment by SapphireLab** [comment]
这个问题是 libsora 和 numpy 出现了一点冲突.
可以考虑降级 numpy 版本 (大概是 1.23.5) 或者升级 libsora (0.10+)

官方 issue: https://github.com/librosa/librosa/pull/1594

**Comment by SapphireLab** [comment]
这个问题是 libsora 和 numpy 出现了一点冲突.
可以考虑降级 numpy 版本 (大概是 1.23.5) 或者升级 libsora (0.10+)

参考链接: `https://github.com/librosa/librosa/pull/1594`
> (删了重发还是没能去掉引用不好意思, Rewrites still don't remove issue reference , I'm sorry)

**Comment by xiaolongww** [comment]
解决了！非常感谢！
另外提醒一下，是 librosa 

我的操作是：先查看numpy，发现是1.23.5；然后查看librosa，是librosa==0.9.2 （这个在requirement.txt里也是这个版本）
然后我直接pip install librosa==0.10.1

**Comment by xiaolongww** [comment]
解决了！非常感谢！
另外提醒一下，是 librosa 

我的操作是：先查看numpy，发现是1.23.5；然后查看librosa，是librosa==0.9.2 （这个在requirement.txt里也是这个版本）
然后我直接pip install librosa==0.10.1
