### ISSUE TITLE
错误信息求解

### ISSUE THREAD

**Issue by wanjia233** [RVC-Boss/GPT-SoVITS#918]
“冥火”这个词在转化成中文语音的时候给出了`Error`的提示
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/162721121/09252e0c-a748-44f0-a39a-71ccc47bf617)
命令行信息：

```
Traceback (most recent call last):
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\GPT_SoVITS\inference_webui.py", line 438, in get_tts_wav
    bert2 = get_bert_final(phones2, word2ph2, norm_text2, text_language, device).to(dtype)
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\GPT_SoVITS\inference_webui.py", line 348, in get_bert_final
    bert = get_bert_feature(text, word2ph).to(device)
  File "G:\GPT-SoVITS-beta0217\GPT-SoVITS-beta0217\GPT_SoVITS\inference_webui.py", line 100, in get_bert_feature
    phone_level_feature = torch.cat(phone_level_feature, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

而转化成日语是正常的

求解

**Comment by SapphireLab** [comment]
该更新代码了，#556
