### ISSUE TITLE
文本获取进程报错

### ISSUE THREAD

**Issue by AN94565** [RVC-Boss/GPT-SoVITS#924]
在尝试使用一键三连时卡在了第一步文本获取进程，后面尝试了单独点击发现其余两步都没有问题，看过后发现是缺失wordsegment，但在使用pip安装后仍然报错，后台报错如下：

P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "P:\BaiduNetdiskDownload\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\webui.py", line 414, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'

截图如下
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/66905666/c3677fc3-4c28-494d-85c9-07142daa0c28)

**Comment by SapphireLab** [comment]
你这图截的，音频文件夹没填?

**Comment by AN94565** [comment]
> 你这图截的，音频文件夹没填?

这个跟音频没填没关系吧，我是单独点的文本获取，跟音频有关的是第二步吧

**Comment by XXXXRT666** [comment]
在runtime 文件夹里python -m pip install wordsegment

**Comment by SapphireLab** [comment]
你说得对，但记得填。
看日志还是缺失wordsegment，可能是pip没装到整合包的环境里。
先检查一下 pip list 里有没有吧

```
runtime\python.exe -m pip list
```

没有就装
```
runtime\python.exe -m pip install wordsegment
```

**Comment by AN94565** [comment]
感谢各位大佬的帮助，问题已经解决了，此issue终结

**Comment by xhoxye** [comment]
> 感谢各位大佬的帮助，问题已经解决了，此issue终结

你是怎么解决的？为什么我按照上面的方法，安装了wordsegment，还是一样的错误
`"E:\AI\voice\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\AI\voice\GPT-SoVITS-beta\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\voice\GPT-SoVITS-beta\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "E:\AI\voice\GPT-SoVITS-beta\webui.py", line 414, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xhox0406/2-name2text-0.txt'`

**Comment by SapphireLab** [comment]
> > 感谢各位大佬的帮助，问题已经解决了，此issue终结
> 
> 你是怎么解决的？为什么我按照上面的方法，安装了wordsegment，还是一样的错误 
> File "E:\AI\voice\GPT-SoVITS-beta\GPT_SoVITS\text\english.py", line 4, in import wordsegment 
> ModuleNotFoundError: No module named 'wordsegment' 

截图第二句提示是提示更新pip的，但路径开头不是GPT-SoVITS环境该在的E盘，即 `E:\AI\voice\GPT-SoVITS-beta\runtime` 所以你应该还是没有装对位置。

在 `E:\AI\voice\GPT-SoVITS-beta` 文件夹的地址栏输入 cmd 再执行上面的命令试试。

注：
因为 cmd 和 powershell 的语法有区别。
1. 在 `E:\AI\voice\GPT-SoVITS-beta` 路径下使用 `runtime\python.exe -m pip ~`
2. 在 `E:\AI\voice\GPT-SoVITS-beta\runtime` 里使用 `python.exe -m pip ~`，

在 cmd 中这两种方式应该等价， 
在 powershell 中这两条方式可能会不等价，第二种应该使用 `.\python.exe -m pip ~` 指定当前目录下的 python.exe。

你可以分别执行这两种方式验证一下 python 版本判断环境是否正确。

**Comment by xhoxye** [comment]
> runtime\python.exe -m pip list

非常感谢，的确是安装路径错误，重新用cmd在E:\AI\voice\GPT-SoVITS-beta 安装后解决

**Comment by xtopass** [comment]
```
"D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
    from text.cleaner import clean_text
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\workspace\GPT-SoVITS-beta0217\webui.py", line 414, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
错误: 没有找到进程 "1996"。
错误: 没有找到进程 "10944"。
```
麻烦各位大佬帮我看看，我的是哪里出错了（一键三连过程）。谢谢

**Comment by XXXXRT666** [comment]
> ```
> 
> "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> 
> "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> 
>     from text.cleaner import clean_text
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> 
>     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> 
>     from text.cleaner import clean_text
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> 
>     import wordsegment
> 
> ModuleNotFoundError: No module named 'wordsegment'
> 
>     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> 
>     import wordsegment
> 
> ModuleNotFoundError: No module named 'wordsegment'
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
> 
>     output = await app.blocks.process_api(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
> 
>     result = await self.call_function(fn_index, inputs, iterator, request)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
> 
>     prediction = await anyio.to_thread.run_sync(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
> 
>     return await get_asynclib().run_sync_in_worker_thread(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
> 
>     return await future
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
> 
>     result = context.run(func, *args)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
> 
>     return next(iterator)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\webui.py", line 414, in open1a
> 
>     with open(txt_path, "r", encoding="utf8") as f:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
> 
> 错误: 没有找到进程 "1996"。
> 
> 错误: 没有找到进程 "10944"。
> 
> ```
> 
> 麻烦各位大佬帮我看看，我的是哪里出错了（一键三连过程）。谢谢

缺少依赖，教程文档报错合集1.6

**Comment by xtopass** [comment]
> 缺少依赖，教程文档报错合集1.6

已经按照依赖了，成功解决了当前问题，后续步骤也成功执行了，感谢回复

**Comment by chenyi945** [comment]
英文的时候正常，到日语的时候就文本进程失败，提示
  _global_jtalk = OpenJTalk(
  File "pyopenjtalk\openjtalk.pyx", line 179, in pyopenjtalk.openjtalk.OpenJTalk.__cinit__
RuntimeError: Failed to initalize Mecab

![微信截图_20240929125143](https://github.com/user-attachments/assets/989d1959-ea44-4be7-ba52-35b7b12adc8f)

**Comment by XXXXRT666** [comment]
把user_dict的使用注释掉
