### ISSUE TITLE
ASR报错

### ISSUE THREAD

**Issue by FLH1030** [RVC-Boss/GPT-SoVITS#954]
中文批量离线ASR工具报错，请问是什么原因呢：
Traceback (most recent call last):
  File "/data/workpace/GPT-SoVITS/tools/asr/funasr_asr.py", line 17, in <module>
    model = AutoModel(
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 92, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 143, in build_model
    kwargs = download_model(**kwargs)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/funasr/download/download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/funasr/download/download_from_hub.py", line 32, in download_from_ms
    kwargs["tokenizer_conf"]["token_list"] = os.path.join(model_or_path, "tokens.txt")
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/data/workpace/GPT-SoVITS/.conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key tokenizer_conf
    full_key: tokenizer_conf
    object_type=dict

**Comment by SapphireLab** [comment]
检查 FunASR 版本尝试更新或者尝试 #704
