### ISSUE TITLE
一键三连错误

### ISSUE THREAD

**Issue by fengyewater** [RVC-Boss/GPT-SoVITS#969]
请问怎么解决
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
成功: 已终止 PID 17800 (属于 PID 9156 子进程)的进程。
成功: 已终止 PID 9156 (属于 PID 17648 子进程)的进程。
"D:\AI\SoVITS\GPT-SoVITS-beta0306fix2\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\AI\SoVITS\GPT-SoVITS-beta0306fix2\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\AI\SoVITS\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "os.py", line 684, in __setitem__
  File "os.py", line 742, in check_str
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "D:\AI\SoVITS\GPT-SoVITS-beta0306fix2\GPT_SoVITS\prepare_datasets\1-get-text.py", line 10, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ.get("_CUDA_VISIBLE_DEVICES")
  File "os.py", line 684, in __setitem__
  File "os.py", line 742, in check_str
TypeError: str expected, not NoneType
Traceback (most recent call last):
  File "D:\AI\SoVITS\GPT-SoVITS-beta0306fix2\webui.py", line 580, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/first/2-name2text-0.txt'
错误: 没有找到进程 "14360"。
错误: 没有找到进程 "4100"。

**Comment by fengyewater** [comment]
![Uploading 屏幕截图 2024-04-14 145211.png…]()

**Comment by XXXXRT666** [comment]
没N卡

**Comment by fengyewater** [comment]
请问还有没有其他的方法，没有N卡的话










                       
原始邮件
                       
                     

发件人："XXXXRT666"< ***@***.*** &gt;;

发件时间：2024/4/14 15:04

收件人："RVC-Boss/GPT-SoVITS"< ***@***.*** &gt;;

抄送人："fengyewater"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [RVC-Boss/GPT-SoVITS] 一键三连错误 (Issue #969)




 
没N卡

**Comment by xtopass** [comment]
```
"D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text.cleaner import clean_text
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
    from text.cleaner import clean_text
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
    import wordsegment
ModuleNotFoundError: No module named 'wordsegment'
Traceback (most recent call last):
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\workspace\GPT-SoVITS-beta0217\webui.py", line 414, in open1a
    with open(txt_path, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
错误: 没有找到进程 "1996"。
错误: 没有找到进程 "10944"。

```
我的也是一键三连过程出错

**Comment by XXXXRT666** [comment]
> ```
> 
> "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> 
> "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> 
>     from text.cleaner import clean_text
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> 
>     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> 
>     from text.cleaner import clean_text
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> 
>     import wordsegment
> 
> ModuleNotFoundError: No module named 'wordsegment'
> 
>     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> 
>     import wordsegment
> 
> ModuleNotFoundError: No module named 'wordsegment'
> 
> Traceback (most recent call last):
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
> 
>     output = await app.blocks.process_api(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
> 
>     result = await self.call_function(fn_index, inputs, iterator, request)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
> 
>     prediction = await anyio.to_thread.run_sync(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
> 
>     return await get_asynclib().run_sync_in_worker_thread(
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
> 
>     return await future
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
> 
>     result = context.run(func, *args)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
> 
>     return next(iterator)
> 
>   File "D:\workspace\GPT-SoVITS-beta0217\webui.py", line 414, in open1a
> 
>     with open(txt_path, "r", encoding="utf8") as f:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
> 
> 错误: 没有找到进程 "1996"。
> 
> 错误: 没有找到进程 "10944"。
> 
> 
> 
> ```
> 
> 我的也是一键三连过程出错

缺少依赖，教程文档报错合集1.6

**Comment by xtopass** [comment]
> 缺少依赖，教程文档报错合集1.6

感谢回复，已经解决了！谢谢

**Comment by ihxkjggg** [comment]
> > 缺少依赖，教程文档报错合集1.6
> 
> 感谢回复，已经解决了！谢谢

你好，请问怎么解决的呢？我也是报这个错！单步运行和一键三连都一样

**Comment by xtopass** [comment]
> > > 缺少依赖，教程文档报错合集1.6
> > 
> > 
> > 感谢回复，已经解决了！谢谢
> 
> 你好，请问怎么解决的呢？我也是报这个错！单步运行和一键三连都一样

可能是缺失wordsegment，可能是pip没装到整合包的环境里。
先检查一下 pip list 里有没有吧

runtime\python.exe -m pip list
没有就装

runtime\python.exe -m pip install wordsegment

**Comment by one-pip** [comment]
> > ```
> > 
> > "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> > 
> > "D:\workspace\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> > 
> > Traceback (most recent call last):
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> > 
> >     from text.cleaner import clean_text
> > 
> > Traceback (most recent call last):
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 18, in <module>
> > 
> >     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> > 
> >     from text.cleaner import clean_text
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\cleaner.py", line 1, in <module>
> > 
> >     import wordsegment
> > 
> > ModuleNotFoundError: No module named 'wordsegment'
> > 
> >     from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\GPT_SoVITS\text\english.py", line 4, in <module>
> > 
> >     import wordsegment
> > 
> > ModuleNotFoundError: No module named 'wordsegment'
> > 
> > Traceback (most recent call last):
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
> > 
> >     output = await app.blocks.process_api(
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
> > 
> >     result = await self.call_function(fn_index, inputs, iterator, request)
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
> > 
> >     prediction = await anyio.to_thread.run_sync(
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
> > 
> >     return await get_asynclib().run_sync_in_worker_thread(
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
> > 
> >     return await future
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
> > 
> >     result = context.run(func, *args)
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
> > 
> >     return next(iterator)
> > 
> >   File "D:\workspace\GPT-SoVITS-beta0217\webui.py", line 414, in open1a
> > 
> >     with open(txt_path, "r", encoding="utf8") as f:
> > 
> > FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'
> > 
> > 错误: 没有找到进程 "1996"。
> > 
> > 错误: 没有找到进程 "10944"。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的也是一键三连过程出错
> 
> 缺少依赖，教程文档报错合集1.6

教程文档报错合集1.6在哪里？
