### ISSUE TITLE
发现一个奇怪的问题，更新到最新版本后，首次并发10个请求正常，以后再次并发超过3个请求，就出现如下异常：

### ISSUE THREAD

**Issue by hezilon** [RVC-Boss/GPT-SoVITS#972]

**Comment by hezilon** [comment]
控制台信息如下：INFO:     127.0.0.1:53916 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53917 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53918 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53919 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53920 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53921 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53922 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53923 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53924 - "POST / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53925 - "POST / HTTP/1.1" 200 OK
  0%|                                                                                                                                                                          | 1/1500 [00:00<04:45,  5.25it/s]ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 273, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 269, in wrap
    await func()
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\api.py", line 427, in get_tts_wav
    phones1, bert1, norm_text1 = get_phones_and_bert(prompt_text, prompt_language)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\api.py", line 277, in get_phones_and_bert
    for tmp in LangSegment.getTexts(text):
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 676, in getTexts
    return LangSegment.getTexts(text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 572, in getTexts
    text = LangSegment._parse_symbols(text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 508, in _parse_symbols
    cur_word = LangSegment._process_tags([] , text , True)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 461, in _process_tags
    LangSegment._parse_language(words , text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 330, in _parse_language
    LangSegment._addwords(words,language,text,score)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 250, in _addwords
    else:LangSegment._saveData(words,language,text,score)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 228, in _saveData
    LangSegment._statistics(data["lang"],data["text"])
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 191, in _statistics
    if not "|" in language:lang_count[language] += int(len(text)*2) if language == "zh" else len(text)
TypeError: list indices must be integers or slices, not str
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 273, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 269, in wrap
    await func()
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\api.py", line 437, in get_tts_wav
    phones2, bert2, norm_text2 = get_phones_and_bert(text, text_language)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\api.py", line 277, in get_phones_and_bert
    for tmp in LangSegment.getTexts(text):
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 676, in getTexts
    return LangSegment.getTexts(text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 572, in getTexts
    text = LangSegment._parse_symbols(text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 508, in _parse_symbols
    cur_word = LangSegment._process_tags([] , text , True)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 461, in _process_tags
    LangSegment._parse_language(words , text)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 330, in _parse_language
    LangSegment._addwords(words,language,text,score)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 250, in _addwords
    else:LangSegment._saveData(words,language,text,score)
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 228, in _saveData
    LangSegment._statistics(data["lang"],data["text"])
  File "D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\LangSegment\LangSegment.py", line 191, in _statistics
    if not "|" in language:lang_count[language] += int(len(text)*2) if language == "zh" else len(text)
TypeError: list indices must be integers or slices, not str
  1%|█▏                                                                                                                                                                       | 11/1500 [00:01<03:47,  6.54it/s]T2S Decoding EOS [149 -> 158]                                                                                                                                                  | 10/1500 [00:01<03:30,  7.08it/s]
  1%|▉                                                                                                                                                                         | 8/1500 [00:01<04:23,  5.67it/s]
  3%|████▊                                                                                                                                                                    | 43/1500 [00:06<03:16,  7.43it/s]T2S Decoding EOS [149 -> 194]                                                                                                                                                  | 46/1500 [00:05<02:45,  8.79it/s]
  3%|████▉                                                                                                                                                                    | 44/1500 [00:05<03:04,  7.91it/s]
  3%|█████                                                                                                                                                                    | 45/1500 [00:06<03:16,  7.41it/s]T2S Decoding EOS [149 -> 198]                                                                                                                                                  | 48/1500 [00:05<02:52,  8.41it/s]
  3%|█████▍                                                                                                                                                                   | 48/1500 [00:06<03:03,  7.93it/s]
  3%|█████▎                                                                                                                                                                   | 47/1500 [00:06<02:57,  8.19it/s]T2S Decoding EOS [149 -> 197]                                                                                                                                                  | 44/1500 [00:05<02:47,  8.67it/s]
  3%|█████▎                                                                                                                                                                   | 47/1500 [00:06<03:27,  7.01it/s]
  3%|████▊                                                                                                                                                                    | 43/1500 [00:05<03:07,  7.76it/s]T2S Decoding EOS [149 -> 221]                                                                                                                                                  | 46/1500 [00:05<02:55,  8.29it/s]
  5%|███████▉                                                                                                                                                                 | 71/1500 [00:07<02:28,  9.63it/s]
  3%|█████                                                                                                                                                                    | 45/1500 [00:05<02:56,  8.26it/s]T2S Decoding EOS [149 -> 234]                                                                                                                                                  | 49/1500 [00:05<02:36,  9.26it/s]
  6%|█████████▍                                                                                                                                                               | 84/1500 [00:08<02:22,  9.93it/s]
  4%|███████▍                                                                                                                                                                 | 66/1500 [00:07<01:37, 14.75it/s]T2S Decoding EOS [149 -> 250]                                                                                                                                                  | 71/1500 [00:07<01:30, 15.75it/s]
  7%|███████████▏                                                                                                                                                            | 100/1500 [00:08<02:04, 11.21it/s]
  6%|█████████▍                                                                                                                                                               | 84/1500 [00:08<01:15, 18.72it/s]T2S Decoding EOS [149 -> 260]
  7%|████████████▎                                                                                                                                                           | 110/1500 [00:09<01:59, 11.60it/s]

**Comment by hezilon** [comment]
> 升级一下 LangSegment 版本>=0.3.2：
> 
> ```
> pip3 install LangSegment>=0.3.2 -i https://pypi.org/simple
> ```
> 
> 或者，直接使用以下命令在线升级：
> 
> ```
> pip3 install LangSegment -i  https://pypi.org/simple --upgrade
> ```

整合包里好像没有pip3这个模块：
D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2>runtime\python -m pip3 install LangSegment>=0.3.2 -i https://pypi.org/simple
D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\runtime\python.exe: No module named pip3

D:\work-cg\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2>

**Comment by hezilon** [comment]
> 用 pip 也一样：
> 
> ```
> runtime\python.exe -m pip install LangSegment -i  https://pypi.org/simple -U
> ```
> 
> 或者指定版本：
> 
> ```
> runtime\python.exe -m pip install LangSegment>=0.3.2 -i https://pypi.org/simple
> ```

这样应该是安装，测试了一下无效，我用下面的升级命令执行成功了：
runtime\python -m pip install --upgrade LangSegment
