### ISSUE TITLE
240419版本（并行推理分支）报错

### ISSUE THREAD

**Issue by kebinzhi** [RVC-Boss/GPT-SoVITS#999]
240419版本（并行推理分支）报错，回退上个版本正常：

AttributeError: 'list' object has no attribute 'shape'
Loading Text2Semantic weights from GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
Loading VITS weights from GPT_SoVITS/pretrained_models/s2G488k.pth
Traceback (most recent call last):
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\GPT_SoVITS\inference_webui.py", line 121, in inference
    for item in tts_pipeline.run(inputs):
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\runtime\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\GPT_SoVITS\TTS_infer_pack\TTS.py", line 857, in run
    raise e
  File "D:\My Program Files\GPT-SoVITS-fast_inference_240420\GPT_SoVITS\TTS_infer_pack\TTS.py", line 752, in run
    prompt = self.prompt_cache["prompt_semantic"].expand(all_phoneme_ids.shape[0], -1).to(self.configs.device)
AttributeError: 'list' object has no attribute 'shape'

**Comment by SapphireLab** [comment]
#994
